{
  "hash": "dd5c1126a89385efa5ec346909c2b8ff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multivariate Confirmation Analysis on Persistent Disconnection\"\neditor: visual\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLinking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggrepel)\nlibrary(scales)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'scales'\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(shiny)\nlibrary(shinycssloaders)\nlibrary(ggiraph)\nlibrary(kableExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rmapshaper)\nlibrary(cowplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'cowplot'\n\nThe following object is masked from 'package:lubridate':\n\n    stamp\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DT)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'DT'\n\nThe following objects are masked from 'package:shiny':\n\n    dataTableOutput, renderDataTable\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(htmlwidgets)\nlibrary(RColorBrewer)\nlibrary(readxl)\nlibrary(janitor)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'janitor'\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(lubridate)\nlibrary(systemfonts)\nreset_font_cache()\nlibrary(ggtext)\nlibrary(gmodels)\nlibrary(fastDummies)\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(glmnet)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Matrix\n\nAttaching package: 'Matrix'\n\nThe following objects are masked from 'package:tidyr':\n\n    expand, pack, unpack\n\nLoaded glmnet 5.0\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(glmnetUtils)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'glmnetUtils'\n\nThe following objects are masked from 'package:glmnet':\n\n    cv.glmnet, glmnet\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(pscl)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nClasses and Methods for R originally developed in the\nPolitical Science Computational Laboratory\nDepartment of Political Science\nStanford University (2002-2015),\nby and under the direction of Simon Jackman.\nhurdle and zeroinfl functions by Achim Zeileis.\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(sjPlot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'sjPlot'\n\nThe following objects are masked from 'package:cowplot':\n\n    plot_grid, save_plot\n\nThe following object is masked from 'package:ggplot2':\n\n    set_theme\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggforce)\nlibrary(openxlsx)\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaster.original <- read_csv(\"Data/SLEDS/Masters/Master-non-college-grads-disconnection.csv\") \n\nkable(names(master.original))\n```\n\n::: {.cell-output-display}\n\n\n|x                                                  |\n|:--------------------------------------------------|\n|PersonID                                           |\n|K12OrganizationID                                  |\n|OrganizationName                                   |\n|county.name                                        |\n|countyfp                                           |\n|Dem_Desc                                           |\n|edr                                                |\n|grad.year                                          |\n|grad.year.covid                                    |\n|Gender                                             |\n|economic.status                                    |\n|pseo.participant                                   |\n|SpecialEdStatus                                    |\n|non.english.home                                   |\n|RaceEthnicity                                      |\n|n.years.attended                                   |\n|ACTCompositeScore                                  |\n|took.ACT                                           |\n|ap.exam                                            |\n|total.cte.courses.taken                            |\n|ACTE.SPED                                          |\n|Agriculture..Food..and.Natural.Resources           |\n|Architecture...Construction                        |\n|Arts..A.V.Technology...Communication               |\n|Business..Management...Administrative              |\n|Diversified                                        |\n|Education...Training                               |\n|Finance                                            |\n|Government...Public.Administration                 |\n|Health.Science                                     |\n|Hospitality...Tourism                              |\n|Human.Services                                     |\n|Information.Technology                             |\n|Law..Public.Safety...Security                      |\n|Manufacturing                                      |\n|Marketing                                          |\n|Program.Area..Diversified.                         |\n|Science..Technology..Engineering....Mathematics    |\n|STEM                                               |\n|Transportation..Distribution...Logistics           |\n|Work.Experience.Handicapped                        |\n|Work.Experience.Handicapped..16.20..on.IEP.        |\n|Work.Experience.Career.Exploration..age.14.15.on.I |\n|Work.Experience.Disadvantaged                      |\n|Youth.Apprenticeship                               |\n|cte.achievement                                    |\n|english.learner                                    |\n|MCA.M                                              |\n|MCA.R                                              |\n|MCA.S                                              |\n|sat.taken                                          |\n|attended.ps                                        |\n|first.attend.ps                                    |\n|attended.ps.first.year                             |\n|attended.ps.years.hsgrad                           |\n|attended.ps.within.first.year.hsgrad               |\n|n.institutions                                     |\n|first.InstitutionSector                            |\n|ps.sector.1                                        |\n|ps.sector.2                                        |\n|ps.sector.3                                        |\n|ps.sector.4                                        |\n|ps.sector.5                                        |\n|ps.sector.6                                        |\n|ps.sector.7                                        |\n|ps.sector.8                                        |\n|ps.sector.9                                        |\n|ps.in.same.ruca                                    |\n|ps.in.same.edr                                     |\n|ps.in.same.pr                                      |\n|ps.in.MN                                           |\n|hs.grad.year                                       |\n|ps.attended.in.same.ruca                           |\n|ps.attended.in.same.edr                            |\n|ps.attended.in.same.pr                             |\n|ps.attended.in.MN                                  |\n|ps.grad                                            |\n|min.ps.grad.year                                   |\n|max.ps.grad.year                                   |\n|years.between.grads                                |\n|ps.grad.InstitutionSector                          |\n|highest.cred.level                                 |\n|ps.grad.in.same.ruca                               |\n|ps.grad.in.same.edr                                |\n|ps.grad.in.same.pr                                 |\n|ps.grad.in.MN                                      |\n|ps.grad.location                                   |\n|mn.emp.record.hs.grad.year                         |\n|mn.emp.record.hs.grad.year.2                       |\n|mn.emp.record.hs.grad.year.7                       |\n|meaningful.emp.hs.grad.year                        |\n|meaningful.emp.hs.grad.year.2                      |\n|meaningful.emp.hs.grad.year.7                      |\n|hs.grad.year.county.match                          |\n|hs.grad.year.2.county.match                        |\n|hs.grad.year.7.county.match                        |\n|hs.grad.year.edr.match                             |\n|hs.grad.year.2.edr.match                           |\n|hs.grad.year.7.edr.match                           |\n|hs.grad.year.region.match                          |\n|hs.grad.year.2.region.match                        |\n|hs.grad.year.7.region.match                        |\n|hs.grad.year.state.match                           |\n|hs.grad.year.2.state.match                         |\n|hs.grad.year.7.state.match                         |\n|ind.match.hs.grad.year                             |\n|ind.match.hs.grad.year.2                           |\n|ind.match.hs.grad.year.7                           |\n|avg.unemp.rate                                     |\n|wages.3year.avg                                    |\n|avg.wages.pct.state                                |\n|grad.year.1                                        |\n|grad.year.10                                       |\n|grad.year.5                                        |\n|after.ed.1                                         |\n|after.ed.2                                         |\n|after.ed.3                                         |\n|after.ed.4                                         |\n|after.ed.5                                         |\n|disconnected.cat                                   |\n|non_sustained                                      |\n|non.sustained.n                                    |\n|non_sustained.cat                                  |\n|no_record                                          |\n|no.record.n                                        |\n|no_record.cat                                      |\n\n\n:::\n\n```{.r .cell-code}\nkable(head(master.original))\n```\n\n::: {.cell-output-display}\n\n\n| PersonID| K12OrganizationID|OrganizationName                    |county.name | countyfp|Dem_Desc             |edr                   | grad.year|grad.year.covid |Gender | economic.status| pseo.participant| SpecialEdStatus| non.english.home|RaceEthnicity | n.years.attended| ACTCompositeScore|took.ACT | ap.exam| total.cte.courses.taken| ACTE.SPED| Agriculture..Food..and.Natural.Resources| Architecture...Construction| Arts..A.V.Technology...Communication| Business..Management...Administrative| Diversified| Education...Training| Finance| Government...Public.Administration| Health.Science| Hospitality...Tourism| Human.Services| Information.Technology| Law..Public.Safety...Security| Manufacturing| Marketing| Program.Area..Diversified.| Science..Technology..Engineering....Mathematics| STEM| Transportation..Distribution...Logistics| Work.Experience.Handicapped| Work.Experience.Handicapped..16.20..on.IEP.| Work.Experience.Career.Exploration..age.14.15.on.I| Work.Experience.Disadvantaged| Youth.Apprenticeship|cte.achievement               | english.learner| MCA.M| MCA.R| MCA.S| sat.taken|attended.ps | first.attend.ps| attended.ps.first.year| attended.ps.years.hsgrad|attended.ps.within.first.year.hsgrad | n.institutions| first.InstitutionSector| ps.sector.1| ps.sector.2| ps.sector.3| ps.sector.4| ps.sector.5| ps.sector.6| ps.sector.7| ps.sector.8| ps.sector.9|ps.in.same.ruca              |ps.in.same.edr |ps.in.same.pr |ps.in.MN              | hs.grad.year|ps.attended.in.same.ruca     |ps.attended.in.same.edr |ps.attended.in.same.pr |ps.attended.in.MN     |ps.grad |min.ps.grad.year |max.ps.grad.year |years.between.grads |ps.grad.InstitutionSector |highest.cred.level  |ps.grad.in.same.ruca |ps.grad.in.same.edr |ps.grad.in.same.pr |ps.grad.in.MN |ps.grad.location    |mn.emp.record.hs.grad.year |mn.emp.record.hs.grad.year.2 |mn.emp.record.hs.grad.year.7 |meaningful.emp.hs.grad.year |meaningful.emp.hs.grad.year.2 |meaningful.emp.hs.grad.year.7 |hs.grad.year.county.match |hs.grad.year.2.county.match |hs.grad.year.7.county.match |hs.grad.year.edr.match |hs.grad.year.2.edr.match |hs.grad.year.7.edr.match |hs.grad.year.region.match |hs.grad.year.2.region.match |hs.grad.year.7.region.match |hs.grad.year.state.match |hs.grad.year.2.state.match |hs.grad.year.7.state.match |ind.match.hs.grad.year |ind.match.hs.grad.year.2 |ind.match.hs.grad.year.7 | avg.unemp.rate| wages.3year.avg| avg.wages.pct.state|grad.year.1            |grad.year.10      |grad.year.5            |after.ed.1               |after.ed.2                                 |after.ed.3               |after.ed.4             |after.ed.5             |disconnected.cat            |non_sustained | non.sustained.n|non_sustained.cat            |no_record | no.record.n|no_record.cat            |\n|--------:|-----------------:|:-----------------------------------|:-----------|--------:|:--------------------|:---------------------|---------:|:---------------|:------|---------------:|----------------:|---------------:|----------------:|:-------------|----------------:|-----------------:|:--------|-------:|-----------------------:|---------:|----------------------------------------:|---------------------------:|------------------------------------:|-------------------------------------:|-----------:|--------------------:|-------:|----------------------------------:|--------------:|---------------------:|--------------:|----------------------:|-----------------------------:|-------------:|---------:|--------------------------:|-----------------------------------------------:|----:|----------------------------------------:|---------------------------:|-------------------------------------------:|--------------------------------------------------:|-----------------------------:|--------------------:|:-----------------------------|---------------:|-----:|-----:|-----:|---------:|:-----------|---------------:|----------------------:|------------------------:|:------------------------------------|--------------:|-----------------------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|:----------------------------|:--------------|:-------------|:---------------------|------------:|:----------------------------|:-----------------------|:----------------------|:---------------------|:-------|:----------------|:----------------|:-------------------|:-------------------------|:-------------------|:--------------------|:-------------------|:------------------|:-------------|:-------------------|:--------------------------|:----------------------------|:----------------------------|:---------------------------|:-----------------------------|:-----------------------------|:-------------------------|:---------------------------|:---------------------------|:----------------------|:------------------------|:------------------------|:-------------------------|:---------------------------|:---------------------------|:------------------------|:--------------------------|:--------------------------|:----------------------|:------------------------|:------------------------|--------------:|---------------:|-------------------:|:----------------------|:-----------------|:----------------------|:------------------------|:------------------------------------------|:------------------------|:----------------------|:----------------------|:---------------------------|:-------------|---------------:|:----------------------------|:---------|-----------:|:------------------------|\n|  1456500|             44383|EAGLE VALLEY SECONDARY              |Todd        |      153|Town/rural mix       |EDR 5 - North Central |      2008|Pre-covid grad  |M      |               0|               NA|               0|                0|Hispanic      |                1|                NA|No       |       0|                       1|         0|                                        1|                           0|                                    0|                                     0|           0|                    0|       0|                                  0|              0|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        0|                           0|                                           0|                                                  0|                             0|                    0|CTE Participant               |               0|    NA|    NA|    NA|         0|No          |              NA|                     NA|                       NA|Did not attend ps                    |              0|                      NA|           0|           0|           0|           0|           0|           0|           0|           0|           0|NA                           |NA             |NA            |NA                    |         2008|NA                           |NA                      |NA                     |NA                    |No      |NA               |NA               |NA                  |Never attended ps         |Did not graduate ps |NA                   |NA                  |NA                 |NA            |Did not graduate ps |No MN emp record           |No MN emp record             |No MN emp record             |No MN emp record            |No MN emp record              |No MN emp record              |No MN emp record          |No MN emp record            |No MN emp record            |No MN emp record       |No MN emp record         |No MN emp record         |No MN emp record          |No MN emp record            |No MN emp record            |No MN emp record         |No MN emp record           |No MN emp record           |No MN emp record       |No MN emp record         |No MN emp record         |       5.700000|        28114.67|           0.6820086|No MN emp record       |No MN emp record  |No MN emp record       |No MN emp record         |No MN emp record                           |No MN emp record         |No MN emp record       |No MN emp record       |Persistently disconnected   |Non-sustained |               0|Never non-sustained          |No record |           5|Persistently no-record   |\n| 10870895|            100018|SPECIAL EDUCATION FACILITIES        |Stearns     |      145|Urban/town/rural mix |EDR 7W- Central       |      2015|Pre-covid grad  |M      |               1|                0|               1|                1|Hispanic      |                6|                NA|No       |       0|                      14|         0|                                        0|                           0|                                    3|                                     0|           0|                    0|       0|                                  0|              0|                     0|              1|                      0|                             0|             0|         1|                          0|                                               0|    0|                                        4|                           0|                                           5|                                                  0|                             0|                    0|CTE Participant               |               1|     1|     1|     1|         0|No          |              NA|                     NA|                       NA|Did not attend ps                    |              0|                      NA|           0|           0|           0|           0|           0|           0|           0|           0|           0|NA                           |NA             |NA            |NA                    |         2015|NA                           |NA                      |NA                     |NA                    |No      |NA               |NA               |NA                  |Never attended ps         |Did not graduate ps |NA                   |NA                  |NA                 |NA            |Did not graduate ps |MN emp record              |MN emp record                |No MN emp record             |No meaningful emp           |No meaningful emp             |No MN emp record              |No meaningful emp         |No meaningful emp           |No MN emp record            |No meaningful emp      |No meaningful emp        |No MN emp record         |No meaningful emp         |No meaningful emp           |No MN emp record            |No meaningful emp        |No meaningful emp          |No MN emp record           |No meaningful emp      |No meaningful emp        |No MN emp record         |       4.300000|        41847.67|           0.8475591|Non-sustained WF       |After 2023        |No MN emp record       |Non-sustained WF_in_only |Non-sustained WF_out_only                  |No MN emp record         |No MN emp record       |No MN emp record       |Persistently disconnected   |Non-sustained |               2|Intermittently non-sustained |No record |           3|Broadly no-record        |\n|  4558841|            106300|HEALY SECONDARY                     |Morrison    |       97|Town/rural mix       |EDR 5 - North Central |      2009|Pre-covid grad  |M      |               1|                0|               1|                0|White         |                1|                NA|No       |       0|                       2|         0|                                        1|                           1|                                    0|                                     0|           0|                    0|       0|                                  0|              0|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        0|                           0|                                           0|                                                  0|                             0|                    0|CTE Concentrator or Completor |               0|    NA|    NA|    NA|         0|No          |              NA|                     NA|                       NA|Did not attend ps                    |              0|                      NA|           0|           0|           0|           0|           0|           0|           0|           0|           0|NA                           |NA             |NA            |NA                    |         2009|NA                           |NA                      |NA                     |NA                    |No      |NA               |NA               |NA                  |Never attended ps         |Did not graduate ps |NA                   |NA                  |NA                 |NA            |Did not graduate ps |No MN emp record           |MN emp record                |No MN emp record             |No MN emp record            |No meaningful emp             |No MN emp record              |No MN emp record          |No meaningful emp           |No MN emp record            |No MN emp record       |No meaningful emp        |No MN emp record         |No MN emp record          |No meaningful emp           |No MN emp record            |No MN emp record         |No meaningful emp          |No MN emp record           |No MN emp record       |No meaningful emp        |No MN emp record         |       8.266667|        30376.67|           0.7274629|Non-sustained WF       |Non-sustained WF  |No MN emp record       |Non-sustained WF_in_only |Non-sustained WF_in_only                   |Non-sustained WF_in_only |Sustained WF - Central |No MN emp record       |Persistently disconnected   |Non-sustained |               3|Broadly non-sustained        |No record |           1|Intermittently no-record |\n|  8339688|             89210|BIG LAKE SENIOR HIGH                |Sherburne   |      141|Entirely urban       |EDR 7W- Central       |      2010|Pre-covid grad  |F      |               1|               NA|               1|                0|White         |                3|                NA|No       |       0|                       5|         0|                                        0|                           0|                                    1|                                     0|           0|                    0|       0|                                  0|              3|                     0|              0|                      0|                             0|             1|         0|                          0|                                               0|    0|                                        0|                           0|                                           0|                                                  0|                             0|                    0|CTE Participant               |               0|     1|     1|     1|         0|No          |        20140825|                   2014|                        4|Did not attend ps                    |              1|                       4|           0|           0|           0|           1|           0|           0|           0|           0|           0|Outside RUCA                 |Outside EDR    |In same PR    |In MN                 |         2010|Outside RUCA                 |Outside EDR             |In same PR             |In MN                 |No      |NA               |NA               |NA                  |Never attended ps         |Did not graduate ps |NA                   |NA                  |NA                 |NA            |Did not graduate ps |MN emp record              |MN emp record                |MN emp record                |Meaningful emp              |Meaningful emp                |No meaningful emp             |No location match         |No location match           |No meaningful emp           |No location match      |No location match        |No meaningful emp        |No location match         |No location match           |No meaningful emp           |Location match           |Location match             |No meaningful emp          |No ind match           |No ind match             |No meaningful emp        |       7.900000|        34886.00|           0.8274406|Sustained WF - MN      |Non-sustained WF  |Sustained WF - MN      |Sustained WF - MN        |Non-sustained WF_mixed_in_out_simultaneous |Non-sustained WF_in_only |Sustained WF - MN      |Sustained WF - MN      |Intermittently disconnected |Non-sustained |               2|Intermittently non-sustained |No record |           0|Never no-record          |\n|  2014911|            168495|BUFFALO SENIOR HIGH                 |Wright      |      171|Urban/town/rural mix |EDR 7W- Central       |      2018|Pre-covid grad  |F      |               0|                0|               0|                0|White         |                3|                19|Yes      |       0|                       2|         0|                                        0|                           0|                                    0|                                     0|           1|                    0|       0|                                  0|              0|                     0|              0|                      0|                             0|             0|         0|                          0|                                               0|    0|                                        1|                           0|                                           0|                                                  0|                             0|                    0|CTE Participant               |               0|     3|     4|     3|         0|No          |        20180827|                   2018|                        0|Did not attend ps                    |              1|                       4|           0|           0|           0|           1|           0|           0|           0|           0|           0|In same RUCA                 |In same EDR    |In same PR    |In MN                 |         2018|In same RUCA                 |In same EDR             |In same PR             |In MN                 |No      |NA               |NA               |NA                  |Never attended ps         |Did not graduate ps |NA                   |NA                  |NA                 |NA            |Did not graduate ps |MN emp record              |MN emp record                |After 2023                   |Meaningful emp              |Meaningful emp                |After 2023                    |Location match            |Location match              |After 2023                  |Location match         |Location match           |After 2023               |Location match            |Location match              |After 2023                  |Location match           |Location match             |After 2023                 |No ind match           |No ind match             |After 2023               |       3.400000|        48075.33|           0.8902345|Sustained WF - Central |After 2023        |Sustained WF - Central |Sustained WF - Central   |Sustained WF - Central                     |Sustained WF - Central   |Sustained WF - Central |Sustained WF - Central |Consistently attached       |Non-sustained |               0|Never non-sustained          |No record |           0|Never no-record          |\n|  2402400|              1986|ST. MICHAEL-ALBERTVILLE SENIOR HIGH |Wright      |      171|Urban/town/rural mix |EDR 7W- Central       |      2011|Pre-covid grad  |M      |               0|                0|               0|                0|Asian/PI      |                3|                NA|No       |       0|                      11|         0|                                        1|                           1|                                    2|                                     0|           0|                    0|       0|                                  1|              0|                     0|              1|                      0|                             0|             1|         0|                          0|                                               0|    0|                                        4|                           0|                                           0|                                                  0|                             0|                    0|CTE Concentrator or Completor |               0|     3|     4|     3|         0|Yes         |        20120709|                   2012|                        1|Yes                                  |              4|                       4|           1|           0|           0|           1|           0|           0|           0|           0|           0|Inside and outside same RUCA |Outside EDR    |Outside PR    |Inside and outside MN |         2011|Inside and outside same RUCA |Outside EDR             |Outside PR             |Inside and outside MN |No      |NA               |NA               |NA                  |Did not grad              |Did not graduate ps |NA                   |NA                  |NA                 |NA            |Did not graduate ps |No MN emp record           |MN emp record                |MN emp record                |No MN emp record            |Meaningful emp                |Meaningful emp                |No MN emp record          |Location match              |No location match           |No MN emp record       |Location match           |No location match        |No MN emp record          |Location match              |No location match           |No MN emp record         |Location match             |Location match             |No MN emp record       |No ind match             |No ind match             |       7.900000|        37748.67|           0.8803669|Attending ps           |Sustained WF - MN |Sustained WF - MN      |Sustained WF - Central   |Sustained WF - MN                          |Sustained WF - MN        |Sustained WF - MN      |Sustained WF - MN      |Consistently attached       |Non-sustained |               0|Never non-sustained          |No record |           0|Never no-record          |\n\n\n:::\n:::\n\n\n# Multivariate Confirmation Analysis: Disconnection Persistence Among Non–Postsecondary Graduates\n\n## Introduction\n\nThe bivariate analysis of workforce disconnection among non-college graduates identified two distinct disconnection mechanisms operating within a single combined measure. Non-sustained employment (working, but below the sustained-employment threshold) and absence of any Minnesota employment record behave as structurally different phenomena: the former is front-loaded and largely resolves within five years, while the latter is bimodal and behaves as a durable end-state once established. Separating these two mechanisms revealed that different demographic and high-school-accomplishment variables predict each one — most notably, Special Education status and English learner status appeared to drive no-record persistence specifically, while Economic status and Gender appeared to drive non-sustained persistence specifically, and different racial/ethnic groups showed disparities concentrated in one mechanism or the other.\n\nThis multivariate analysis exists to confirm whether that mechanism-split pattern holds once all variables are considered simultaneously, rather than one at a time. This step is necessary because earlier work in this project has shown that bivariate relationships — particularly those involving English learner status — can substantially attenuate or shift once other variables, especially missing-data patterns in academic assessment scores, are accounted for in the same model. Before this mechanism-split finding is presented as a confirmed result, it should be tested under the same conditions.\n\n## Methodology\n\n### Study Population\n\nThe analytic sample is restricted to individuals who did **not** complete a postsecondary credential, consistent with the non-college-graduate population used throughout this project. The sample is further restricted to individuals who graduated (or exited postsecondary attendance, for those who attended without completing) after 2010, consistent with the cohort restriction applied elsewhere in this project to avoid the PSEO participation tracking gap present in earlier cohorts.\n\n### Dependent Variables\n\nThis analysis models two outcomes, each derived from the disconnection-persistence categories established in the bivariate analysis. Each graduate's workforce status was tracked across the first five years after exiting formal education (high school for direct-to-workforce graduates, or postsecondary attendance for those who attended without completing).\n\n- **Persistent non-sustained employment** — binary (1 = non-sustained workforce participation in 4 or 5 of the first 5 years, 0 = otherwise). This isolates the instability mechanism identified in the bivariate work.\n- **Persistent no-record status** — binary (1 = no Minnesota employment record in 4 or 5 of the first 5 years, 0 = otherwise). This isolates the disappearance-from-the-system mechanism identified in the bivariate work.\n\nEach outcome is modeled separately, in its own specification, rather than as levels of a single combined variable. This mirrors the logic of the bivariate analysis: combining the two mechanisms into one model would risk re-obscuring the distinction this analysis is specifically designed to confirm.\n\n### Independent Variables\n\nThe following indepdent variables were confirmed associated to our dependent variables in the bivariate analysis. These will all be considered for use in the modeling.\n\n**Demographics**\n\n- `Gender`\n- `RaceEthnicity`\n- `economic.status`\n- `SpecialEdStatus`\n- `english.learner`\n\n**High school characteristics**\n\n- `edr`\n- `avg.unemp.rate`\n- `avg.wages.pct.state`\n\n**High school accomplishments**\n\n- `pseo.participant`\n- `ap.exam`\n- `took.ACT`\n- `ACTCompositeScore` (recoded to 0 for non-test-takers, entered alongside `took.ACT`, per the missing-indicator approach established earlier in this project)\n- `cte.achievement`\n- `total.cte.courses.taken`\n- `sat.taken`\n\n**Postsecondary variable**\n\n- `attended.ps` — included specifically because it was the single strongest predictor of overall disconnection in the bivariate analysis, and it is the one variable found to meaningfully affect both disconnection mechanisms rather than only one.\n\n### Modeling Approach\n\nEach outcome (persistent non-sustained status, persistent no-record status) is modeled using a staged block-entry sequence, consistent with the modeling structure used throughout this project's other multivariate confirmation analyses. Predictors are introduced in four stages to make attenuation of any individual variable's effect visible and attributable to a specific block, rather than only observable in a single final specification.\n\n**Model 1: Demographics**\n\n- Demographics: `Gender`, `RaceEthnicity`, `economic.status`, `SpecialEdStatus`, `english.learner`, `non.english.home`\n\n**Model 2: add High School Characteristics**\n\n- High school characteristics: `edr`, `avg.unemp.rate`, `avg.wages.pct.state`\n\n**Model 3: Add High School Accomplishments**\n\n- Adds: `pseo.participant`, `took.ACT`, `ACTCompositeScore.filled`, `ap.exam`, `cte.achievement`, `total.cte.courses.taken`, `sat.taken`\n\n**Model 4: Add Postsecondary Attempt**\n\n- Adds: `attended.ps`\n\nEach model is compared to the prior one using a likelihood ratio test to confirm it adds significant explanatory power, with AIC tracked across the sequence to summarize overall model improvement. This staged structure is applied identically to both outcomes, allowing direct comparison of how each mechanism's predictors evolve across the same three blocks.\n\n### Evaluation Criteria\n\nResults will be reported using odds ratios, 95% confidence intervals, and statistical significance levels. Interpretation will focus specifically on whether the demographic variables identified as mechanism-specific in the bivariate analysis (Special Education and English learner status for no-record persistence; Economic status and Gender for non-sustained persistence; racial/ethnic groups for whichever mechanism their bivariate disparity was concentrated in) remain significant, attenuate, or reverse once the full variable set is included. Findings will be described as associations holding other included variables constant. No causal claims will be made.\n\n<br>\n\n# Prepping the data\n\nThe modeling dataset begins from the merged file containing both the disconnection-persistence categories (established in the bivariate analysis) and the full set of demographic, high school, and postsecondary variables used throughout this project. Three preparation steps are applied before modeling.\n\n**Cohort restriction.** The sample is restricted to graduates from 2011 onward (`grad.year > 2010`). This mirrors the cohort restriction applied throughout this project's other analyses of non-college graduates: PSEO participation was not reliably tracked prior to 2011 (missingness runs 92-100% in the 2008-2010 cohorts, dropping to near-zero by 2014), and including those cohorts would risk misclassifying untracked PSEO participants as confirmed non-participants.\n\n**Reference level assignment.** Categorical variables are releveled to match the reference categories used consistently throughout this project (male, White, non-economically-disadvantaged, non-Special-Education, non-English-learner, EDR 5 - North Central, no CTE involvement, non-participant/non-test-taker for the binary accomplishment variables). This keeps odds ratios in this analysis directly comparable in direction and interpretation to every other model built in this project.\n\n**Missing-indicator recodes for two variables with structural or correlated missingness:**\n\n- **ACT composite score.** Students who did not take the ACT have no composite score by definition — confirmed here to be a fully deterministic relationship with `took.ACT` (zero mismatches between the two). `ACTCompositeScore` is recoded to 0 for non-test-takers and entered into the model alongside `took.ACT`, so that `took.ACT` absorbs the effect of test participation itself while the filled score captures the achievement gradient among test-takers only.\n\n**Dependent variable construction.** The two outcomes tested in this analysis are built directly from the bivariate persistence categories, collapsed to binary indicators:\n\n- `persistent.non_sustained` — 1 if the graduate was non-sustained in 4 or 5 of their first 5 years post-education-exit, 0 otherwise.\n\n- `persistent.no_record` — 1 if the graduate had no Minnesota employment record in 4 or 5 of those years, 0 otherwise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_ivs <- c(\n  # Demographics\n  \"Gender\",\n  \"RaceEthnicity\",\n  \"economic.status\",\n  \"SpecialEdStatus\",\n  \"english.learner\",\n  \"non.english.home\",\n  \n  # High school characteristics\n  \"edr\",\n  \"avg.unemp.rate\",\n  \"avg.wages.pct.state\",\n  \n  # High school accomplishments\n  \"pseo.participant\",\n  \"took.ACT\",\n  \"ACTCompositeScore\",\n  \"ap.exam\",\n  \"sat.taken\",\n  \"cte.achievement\",\n  \"total.cte.courses.taken\",\n  \n  # Postsecondary\n  \"attended.ps\"\n)\nmaster.disc <- master.original %>%\n  filter(grad.year > 2010,\n         !is.na(pseo.participant),\n         grad.year < 2020,\n         RaceEthnicity != \"Unknown\") %>%\n  select(PersonID, all_of(final_ivs), non_sustained.cat, no_record.cat) %>%\n  mutate(\n    Gender              = fct_relevel(Gender, \"M\"),\n    RaceEthnicity       = fct_relevel(RaceEthnicity, \"White\"),\n    economic.status = as_factor(economic.status),\n    economic.status     = fct_relevel(economic.status, \"0\"),\n    SpecialEdStatus = as_factor(SpecialEdStatus),\n    SpecialEdStatus     = fct_relevel(SpecialEdStatus, \"0\"),\n    english.learner = as_factor(english.learner),\n    english.learner     = fct_relevel(english.learner, \"0\"),\n    non.english.home = as_factor(non.english.home),\n    non.english.home = fct_relevel(non.english.home, \"0\"),\n    edr = fct_relevel(edr, \"EDR 5 - North Central\"),\n    pseo.participant = as_factor(pseo.participant),\n    pseo.participant    = fct_relevel(pseo.participant, \"0\"),\n    took.ACT            = fct_relevel(took.ACT, \"No\"),\n    ap.exam = as_factor(ap.exam),\n    ap.exam             = fct_relevel(ap.exam, \"0\"),\n    sat.taken = as_factor(sat.taken),\n    sat.taken = fct_relevel(sat.taken, \"0\"),\n    cte.achievement     = fct_relevel(cte.achievement, \"No CTE\"),\n    attended.ps         = fct_relevel(attended.ps, \"No\"),\n    ACTCompositeScore.filled = ifelse(is.na(ACTCompositeScore), 0, ACTCompositeScore),\n    persistent.non_sustained = ifelse(non_sustained.cat == \"Persistently non-sustained\", 1, 0),\n    persistent.no_record     = ifelse(no_record.cat == \"Persistently no-record\", 1, 0)\n  ) \n\nnrow(master.disc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(names(master.disc))\n```\n\n::: {.cell-output-display}\n\n\n|x                        |\n|:------------------------|\n|PersonID                 |\n|Gender                   |\n|RaceEthnicity            |\n|economic.status          |\n|SpecialEdStatus          |\n|english.learner          |\n|non.english.home         |\n|edr                      |\n|avg.unemp.rate           |\n|avg.wages.pct.state      |\n|pseo.participant         |\n|took.ACT                 |\n|ACTCompositeScore        |\n|ap.exam                  |\n|sat.taken                |\n|cte.achievement          |\n|total.cte.courses.taken  |\n|attended.ps              |\n|non_sustained.cat        |\n|no_record.cat            |\n|ACTCompositeScore.filled |\n|persistent.non_sustained |\n|persistent.no_record     |\n\n\n:::\n\n```{.r .cell-code}\nkable(head(master.disc))\n```\n\n::: {.cell-output-display}\n\n\n| PersonID|Gender |RaceEthnicity |economic.status |SpecialEdStatus |english.learner |non.english.home |edr                  | avg.unemp.rate| avg.wages.pct.state|pseo.participant |took.ACT | ACTCompositeScore|ap.exam |sat.taken |cte.achievement               | total.cte.courses.taken|attended.ps |non_sustained.cat            |no_record.cat     | ACTCompositeScore.filled| persistent.non_sustained| persistent.no_record|\n|--------:|:------|:-------------|:---------------|:---------------|:---------------|:----------------|:--------------------|--------------:|-------------------:|:----------------|:--------|-----------------:|:-------|:---------|:-----------------------------|-----------------------:|:-----------|:----------------------------|:-----------------|------------------------:|------------------------:|--------------------:|\n| 10870895|M      |Hispanic      |1               |1               |1               |1                |EDR 7W- Central      |       4.300000|           0.8475591|0                |No       |                NA|0       |0         |CTE Participant               |                      14|No          |Intermittently non-sustained |Broadly no-record |                        0|                        0|                    0|\n|  2014911|F      |White         |0               |0               |0               |0                |EDR 7W- Central      |       3.400000|           0.8902345|0                |Yes      |                19|0       |0         |CTE Participant               |                       2|No          |Never non-sustained          |Never no-record   |                       19|                        0|                    0|\n|  2402400|M      |Asian/PI      |0               |0               |0               |0                |EDR 7W- Central      |       7.900000|           0.8803669|0                |No       |                NA|0       |0         |CTE Concentrator or Completor |                      11|Yes         |Never non-sustained          |Never no-record   |                        0|                        0|                    0|\n|  7426938|F      |White         |0               |0               |0               |0                |EDR 7W- Central      |       3.666667|           0.8871667|1                |Yes      |                26|1       |0         |No CTE                        |                       0|No          |Intermittently non-sustained |Never no-record   |                       26|                        0|                    0|\n|  8972257|M      |White         |0               |0               |0               |0                |EDR 7E- East Central |       9.700000|           0.7326147|0                |Yes      |                15|0       |0         |CTE Concentrator or Completor |                       4|Yes         |Never non-sustained          |Never no-record   |                       15|                        0|                    0|\n|  2271075|M      |White         |1               |0               |0               |0                |EDR 7E- East Central |       6.166667|           0.6650119|0                |Yes      |                13|0       |0         |CTE Concentrator or Completor |                       2|No          |Broadly non-sustained        |Never no-record   |                       13|                        0|                    0|\n\n\n:::\n:::\n\n\n<br>\n\n# Modeling: persistent non-sustained WF\n\n## Model 1: Demographics\n\nSample: N = 27,669 \\| AIC: 22,484.98 \\| Pseudo R² (McFadden-style): 0.0177\n\nAs expected for a demographics-only baseline, model fit is minimal — this is the reference point for tracking whether the mechanism-specific bivariate findings hold once every demographic variable is considered simultaneously.\n\n**Coefficient Interpretation**\n\n*Gender and Economic Status — the two variables the bivariate work flagged as \"genuinely about job instability\"*\n\n- Female non-completers show **significantly higher odds** of persistent non-sustained employment (OR = 1.57, 95% CI 1.46–1.68) — this directly confirms the bivariate finding that Gender's disconnection disadvantage is concentrated in job instability specifically, now holding up with every other demographic variable controlled.\n- Economically disadvantaged non-completers also show **significantly higher odds** (OR = 1.21, CI 1.13–1.30) — likewise confirming the bivariate finding for this variable.\n\n*English Learner and Non-English Home — the mechanism split resolves cleanly here*\n\n- **English learner status shows essentially no relationship at all** (OR = 1.00, CI 0.88–1.13, p = 0.982) — this is about as clean a null result as this analysis could produce, and it directly confirms the bivariate finding that EL's overall disconnection disadvantage has nothing to do with non-sustained employment specifically.\n- **Non-English home is significant and *protective*** (OR = 0.65, CI 0.52–0.80) — non-completers from non-English-speaking homes show notably *lower* odds of persistent non-sustained employment. This is a strong, direct confirmation of the bivariate finding that this group showed *better*-than-average non-sustained outcomes despite a dramatically *worse* no-record outcome. Seeing this protective direction hold up in a fully controlled multivariate model, rather than just a simple cross-tab, meaningfully strengthens confidence in the mechanism-split interpretation from the bivariate stage.\n\n*Race/Ethnicity — partial confirmation*\n\n- **Black shows a large, highly significant disadvantage** (OR = 1.86, CI 1.58–2.19) — the strongest race/ethnicity coefficient in this model, directly confirming the bivariate finding that Black graduates show real, elevated non-sustained-employment risk (one of the two groups, alongside American Indian, whose disadvantage operates through both mechanisms rather than concentrating in no-record status alone).\n- American Indian shows a positive but only **borderline-significant** effect (OR = 1.20, CI 0.98–1.47, p = 0.069) — directionally consistent with the bivariate finding, though weaker than expected once other demographics are controlled simultaneously.\n- Asian/Pacific Islander (OR = 0.88, CI 0.64–1.19, p = 0.434) and Hispanic (OR = 1.08, CI 0.86–1.34, p = 0.510) are **both not significant**. The point estimate for Asian/Pacific Islander trends in the \"protective\" direction the bivariate analysis identified (this group showed *better*-than-White non-sustained outcomes), but doesn't reach significance here — worth watching whether this sharpens once HS context and accomplishments are added in later blocks, since the bivariate racial split was one of the more striking findings in the earlier work.\n\n**Multicollinearity Check**\n\nLooks good — all GVIF\\^(1/(2·Df)) values are low, with the highest being non-English home (1.27) and English learner (1.27), both well under the \\~2.0–2.5 concern threshold. As expected given their conceptual overlap, these two show the highest (though still low) correlation of any pair in the model.\n\n**Substantive Pattern**\n\nThis baseline model delivers a strong first confirmation of the bivariate mechanism-split hypothesis this analysis exists to test. Four of the five demographic variables behave exactly as predicted: Gender and economic status show real, significant disadvantage specifically for non-sustained employment; English learner status shows no relationship at all; and non-English home shows a significant *protective* effect, matching its bivariate direction precisely. Race/ethnicity is only partially confirmed at this stage — Black graduates show the predicted large disadvantage, but American Indian is only borderline and Asian/Pacific Islander and Hispanic don't yet reach significance, though their point estimates trend in the expected directions. This is a promising start for the confirmatory design; the real test will be whether these patterns persist once HS characteristics and accomplishments are added.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_non_sustained <- glm(\n  persistent.non_sustained ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home,\n  family = binomial,\n  data = master.disc\n)\n\nmodel1_non_sustained\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home, \n    family = binomial, data = master.disc)\n\nCoefficients:\n          (Intercept)                GenderF        RaceEthnicityAI  \n            -2.198433               0.449771               0.185974  \nRaceEthnicityAsian/PI     RaceEthnicityBlack  RaceEthnicityHispanic  \n            -0.124216               0.620136               0.073704  \n     economic.status1       SpecialEdStatus1       english.learner1  \n             0.190730               0.445085              -0.001395  \n    non.english.home1  \n            -0.436744  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27659 Residual\nNull Deviance:\t    22870 \nResidual Deviance: 22460 \tAIC: 22480\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model1_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home, \n    family = binomial, data = master.disc)\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -2.198433   0.031301 -70.235  < 2e-16 ***\nGenderF                0.449771   0.034863  12.901  < 2e-16 ***\nRaceEthnicityAI        0.185974   0.102351   1.817   0.0692 .  \nRaceEthnicityAsian/PI -0.124216   0.158582  -0.783   0.4335    \nRaceEthnicityBlack     0.620136   0.083806   7.400 1.36e-13 ***\nRaceEthnicityHispanic  0.073704   0.111833   0.659   0.5099    \neconomic.status1       0.190730   0.035883   5.315 1.06e-07 ***\nSpecialEdStatus1       0.445085   0.045527   9.776  < 2e-16 ***\nenglish.learner1      -0.001395   0.062986  -0.022   0.9823    \nnon.english.home1     -0.436744   0.109442  -3.991 6.59e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 22871  on 27668  degrees of freedom\nResidual deviance: 22465  on 27659  degrees of freedom\nAIC: 22485\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model1_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model1_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22484.98\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model1_non_sustained), confint(model1_non_sustained)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             OR     2.5 %    97.5 %\n(Intercept)           0.1109769 0.1043353 0.1179565\nGenderF               1.5679535 1.4643985 1.6788602\nRaceEthnicityAI       1.2043914 0.9817124 1.4668015\nRaceEthnicityAsian/PI 0.8831888 0.6397731 1.1928903\nRaceEthnicityBlack    1.8591811 1.5750336 2.1878522\nRaceEthnicityHispanic 1.0764886 0.8611020 1.3353206\neconomic.status1      1.2101325 1.1279329 1.2983008\nSpecialEdStatus1      1.5606234 1.4268217 1.7056246\nenglish.learner1      0.9986057 0.8823427 1.1294881\nnon.english.home1     0.6461369 0.5201831 0.7989799\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model1_non_sustained$deviance / model1_non_sustained$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01774911\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model1_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     GVIF Df GVIF^(1/(2*Df))\nGender           1.022261  1        1.011069\nRaceEthnicity    1.454714  4        1.047966\neconomic.status  1.084280  1        1.041288\nSpecialEdStatus  1.422106  1        1.192521\nenglish.learner  1.609141  1        1.268519\nnon.english.home 1.615907  1        1.271183\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Model 2: Add High School Characteristics\n\nSample: N = 27,669 (unchanged from Model 1) \\| AIC: 22,469.78 (down from 22,484.98) \\| Pseudo R² (McFadden-style): 0.0188 (up from 0.0177)\n\nLikelihood ratio test vs. Model 1: Δdeviance = 23.20 on 4 df, p \\< 0.001 — this block adds significant explanatory power, though modestly compared to the demographics block itself.\n\n**Coefficient Interpretation**\n\n*Gender, Economic Status, English Learner, and Non-English Home — all confirm Model 1*\n\n- Gender (OR = 1.57) and economic status (OR = 1.22) both remain essentially unchanged and highly significant, continuing to confirm the bivariate finding that these two variables are genuinely about job instability.\n- English learner remains **essentially exactly null** (OR = 0.99, p = 0.840), confirming Model 1 with a slightly larger sample of controls.\n- Non-English home remains significant and **protective** (OR = 0.66), essentially unchanged from Model 1 (0.65) — this stability across two blocks strengthens confidence that this is a real, robust finding rather than a baseline artifact.\n\n*Race/Ethnicity*\n\n- **Black remains the largest and most significant race/ethnicity coefficient** (OR = 1.85, p \\< 0.001), essentially unchanged from Model 1 (1.86) — HS characteristics don't explain this disparity at all.\n- **American Indian is now significant** (OR = 1.24, p = 0.039), crossing the threshold from Model 1's borderline result (p = 0.069) — consistent with the bivariate prediction that this group's disadvantage operates through the non-sustained mechanism.\n- Asian/Pacific Islander remains **not significant** (OR = 0.88, p = 0.405), continuing to trend in the bivariate-predicted protective direction without reaching significance.\n- Hispanic remains **not significant** (OR = 1.07, p = 0.556).\n\n*Regional and Local Labor Market Context*\n\n- **EDR 7E is significant and positive** (OR = 1.25, p \\< 0.001) — non-completers from EDR 7E high schools show higher odds of persistent non-sustained employment relative to EDR 5. This is a new finding not previously tested in the bivariate stage for this specific mechanism.\n- EDR 7W is **not significant** (OR = 1.08, p = 0.178).\n- Neither `avg.wages.pct.state` (OR = 0.92, p = 0.849) nor `avg.unemp.rate` (OR = 0.98, p = 0.144) is significant — consistent with the earlier bivariate finding that local labor-market conditions showed only a weak, threshold-like relationship with non-sustained employment specifically (as opposed to their much stronger relationship with no-record status).\n\n**Multicollinearity Check**\n\nLooks good — all GVIF\\^(1/(2·Df)) values are low, with the highest being `avg.wages.pct.state` at 1.45 and `english.learner`/`non.english.home` both around 1.28 (expected given their conceptual overlap). All well under the \\~2.0–2.5 concern threshold.\n\n**Substantive Pattern**\n\nThis block adds one genuinely new finding (EDR 7E's positive association with non-sustained employment) while otherwise reinforcing every pattern established in Model 1. The mechanism-split hypothesis continues to hold up well: Gender, economic status, English learner, and non-English home all behave exactly as the bivariate analysis predicted, and American Indian's disadvantage has now crossed into clear significance. The one remaining open question is whether Asian/Pacific Islander and Hispanic will show any movement once accomplishments are added in Model 3, or whether they'll remain null throughout this non-sustained-specific sequence — which would itself be a meaningful confirmatory finding, since the bivariate work suggested these two groups' disadvantage was concentrated almost entirely in the no-record mechanism instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2_non_sustained <- glm(\n  persistent.non_sustained ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home +\n    edr +\n    avg.wages.pct.state +\n    avg.unemp.rate, \n  family = binomial,\n  data = master.disc\n)\n\nmodel2_non_sustained\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate, family = binomial, \n    data = master.disc)\n\nCoefficients:\n            (Intercept)                  GenderF          RaceEthnicityAI  \n               -2.14280                  0.45108                  0.21404  \n  RaceEthnicityAsian/PI       RaceEthnicityBlack    RaceEthnicityHispanic  \n               -0.13233                  0.61378                  0.06581  \n       economic.status1         SpecialEdStatus1         english.learner1  \n                0.19911                  0.45274                 -0.01283  \n      non.english.home1  edrEDR 7E- East Central       edrEDR 7W- Central  \n               -0.41878                  0.22434                  0.07768  \n    avg.wages.pct.state           avg.unemp.rate  \n               -0.07990                 -0.01594  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27655 Residual\nNull Deviance:\t    22870 \nResidual Deviance: 22440 \tAIC: 22470\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model2_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model2_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22469.78\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model2_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate, family = binomial, \n    data = master.disc)\n\nCoefficients:\n                        Estimate Std. Error z value Pr(>|z|)    \n(Intercept)             -2.14280    0.35151  -6.096 1.09e-09 ***\nGenderF                  0.45108    0.03489  12.930  < 2e-16 ***\nRaceEthnicityAI          0.21404    0.10345   2.069 0.038548 *  \nRaceEthnicityAsian/PI   -0.13233    0.15877  -0.833 0.404591    \nRaceEthnicityBlack       0.61378    0.08460   7.255 4.01e-13 ***\nRaceEthnicityHispanic    0.06581    0.11190   0.588 0.556468    \neconomic.status1         0.19911    0.03658   5.443 5.24e-08 ***\nSpecialEdStatus1         0.45274    0.04564   9.921  < 2e-16 ***\nenglish.learner1        -0.01283    0.06346  -0.202 0.839757    \nnon.english.home1       -0.41878    0.10990  -3.810 0.000139 ***\nedrEDR 7E- East Central  0.22434    0.05009   4.479 7.50e-06 ***\nedrEDR 7W- Central       0.07768    0.05770   1.346 0.178240    \navg.wages.pct.state     -0.07990    0.41967  -0.190 0.849003    \navg.unemp.rate          -0.01594    0.01090  -1.462 0.143861    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 22871  on 27668  degrees of freedom\nResidual deviance: 22442  on 27655  degrees of freedom\nAIC: 22470\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model2_non_sustained), confint(model2_non_sustained)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               OR      2.5 %    97.5 %\n(Intercept)             0.1173264 0.05884514 0.2334322\nGenderF                 1.5700103 1.46625253 1.6811399\nRaceEthnicityAI         1.2386661 1.00756919 1.5119270\nRaceEthnicityAsian/PI   0.8760550 0.63438429 1.1837092\nRaceEthnicityBlack      1.8474042 1.56264924 2.1773888\nRaceEthnicityHispanic   1.0680224 0.85422271 1.3250111\neconomic.status1        1.2203212 1.13587819 1.3110263\nSpecialEdStatus1        1.5726192 1.43748534 1.7191129\nenglish.learner1        0.9872505 0.87150772 1.1176860\nnon.english.home1       0.6578458 0.52913062 0.8141964\nedrEDR 7E- East Central 1.2514952 1.13463760 1.3808266\nedrEDR 7W- Central      1.0807757 0.96538697 1.2104387\navg.wages.pct.state     0.9232073 0.40589503 2.1033939\navg.unemp.rate          0.9841888 0.96333691 1.0054102\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(model1_non_sustained, model2_non_sustained, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home\nModel 2: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1     27659      22465                          \n2     27655      22442  4   23.197 0.0001157 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model2_non_sustained$deviance / model2_non_sustained$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01876336\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model2_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        GVIF Df GVIF^(1/(2*Df))\nGender              1.022702  1        1.011287\nRaceEthnicity       1.513199  4        1.053142\neconomic.status     1.125846  1        1.061059\nSpecialEdStatus     1.427477  1        1.194771\nenglish.learner     1.631964  1        1.277483\nnon.english.home    1.628572  1        1.276155\nedr                 2.155919  2        1.211736\navg.wages.pct.state 2.094442  1        1.447219\navg.unemp.rate      1.382436  1        1.175770\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Model 3: Add High School Accomplishments\n\nSample: N = 27,669 (unchanged from Models 1–2) \\| AIC: 22,422.82 (down from 22,469.78) \\| Pseudo R² (McFadden-style): 0.0215 (up from 0.0188)\n\nLikelihood ratio test vs. Model 2: Δdeviance = 62.96 on 8 df, p \\< 2.2e-10 — significant, and the largest single-block improvement in this sequence so far.\n\n**Coefficient Interpretation** (recall: OR \\> 1 = higher odds of the *bad* outcome, persistent non-sustained employment)\n\n*Gender, Economic Status, English Learner, and Non-English Home — all remain stable*\n\n- Gender (OR = 1.55) and economic status (OR = 1.23) both remain essentially unchanged and highly significant.\n- English learner remains **exactly null** (OR = 1.00, p = 0.962).\n- Non-English home remains significant and protective (OR = 0.65), essentially unchanged across all three models now — this is a genuinely robust, stable finding.\n\n*Race/Ethnicity*\n\n- **Black remains essentially unchanged and highly significant** (OR = 1.84, vs. 1.85 in Model 2) — accomplishments explain none of this disparity, consistent with the pattern established throughout this entire project.\n- American Indian **slips back to borderline** (OR = 1.21, p = 0.067, vs. p = 0.039 in Model 2) — some of this coefficient's Model 2 significance appears to run through the accomplishment variables now added.\n- Asian/Pacific Islander (OR = 0.86, p = 0.353) and Hispanic (OR = 1.04, p = 0.697) both remain **not significant** — continuing to confirm the bivariate prediction that these two groups' disconnection disadvantage is concentrated in the no-record mechanism, not non-sustained employment.\n\n*Regional and Local Labor Market Context*\n\n- **EDR 7E strengthens further** (OR = 1.29, up from 1.25 in Model 2) — non-completers from EDR 7E high schools continue to show meaningfully higher odds of persistent non-sustained employment.\n- EDR 7W remains not significant.\n- `avg.wages.pct.state` remains not significant (OR = 0.89, p = 0.779).\n- **`avg.unemp.rate` becomes significant here** (OR = 0.97, p = 0.006) — and notably in the *protective* direction: higher local unemployment is associated with *lower* odds of persistent non-sustained employment. This is worth connecting directly back to the bivariate ANOVA finding for this variable, which showed a genuinely non-monotonic relationship with `non_sustained.cat` — Intermittent and Broadly non-sustained individuals lived in higher-unemployment areas than the \"Never\" group, but Persistently non-sustained individuals were *not* significantly different from \"Never.\" This multivariate result is consistent with that earlier finding: once other variables are controlled, higher local unemployment doesn't predict the most severe, persistent form of non-sustained employment — if anything, it's mildly protective against it.\n\n*High School Accomplishments — the ACT/CTE threshold pattern reconfirms directly*\n\n- **`took.ACT` is significant and protective** (OR = 0.61, p \\< 0.001) — simply taking the ACT is associated with substantially lower odds of persistent non-sustained employment, directly consistent with the \"took.ACT positive for good outcomes\" pattern established throughout this project.\n- **`ACTCompositeScore.filled` is significant and *harmful*** (OR = 1.02 per point, p = 0.001) — among ACT-takers specifically, a higher score is associated with *higher* odds of persistent non-sustained employment. This is the same threshold pattern (participation protective, score itself harmful) that has appeared repeatedly throughout this project, now confirmed directly in a model isolating the non-sustained mechanism specifically.\n- **Both `cte.achievement` categories are significant and protective**: Concentrator/Completer (OR = 0.85) and Participant (OR = 0.89) — confirming CTE's established role as a protective factor against workforce instability. `total.cte.courses.taken` trends the same protective direction but doesn't reach significance here (OR = 0.99, p = 0.136).\n- `pseo.participant` is **not significant** (OR = 0.93, p = 0.113) — trending protective but not reaching significance, consistent with the bivariate finding that PSEO's clearest benefit for this population is regional-employment-specific rather than about non-sustained employment broadly.\n- `ap.exam` is **borderline** (OR = 1.13, p = 0.074), trending toward *harmful* — consistent with the \"college-ambition\" pattern, though it doesn't clear significance here, matching its weak bivariate relationship with this specific mechanism.\n- `sat.taken` remains **not significant** (OR = 1.13, p = 0.542) — directly confirming the bivariate finding that SAT-taking has essentially no relationship with non-sustained employment specifically (its large bivariate disadvantage was concentrated almost entirely in no-record status).\n\n**Multicollinearity Check**\n\n`took.ACT` and `ACTCompositeScore.filled` are elevated as expected (3.71 and 3.93) given their coding design. Everything else remains comfortably under the \\~2.0–2.5 threshold, including `avg.wages.pct.state` (1.46) and `total.cte.courses.taken` (1.44). Overall, looks good.\n\n**Substantive Pattern**\n\nThis model provides strong, direct confirmation of the mechanism-split hypothesis this analysis exists to test. Every demographic prediction from the bivariate stage continues to hold: Gender, economic status, and Black graduates show real, stable disadvantage specific to non-sustained employment; English learner shows none; non-English home remains protective; and Asian/Pacific Islander and Hispanic remain null, exactly as expected if their disadvantage is concentrated in the no-record mechanism instead. The accomplishment variables reproduce the project's established \"two pathways\" pattern cleanly and directly: CTE engagement and simply taking the ACT both protect against instability, while a higher ACT score (conditional on taking it) and AP exam participation both trend toward harm — and SAT-taking, once again, shows no relationship at all, reinforcing that its dramatic bivariate disadvantage belongs entirely to the no-record mechanism this model doesn't test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3_non_sustained <- glm(\n  persistent.non_sustained ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home +\n    edr +\n    avg.wages.pct.state +\n    avg.unemp.rate +\n    pseo.participant +\n    took.ACT +\n    ACTCompositeScore.filled +\n    ap.exam +\n    sat.taken +\n    cte.achievement +\n    total.cte.courses.taken,\n  family = binomial,\n  data = master.disc\n)\n\nmodel3_non_sustained\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken, family = binomial, \n    data = master.disc)\n\nCoefficients:\n                                 (Intercept)  \n                                   -1.827348  \n                                     GenderF  \n                                    0.439017  \n                             RaceEthnicityAI  \n                                    0.190801  \n                       RaceEthnicityAsian/PI  \n                                   -0.147840  \n                          RaceEthnicityBlack  \n                                    0.607978  \n                       RaceEthnicityHispanic  \n                                    0.043553  \n                            economic.status1  \n                                    0.204979  \n                            SpecialEdStatus1  \n                                    0.441244  \n                            english.learner1  \n                                   -0.003057  \n                           non.english.home1  \n                                   -0.428303  \n                     edrEDR 7E- East Central  \n                                    0.255439  \n                          edrEDR 7W- Central  \n                                    0.038673  \n                         avg.wages.pct.state  \n                                   -0.118717  \n                              avg.unemp.rate  \n                                   -0.031220  \n                           pseo.participant1  \n                                   -0.075585  \n                                 took.ACTYes  \n                                   -0.499884  \n                    ACTCompositeScore.filled  \n                                    0.020923  \n                                    ap.exam1  \n                                    0.120829  \n                                  sat.taken1  \n                                    0.121110  \ncte.achievementCTE Concentrator or Completor  \n                                   -0.160528  \n              cte.achievementCTE Participant  \n                                   -0.114177  \n                     total.cte.courses.taken  \n                                   -0.010028  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27647 Residual\nNull Deviance:\t    22870 \nResidual Deviance: 22380 \tAIC: 22420\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model3_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model3_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22422.82\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model3_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken, family = binomial, \n    data = master.disc)\n\nCoefficients:\n                                              Estimate Std. Error z value\n(Intercept)                                  -1.827348   0.358619  -5.096\nGenderF                                       0.439017   0.035360  12.416\nRaceEthnicityAI                               0.190801   0.104090   1.833\nRaceEthnicityAsian/PI                        -0.147840   0.159081  -0.929\nRaceEthnicityBlack                            0.607978   0.085028   7.150\nRaceEthnicityHispanic                         0.043553   0.111929   0.389\neconomic.status1                              0.204979   0.037141   5.519\nSpecialEdStatus1                              0.441244   0.047552   9.279\nenglish.learner1                             -0.003057   0.063685  -0.048\nnon.english.home1                            -0.428303   0.109866  -3.898\nedrEDR 7E- East Central                       0.255439   0.050666   5.042\nedrEDR 7W- Central                            0.038673   0.058182   0.665\navg.wages.pct.state                          -0.118717   0.422981  -0.281\navg.unemp.rate                               -0.031220   0.011434  -2.730\npseo.participant1                            -0.075585   0.047703  -1.584\ntook.ACTYes                                  -0.499884   0.128739  -3.883\nACTCompositeScore.filled                      0.020923   0.006473   3.232\nap.exam1                                      0.120829   0.067566   1.788\nsat.taken1                                    0.121110   0.198456   0.610\ncte.achievementCTE Concentrator or Completor -0.160528   0.058859  -2.727\ncte.achievementCTE Participant               -0.114177   0.046460  -2.458\ntotal.cte.courses.taken                      -0.010028   0.006722  -1.492\n                                             Pr(>|z|)    \n(Intercept)                                  3.48e-07 ***\nGenderF                                       < 2e-16 ***\nRaceEthnicityAI                              0.066797 .  \nRaceEthnicityAsian/PI                        0.352714    \nRaceEthnicityBlack                           8.66e-13 ***\nRaceEthnicityHispanic                        0.697192    \neconomic.status1                             3.41e-08 ***\nSpecialEdStatus1                              < 2e-16 ***\nenglish.learner1                             0.961720    \nnon.english.home1                            9.68e-05 ***\nedrEDR 7E- East Central                      4.62e-07 ***\nedrEDR 7W- Central                           0.506249    \navg.wages.pct.state                          0.778966    \navg.unemp.rate                               0.006326 ** \npseo.participant1                            0.113082    \ntook.ACTYes                                  0.000103 ***\nACTCompositeScore.filled                     0.001228 ** \nap.exam1                                     0.073729 .  \nsat.taken1                                   0.541690    \ncte.achievementCTE Concentrator or Completor 0.006385 ** \ncte.achievementCTE Participant               0.013989 *  \ntotal.cte.courses.taken                      0.135769    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 22871  on 27668  degrees of freedom\nResidual deviance: 22379  on 27647  degrees of freedom\nAIC: 22423\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model3_non_sustained), confint(model3_non_sustained)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                    OR      2.5 %    97.5 %\n(Intercept)                                  0.1608396 0.07955623 0.3245157\nGenderF                                      1.5511818 1.44732322 1.6625189\nRaceEthnicityAI                              1.2102187 0.98323321 1.4791170\nRaceEthnicityAsian/PI                        0.8625693 0.62425925 1.1662462\nRaceEthnicityBlack                           1.8367140 1.55232789 2.1666695\nRaceEthnicityHispanic                        1.0445156 0.83538864 1.2959417\neconomic.status1                             1.2274990 1.14131560 1.3201976\nSpecialEdStatus1                             1.5546397 1.41580481 1.7059445\nenglish.learner1                             0.9969481 0.87968499 1.1291774\nnon.english.home1                            0.6516142 0.52415780 0.8064277\nedrEDR 7E- East Central                      1.2910285 1.16915401 1.4260589\nedrEDR 7W- Central                           1.0394306 0.92758744 1.1652337\navg.wages.pct.state                          0.8880592 0.38789815 2.0363998\navg.unemp.rate                               0.9692622 0.94773467 0.9911834\npseo.participant1                            0.9272009 0.84411400 1.0177003\ntook.ACTYes                                  0.6066012 0.47115019 0.7804540\nACTCompositeScore.filled                     1.0211430 1.00824896 1.0341620\nap.exam1                                     1.1284314 0.98741625 1.2869228\nsat.taken1                                   1.1287487 0.75236753 1.6420318\ncte.achievementCTE Concentrator or Completor 0.8516939 0.75873607 0.9556530\ncte.achievementCTE Participant               0.8921005 0.81440285 0.9770992\ntotal.cte.courses.taken                      0.9900221 0.97700788 1.0030981\n```\n\n\n:::\n\n```{.r .cell-code}\n# likelihood ratio test comparing Model 2 to Model 3\nanova(model1_non_sustained, model2_non_sustained, model3_non_sustained, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home\nModel 2: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate\nModel 3: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1     27659      22465                          \n2     27655      22442  4   23.197 0.0001157 ***\n3     27647      22379  8   62.959 1.221e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model3_non_sustained$deviance / model3_non_sustained$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02151614\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model3_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              GVIF Df GVIF^(1/(2*Df))\nGender                    1.048129  1        1.023782\nRaceEthnicity             1.536113  4        1.055123\neconomic.status           1.157806  1        1.076014\nSpecialEdStatus           1.545711  1        1.243266\nenglish.learner           1.638824  1        1.280165\nnon.english.home          1.626504  1        1.275345\nedr                       2.313714  2        1.233325\navg.wages.pct.state       2.131567  1        1.459989\navg.unemp.rate            1.505807  1        1.227113\npseo.participant          1.326281  1        1.151643\ntook.ACT                 13.728852  1        3.705246\nACTCompositeScore.filled 15.466358  1        3.932729\nap.exam                   1.282781  1        1.132599\nsat.taken                 1.034173  1        1.016943\ncte.achievement           1.981577  2        1.186459\ntotal.cte.courses.taken   2.079328  1        1.441987\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Model 4: Add Post-secondary\n\nSample: N = 27,669 (unchanged from Models 1–3) \\| AIC: 22,333.81 (down from 22,422.82) \\| Pseudo R² (McFadden-style): 0.0255 (up from 0.0215)\n\nLikelihood ratio test vs. Model 3: Δdeviance = 91.02 on 1 df, p \\< 2.2e-16 — `attended.ps` adds substantial explanatory power, the largest single-block improvement in this sequence.\n\n**Coefficient Interpretation** (recall: OR \\> 1 = higher odds of persistent non-sustained employment)\n\n*Gender, Economic Status, English Learner, and Non-English Home — all remain stable*\n\n- Gender (OR = 1.57) and economic status (OR = 1.21) remain essentially unchanged and highly significant.\n- English learner remains exactly null (OR = 0.99, p = 0.917).\n- Non-English home remains significant and protective (OR = 0.65), stable across all four models — this is now a fully confirmed, robust finding across the entire sequence.\n\n*Race/Ethnicity*\n\n- **Black strengthens further rather than attenuating** (OR = 1.91, up from 1.84 in Model 3) — postsecondary attendance does not explain this disparity; if anything, controlling for it reveals a slightly larger gap. This continues the now-familiar pattern across this entire project where the Black-White gap never narrows and frequently widens once additional controls are added.\n- **American Indian drops to fully non-significant** (OR = 1.18, p = 0.121) — down from Model 2's clear significance and Model 3's borderline result. Across this 4-model sequence, American Indian's relationship with persistent non-sustained employment has steadily eroded (Model 1: p = 0.069 → Model 2: p = 0.039 → Model 3: p = 0.067 → Model 4: p = 0.121), ending not significant. This is worth reporting as a genuinely unstable, inconclusive finding for this specific group and mechanism, rather than either a confirmed disadvantage or a confirmed null.\n- Asian/Pacific Islander and Hispanic remain not significant, continuing to confirm across all four models that their disconnection disadvantage is concentrated in the no-record mechanism rather than this one.\n\n*Regional and Local Labor Market Context*\n\n- EDR 7E remains significant (OR = 1.28), essentially unchanged from Model 3.\n- **`avg.unemp.rate` drops to non-significance here** (OR = 0.99, p = 0.624) — was significant and protective in Model 3 (p = 0.006). Some of that relationship appears to run through postsecondary attendance, suggesting local unemployment's earlier association with lower persistent-non-sustained risk was partly capturing where people who go on to attend postsecondary education tend to live, rather than a fully independent labor-market effect.\n- `avg.wages.pct.state` remains not significant.\n\n*High School Accomplishments*\n\n- `took.ACT` (OR = 0.62), `ACTCompositeScore.filled` (OR = 1.02 per point), and both `cte.achievement` categories (OR = 0.85 and 0.90) all remain essentially stable and significant, continuing to confirm the established two-pathway pattern.\n- `ap.exam` is now **borderline** (OR = 1.14, p = 0.051) — just short of significance, continuing its consistent trend toward the \"harmful\" direction across every model in this sequence without ever quite crossing the threshold.\n- `sat.taken` and `pseo.participant` remain not significant, unchanged from Model 3.\n- `total.cte.courses.taken` remains not significant (OR = 0.99, p = 0.162).\n\n*Postsecondary Attendance*\n\n- **Having attended some postsecondary education is significant and strongly protective** (OR = 0.67, CI 0.61–0.73) — non-completers who attended some postsecondary program show meaningfully lower odds of persistent non-sustained employment. This directly confirms, in a fully controlled multivariate model, the bivariate finding that `attended.ps` was the strongest predictor of overall disconnection, with a genuine, independent, non-sustained-specific component to its benefit (alongside its no-record-specific component, to be tested in the next sequence).\n\n**Multicollinearity Check**\n\n`took.ACT` and `ACTCompositeScore.filled` remain elevated as expected (3.69 and 3.92). `attended.ps` itself is low (1.07). Everything else remains comfortably under the \\~2.0–2.5 threshold.\n\n**Substantive Pattern**\n\nThis completes the planned 4-model sequence for persistent non-sustained employment, and the confirmatory design has succeeded on nearly every count the bivariate analysis predicted. Gender, economic status, and Black graduates show real, stable, non-attenuating disadvantage specific to this mechanism; English learner shows none; non-English home is protective, exactly as the bivariate work found; and Asian/Pacific Islander and Hispanic remain null throughout, consistent with their disadvantage being concentrated in the no-record mechanism instead. The one prediction that didn't hold up cleanly is American Indian, whose significance eroded steadily across the four blocks to a final null result — worth flagging as a genuinely inconclusive finding rather than forcing it into either the \"confirmed\" or \"disconfirmed\" bucket. The accomplishment variables reproduce the project's established two-pathway story exactly, and `attended.ps` closes the sequence as a strong, independent protective factor, setting up a direct point of comparison against its role in the persistent no-record model to come.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4_non_sustained <- glm(\n  persistent.non_sustained ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home +\n    edr +\n    avg.wages.pct.state +\n    avg.unemp.rate +\n    pseo.participant +\n    took.ACT +\n    ACTCompositeScore.filled +\n    ap.exam +\n    sat.taken +\n    cte.achievement +\n    total.cte.courses.taken +\n    attended.ps,\n  family = binomial,\n  data = master.disc\n)\n\nmodel4_non_sustained\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken + attended.ps, \n    family = binomial, data = master.disc)\n\nCoefficients:\n                                 (Intercept)  \n                                   -2.067694  \n                                     GenderF  \n                                    0.450319  \n                             RaceEthnicityAI  \n                                    0.161755  \n                       RaceEthnicityAsian/PI  \n                                   -0.151904  \n                          RaceEthnicityBlack  \n                                    0.649441  \n                       RaceEthnicityHispanic  \n                                    0.044776  \n                            economic.status1  \n                                    0.191157  \n                            SpecialEdStatus1  \n                                    0.415684  \n                            english.learner1  \n                                   -0.006646  \n                           non.english.home1  \n                                   -0.435572  \n                     edrEDR 7E- East Central  \n                                    0.244618  \n                          edrEDR 7W- Central  \n                                    0.058256  \n                         avg.wages.pct.state  \n                                    0.065134  \n                              avg.unemp.rate  \n                                   -0.005746  \n                           pseo.participant1  \n                                   -0.066216  \n                                 took.ACTYes  \n                                   -0.480249  \n                    ACTCompositeScore.filled  \n                                    0.024385  \n                                    ap.exam1  \n                                    0.132548  \n                                  sat.taken1  \n                                    0.114733  \ncte.achievementCTE Concentrator or Completor  \n                                   -0.162082  \n              cte.achievementCTE Participant  \n                                   -0.103483  \n                     total.cte.courses.taken  \n                                   -0.009400  \n                              attended.psYes  \n                                   -0.402803  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27646 Residual\nNull Deviance:\t    22870 \nResidual Deviance: 22290 \tAIC: 22330\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model4_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model4_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22333.81\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model4_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.non_sustained ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken + attended.ps, \n    family = binomial, data = master.disc)\n\nCoefficients:\n                                              Estimate Std. Error z value\n(Intercept)                                  -2.067694   0.360324  -5.738\nGenderF                                       0.450319   0.035456  12.701\nRaceEthnicityAI                               0.161755   0.104313   1.551\nRaceEthnicityAsian/PI                        -0.151904   0.159247  -0.954\nRaceEthnicityBlack                            0.649441   0.085210   7.622\nRaceEthnicityHispanic                         0.044776   0.112076   0.400\neconomic.status1                              0.191157   0.037225   5.135\nSpecialEdStatus1                              0.415684   0.047680   8.718\nenglish.learner1                             -0.006646   0.063711  -0.104\nnon.english.home1                            -0.435572   0.109665  -3.972\nedrEDR 7E- East Central                       0.244618   0.050767   4.818\nedrEDR 7W- Central                            0.058256   0.058345   0.998\navg.wages.pct.state                           0.065134   0.424287   0.154\navg.unemp.rate                               -0.005746   0.011734  -0.490\npseo.participant1                            -0.066216   0.047997  -1.380\ntook.ACTYes                                  -0.480249   0.128310  -3.743\nACTCompositeScore.filled                      0.024385   0.006468   3.770\nap.exam1                                      0.132548   0.068040   1.948\nsat.taken1                                    0.114733   0.199533   0.575\ncte.achievementCTE Concentrator or Completor -0.162082   0.058881  -2.753\ncte.achievementCTE Participant               -0.103483   0.046545  -2.223\ntotal.cte.courses.taken                      -0.009400   0.006719  -1.399\nattended.psYes                               -0.402803   0.043028  -9.361\n                                             Pr(>|z|)    \n(Intercept)                                  9.56e-09 ***\nGenderF                                       < 2e-16 ***\nRaceEthnicityAI                              0.120983    \nRaceEthnicityAsian/PI                        0.340137    \nRaceEthnicityBlack                           2.50e-14 ***\nRaceEthnicityHispanic                        0.689511    \neconomic.status1                             2.82e-07 ***\nSpecialEdStatus1                              < 2e-16 ***\nenglish.learner1                             0.916924    \nnon.english.home1                            7.13e-05 ***\nedrEDR 7E- East Central                      1.45e-06 ***\nedrEDR 7W- Central                           0.318049    \navg.wages.pct.state                          0.877994    \navg.unemp.rate                               0.624326    \npseo.participant1                            0.167711    \ntook.ACTYes                                  0.000182 ***\nACTCompositeScore.filled                     0.000163 ***\nap.exam1                                     0.051405 .  \nsat.taken1                                   0.565287    \ncte.achievementCTE Concentrator or Completor 0.005911 ** \ncte.achievementCTE Participant               0.026196 *  \ntotal.cte.courses.taken                      0.161857    \nattended.psYes                                < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 22871  on 27668  degrees of freedom\nResidual deviance: 22288  on 27646  degrees of freedom\nAIC: 22334\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model4_non_sustained), confint(model4_non_sustained)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                    OR      2.5 %    97.5 %\n(Intercept)                                  0.1264771 0.06234782 0.2560317\nGenderF                                      1.5688129 1.46349950 1.6817365\nRaceEthnicityAI                              1.1755717 0.95467327 1.4374120\nRaceEthnicityAsian/PI                        0.8590704 0.62153667 1.1619427\nRaceEthnicityBlack                           1.9144706 1.61750173 2.2592525\nRaceEthnicityHispanic                        1.0457940 0.83618335 1.2979290\neconomic.status1                             1.2106495 1.12546031 1.3022921\nSpecialEdStatus1                             1.5154075 1.37972552 1.6633130\nenglish.learner1                             0.9933764 0.87649095 1.1251930\nnon.english.home1                            0.6468947 0.52055983 0.8002674\nedrEDR 7E- East Central                      1.2771330 1.15633904 1.4109883\nedrEDR 7W- Central                           1.0599865 0.94562980 1.1886619\navg.wages.pct.state                          1.0673016 0.46499909 2.4537550\navg.unemp.rate                               0.9942701 0.97162007 1.0173587\npseo.participant1                            0.9359285 0.85156661 1.0278731\ntook.ACTYes                                  0.6186291 0.48089248 0.7952603\nACTCompositeScore.filled                     1.0246843 1.01175542 1.0377398\nap.exam1                                     1.1417343 0.99813063 1.3033132\nsat.taken1                                   1.1215738 0.74609789 1.6352228\ncte.achievementCTE Concentrator or Completor 0.8503714 0.75752464 0.9542157\ncte.achievementCTE Participant               0.9016917 0.82302132 0.9877721\ntotal.cte.courses.taken                      0.9906445 0.97762764 1.0037233\nattended.psYes                               0.6684436 0.61415192 0.7270075\n```\n\n\n:::\n\n```{.r .cell-code}\n# likelihood ratio test comparing Model 2 to Model 3\nanova(model1_non_sustained, model2_non_sustained, model3_non_sustained, model4_non_sustained, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home\nModel 2: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate\nModel 3: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken\nModel 4: persistent.non_sustained ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken + attended.ps\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1     27659      22465                          \n2     27655      22442  4   23.197 0.0001157 ***\n3     27647      22379  8   62.959 1.221e-10 ***\n4     27646      22288  1   91.016 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model4_non_sustained$deviance / model4_non_sustained$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02549568\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model4_non_sustained)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              GVIF Df GVIF^(1/(2*Df))\nGender                    1.050283  1        1.024833\nRaceEthnicity             1.537843  4        1.055271\neconomic.status           1.159244  1        1.076682\nSpecialEdStatus           1.549892  1        1.244947\nenglish.learner           1.636182  1        1.279133\nnon.english.home          1.616744  1        1.271512\nedr                       2.329569  2        1.235432\navg.wages.pct.state       2.142359  1        1.463680\navg.unemp.rate            1.597029  1        1.263736\npseo.participant          1.336856  1        1.156225\ntook.ACT                 13.588348  1        3.686238\nACTCompositeScore.filled 15.404612  1        3.924871\nap.exam                   1.293451  1        1.137300\nsat.taken                 1.036858  1        1.018262\ncte.achievement           1.979107  2        1.186089\ntotal.cte.courses.taken   2.072494  1        1.439616\nattended.ps               1.148563  1        1.071710\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Summary: Multivariate Confirmation — Persistent Non-Sustained Employment\n\n### Overview\n\nAcross all four models, fit improved steadily and modestly (AIC: 22,485 → 22,470 → 22,423 → 22,334; pseudo-R²: 0.018 → 0.019 → 0.022 → 0.026), with each block adding significant explanatory power. This is a confirmatory analysis, and on nearly every count, it succeeded: the demographic mechanism-split identified in the bivariate work holds up once every variable is considered simultaneously.\n\n### The bivariate predictions that held up cleanly\n\n- **Gender** (OR ≈ 1.55–1.57 across all four models) and **economic status** (OR ≈ 1.21–1.23) both show real, stable, non-attenuating disadvantage specific to non-sustained employment — exactly as the bivariate analysis predicted for the two variables identified as \"genuinely about job instability.\"\n- **English learner status** was essentially exactly null in every single model (p ranging from 0.84 to 0.98) — a clean, complete confirmation that this variable's overall disconnection disadvantage has nothing to do with non-sustained employment specifically.\n- **Non-English home** was significant and *protective* in every model (OR ≈ 0.65–0.66) — directly confirming the bivariate finding that this group shows *better*-than-average non-sustained outcomes despite a dramatically worse no-record outcome. This consistency across four fully-controlled models meaningfully strengthens confidence in what was, at the bivariate stage, a single cross-tabulation.\n- **Black graduates** showed a large, highly significant disadvantage in every model (OR ranging from 1.84 to 1.91) that never attenuated — and, consistent with the pattern seen throughout this entire project, actually *widened slightly* once postsecondary attendance was added in Model 4. This is the same non-attenuating Black-White gap that has now appeared in every single outcome and population examined across this entire body of work.\n- **Asian/Pacific Islander and Hispanic** were not significant in any of the four models — confirming the bivariate prediction that these two groups' disconnection disadvantage is concentrated almost entirely in the no-record mechanism, not this one.\n\n### The one prediction that didn't hold up cleanly\n\n**American Indian** showed a genuinely unstable trajectory across the sequence — borderline in Model 1 (p = 0.069), significant in Model 2 (p = 0.039), back to borderline in Model 3 (p = 0.067), and fully non-significant by Model 4 (p = 0.121). This is worth reporting honestly as an inconclusive finding rather than forcing it into either the \"confirmed disadvantage\" or \"confirmed null\" bucket — the coefficient's significance appears sensitive to exactly which other variables are in the model, which is itself a meaningful result about the fragility of this particular relationship.\n\n### High school characteristics and local labor market context\n\n**EDR 7E** emerged as a new, previously-untested finding: non-completers from EDR 7E high schools show significantly higher odds of persistent non-sustained employment across every model from Model 2 onward, strengthening slightly as accomplishments were added. **`avg.unemp.rate`** showed an interesting, non-monotonic story — not significant in Model 2, briefly significant and *protective* in Model 3 (consistent with the bivariate ANOVA's finding that this variable relates to intermittent/broad non-sustained status but not the most severe persistent form), then reverting to non-significant once `attended.ps` was added in Model 4, suggesting some of that Model 3 relationship ran through postsecondary attendance rather than being a fully independent labor-market effect. `avg.wages.pct.state` was not significant anywhere in this sequence, consistent with its weak bivariate relationship with non-sustained employment specifically.\n\n### The accomplishments story: the project's \"two pathways\" pattern reconfirmed directly\n\nThe ACT threshold pattern that has run through this entire project reappeared exactly as expected: `took.ACT` was significant and protective in both Models 3 and 4 (OR ≈ 0.61–0.62), while `ACTCompositeScore.filled` was significant and harmful (OR ≈ 1.02–1.02 per point) — participation helps, but a higher score among test-takers specifically predicts worse outcomes. Both `cte.achievement` categories were significant and protective throughout (OR ≈ 0.85–0.90), confirming CTE's established role. `sat.taken` was never significant in any model — directly confirming the bivariate finding that SAT's dramatic overall disadvantage belongs entirely to the no-record mechanism this analysis doesn't test. `ap.exam` trended toward harm in every model but never quite crossed significance (closest at Model 4, p = 0.051). `pseo.participant` was never significant, consistent with the bivariate finding that PSEO's clearest benefit is regional-employment-specific rather than about avoiding non-sustained employment broadly.\n\n### Postsecondary attendance\n\n`attended.ps` was strongly significant and protective once added in Model 4 (OR = 0.67), confirming a genuine, independent non-sustained-specific component to what was the single strongest predictor of overall disconnection in the bivariate analysis.\n\n### Bottom line\n\nThis confirmatory analysis validated the core mechanism-split hypothesis for four of five demographic variables and for every accomplishment variable tested, with American Indian's status left genuinely unresolved rather than confirmed either way. The clearest headline finding remains the Black-White gap: unmoved and slightly widening across every block, in a fifth distinct population/outcome combination now confirming this same pattern across the entire project. Ready to move to the `persistent.no_record` sequence, where several of these same variables — particularly non-English home, Asian/Pacific Islander, Hispanic, and the ACT/AP/SAT college-ambition signals — should reappear with their predicted effects reversed or strengthened.\n\n<br>\n\n# Modeling: persistent No MN emp record\n\n## Model 1: Demographics\n\nSample: N = 27,669 \\| AIC: 23,756.44 \\| Pseudo R² (McFadden-style): 0.0134\n\nThis is the mirror-image test of Model 1 from the non-sustained sequence, and the results are striking — this model largely reverses the demographic story just established, exactly as the bivariate analysis predicted.\n\n**Coefficient Interpretation** (recall: OR \\> 1 = higher odds of persistent no-record status, the *bad* outcome)\n\n*Gender — the clearest confirmation in this model*\n\n- **Gender is essentially exactly null** (OR = 0.98, p = 0.613) — a complete reversal of its strong, significant role in the non-sustained model (OR ≈ 1.55–1.57 there). This directly confirms the bivariate prediction that Gender's overall disconnection disadvantage is entirely about non-sustained employment and has nothing to do with disappearing from the record.\n\n*English Learner and Non-English Home — both confirm dramatically*\n\n- **English learner is significant and harmful here** (OR = 1.24, p \\< 0.001) — a complete reversal from its null result in the non-sustained model. This is a clean, direct confirmation that EL's disadvantage operates specifically through the no-record mechanism.\n- **Non-English home shows the largest effect in this entire model** (OR = 2.20, CI 1.85–2.62) — more than double the odds of persistent no-record status, and a complete reversal from its *protective* role in the non-sustained model (OR ≈ 0.65 there). This directly confirms the single largest bivariate finding from the earlier disconnection analysis: non-English-home students are not more likely to hold unstable jobs — they are dramatically more likely to disappear from Minnesota's employment record.\n\n*Economic Status — a genuinely new, reversed finding*\n\n- **Economic status is significant and *protective*** (OR = 0.81, CI 0.76–0.87) — not just weaker than its non-sustained role, but reversed in direction. Economically disadvantaged non-completers show *lower* odds of persistent no-record status. This wasn't clearly anticipated by the bivariate cross-tab (which showed only a modest relationship for this variable and mechanism), and is worth flagging as a genuinely new multivariate finding: one plausible reading is that economically disadvantaged individuals have fewer resources to relocate out of state or otherwise disengage from Minnesota's formal system, keeping them more likely to remain traceable in the employment record even without stable work. This is a substantive interpretation the data can't confirm directly, but it's a coherent story worth raising in any final report.\n\n*SpecialEdStatus*\n\n- **SpecialEdStatus is significant and harmful here too** (OR = 1.25, p \\< 0.001) — unlike Gender, this variable shows real disadvantage in *both* mechanisms (it was also significant and harmful in every non-sustained model). This confirms the bivariate finding that SpecialEdStatus's disadvantage splits fairly evenly across both channels rather than concentrating in one.\n\n*Race/Ethnicity — the mechanism split resolves almost perfectly, with one important nuance*\n\n- **Asian/Pacific Islander** (OR = 1.33, p = 0.017) and **Hispanic** (OR = 1.30, p = 0.007) are both **significant and harmful here**, a complete reversal from their null results in the non-sustained model. This is a precise, direct confirmation of the bivariate prediction that these two groups' disadvantage is concentrated almost entirely in the no-record mechanism.\n- **American Indian remains significant and harmful** (OR = 1.59, CI 1.30–1.92) — the largest race/ethnicity coefficient in this model, confirming this group's disadvantage operates through both mechanisms (as it showed instability but trended harmful in the non-sustained sequence, and now shows clear, strong harm here).\n- **Black shows a genuine reversal worth flagging carefully.** In the raw bivariate cross-tab, Black graduates showed a *modestly elevated* no-record rate (18.2% vs. White's 16.1%). Here, in the fully controlled multivariate model, **Black is significant and *protective*** (OR = 0.82, CI 0.68–0.98) — the opposite direction from the simple bivariate comparison. This is exactly the kind of shift this analysis's own methodology introduction warned could happen once other variables are controlled simultaneously, and it should be reported as a genuine multivariate finding rather than assumed to match the earlier bivariate direction: once other demographics (especially non-English home and English learner status, which likely correlate with race/ethnicity to some degree) are accounted for, Black graduates show a small but real *protective* association with staying visible in Minnesota's employment record — even though, as the non-sustained model showed, Black graduates remain considerably more likely to experience unstable employment specifically.\n\n**Multicollinearity Check**\n\nOverall still fine, but worth a brief note: `RaceEthnicity` (GVIF\\^(1/(2·Df)) = 1.08) and `non.english.home` (1.42) are both somewhat higher here than in the equivalent non-sustained model (1.06 and 1.28, respectively), consistent with some correlation between race/ethnicity, English learner status, and non-English home. Still comfortably under the \\~2.0–2.5 concern threshold, so no action needed, but worth keeping in mind if any of these coefficients seem unstable across later blocks.\n\n**Substantive Pattern**\n\nThis model delivers close to a perfect mirror image of the non-sustained sequence, exactly as the bivariate mechanism-split hypothesis predicted: Gender flips from strongly harmful to null, English learner flips from null to strongly harmful, non-English home flips from protective to the single largest harmful effect in the model, and Asian/Pacific Islander and Hispanic both flip from null to significantly harmful. The one finding that doesn't fit a clean mirror-image story is Black graduates, whose bivariate no-record disadvantage reverses to a protective, multivariate-adjusted effect — a genuinely important nuance that should be reported as its own finding rather than assumed away, and a useful illustration of exactly the kind of bivariate-to-multivariate shift this analysis was designed to check for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_no_record <- glm(\n  persistent.no_record ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home,\n  family = binomial,\n  data = master.disc\n)\n\nsummary(model1_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home, \n    family = binomial, data = master.disc)\n\nCoefficients:\n                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -1.73071    0.02765 -62.597  < 2e-16 ***\nGenderF               -0.01727    0.03418  -0.505 0.613397    \nRaceEthnicityAI        0.46116    0.09852   4.681 2.86e-06 ***\nRaceEthnicityAsian/PI  0.28763    0.12080   2.381 0.017261 *  \nRaceEthnicityBlack    -0.20162    0.09570  -2.107 0.035126 *  \nRaceEthnicityHispanic  0.25895    0.09546   2.713 0.006672 ** \neconomic.status1      -0.21109    0.03527  -5.986 2.15e-09 ***\nSpecialEdStatus1       0.21945    0.04537   4.836 1.32e-06 ***\nenglish.learner1       0.21836    0.06043   3.613 0.000302 ***\nnon.english.home1      0.78917    0.08912   8.855  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 24060  on 27668  degrees of freedom\nResidual deviance: 23736  on 27659  degrees of freedom\nAIC: 23756\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model1_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model1_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23756.44\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model1_no_record), confint(model1_no_record)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             OR     2.5 %    97.5 %\n(Intercept)           0.1771594 0.1677713 0.1869769\nGenderF               0.9828798 0.9191031 1.0508837\nRaceEthnicityAI       1.5859089 1.3030950 1.9179051\nRaceEthnicityAsian/PI 1.3332602 1.0480503 1.6833722\nRaceEthnicityBlack    0.8174035 0.6756897 0.9833874\nRaceEthnicityHispanic 1.2955744 1.0723911 1.5592159\neconomic.status1      0.8096981 0.7555418 0.8675585\nSpecialEdStatus1      1.2453862 1.1389020 1.3606290\nenglish.learner1      1.2440300 1.1048560 1.4002226\nnon.english.home1     2.2015601 1.8477395 2.6205899\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model1_no_record$deviance / model1_no_record$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01344456\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model1_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     GVIF Df GVIF^(1/(2*Df))\nGender           1.015799  1        1.007869\nRaceEthnicity    1.818379  4        1.077607\neconomic.status  1.109603  1        1.053377\nSpecialEdStatus  1.426390  1        1.194316\nenglish.learner  1.771342  1        1.330918\nnon.english.home 2.017186  1        1.420277\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Model 2: Add High School Characteristics\n\nSample: N = 27,669 (unchanged from Model 1) \\| AIC: 23,736.46 (down slightly from 23,756.44) \\| Pseudo R² (McFadden-style): 0.0146 (up from 0.0134)\n\nLikelihood ratio test vs. Model 1: Δdeviance = 27.98 on 4 df, p \\< 0.001 — significant, though modest, similar in scale to the equivalent non-sustained block.\n\n**Coefficient Interpretation** (recall: OR \\> 1 = higher odds of persistent no-record status)\n\n*Gender — remains the clearest confirmation*\n\n- Gender remains **exactly null** (OR = 0.98, p = 0.582), unchanged from Model 1, continuing to confirm this variable's disadvantage is entirely non-sustained-specific.\n\n*Economic Status, SpecialEdStatus, English Learner, and Non-English Home — all remain stable*\n\n- Economic status remains significant and **protective**, essentially unchanged (OR = 0.79, vs. 0.81 in Model 1).\n- SpecialEdStatus remains significant and harmful (OR = 1.25), unchanged.\n- English learner remains significant and harmful (OR = 1.25), unchanged — continuing to confirm the mirror-image relationship to its null non-sustained result.\n- **Non-English home remains the largest coefficient in the model** (OR = 2.23, CI 1.87–2.66), essentially unchanged from Model 1 (2.20) — this finding is proving completely robust across HS-context controls.\n\n*Race/Ethnicity*\n\n- American Indian **attenuates somewhat but remains significant** (OR = 1.49, down from 1.59 in Model 1).\n- Asian/Pacific Islander and Hispanic both remain significant and harmful (OR = 1.37 and 1.33, respectively), essentially unchanged — continuing to confirm the bivariate prediction cleanly.\n- **Black's protective effect weakens to non-significance** (OR = 0.87, p = 0.133, up from a significant 0.82 in Model 1). Some of Model 1's protective association appears to run through HS characteristics — worth watching whether this returns, strengthens, or stays null once accomplishments are added in Model 3, since Model 1's reversal-from-bivariate finding was itself a notable result worth tracking carefully.\n\n*Regional and Local Labor Market Context — a new, coherent finding*\n\n- **Both EDR 7E (OR = 0.86, p = 0.001) and EDR 7W (OR = 0.78, p \\< 0.001) are significant and protective** relative to EDR 5 — non-completers from either region show meaningfully lower odds of persistent no-record status than those from EDR 5. This is directly consistent with the bivariate `edr` table, which showed EDR 5 as the clear laggard specifically for no-record status (worse than both EDR 7E and EDR 7W), now confirmed in a fully controlled multivariate model.\n- Neither `avg.wages.pct.state` (OR = 1.47, p = 0.354) nor `avg.unemp.rate` (OR = 1.01, p = 0.542) is significant here — this is a genuine departure from the sustained-employment analysis, where local wages showed an extremely dramatic relationship with regional employment specifically. Here, in this general non-completer population predicting no-record status directly, neither continuous labor-market variable shows an independent effect once demographics and region are controlled — consistent with the bivariate ANOVA finding that both variables showed only a modest, threshold-type relationship with `no_record.cat` (distinguishing \"any exposure\" from \"none,\" but with a small overall effect size).\n\n**Multicollinearity Check**\n\nLooks good — all GVIF\\^(1/(2·Df)) values are low, with the highest being `non.english.home` (1.42) and `avg.wages.pct.state` (1.45), both comfortably under the \\~2.0–2.5 concern threshold. No issues in this block.\n\n**Substantive Pattern**\n\n`edr`'s finding here is the clean, new confirmation this block adds: EDR 5 is specifically disadvantaged for no-record status, exactly as the bivariate table showed, while EDR 7E and EDR 7W are both protective by comparison. This nicely complements (without duplicating) the sustained-employment analysis, where `edr`'s pattern looked completely different depending on which mechanism was being measured — here, focused directly on no-record status alone, the regional story is cleaner and matches the bivariate prediction precisely. The one coefficient worth continued attention is Black graduates, whose protective Model 1 finding weakened to non-significance here; whether this represents a genuine, small protective effect that HS characteristics partially explain, or whether Model 1's result was itself somewhat fragile, should become clearer once accomplishments are added.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2_no_record <- glm(\n  persistent.no_record ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home +\n    edr +\n    avg.wages.pct.state +\n    avg.unemp.rate,\n  family = binomial,\n  data = master.disc\n)\n\nnobs(model2_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model2_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23736.46\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model2_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate, family = binomial, \n    data = master.disc)\n\nCoefficients:\n                         Estimate Std. Error z value Pr(>|z|)    \n(Intercept)             -1.906631   0.343809  -5.546 2.93e-08 ***\nGenderF                 -0.018816   0.034207  -0.550 0.582273    \nRaceEthnicityAI          0.396011   0.099688   3.972 7.11e-05 ***\nRaceEthnicityAsian/PI    0.312593   0.120889   2.586 0.009716 ** \nRaceEthnicityBlack      -0.144366   0.096175  -1.501 0.133336    \nRaceEthnicityHispanic    0.283292   0.095492   2.967 0.003011 ** \neconomic.status1        -0.238585   0.035945  -6.638 3.19e-11 ***\nSpecialEdStatus1         0.221447   0.045504   4.866 1.14e-06 ***\nenglish.learner1         0.224475   0.060793   3.692 0.000222 ***\nnon.english.home1        0.803654   0.089099   9.020  < 2e-16 ***\nedrEDR 7E- East Central -0.155190   0.047906  -3.239 0.001197 ** \nedrEDR 7W- Central      -0.242192   0.055019  -4.402 1.07e-05 ***\navg.wages.pct.state      0.383277   0.413882   0.926 0.354418    \navg.unemp.rate           0.006401   0.010486   0.610 0.541586    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 24060  on 27668  degrees of freedom\nResidual deviance: 23708  on 27655  degrees of freedom\nAIC: 23736\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model2_no_record), confint(model2_no_record)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               OR      2.5 %    97.5 %\n(Intercept)             0.1485800 0.07565469 0.2911857\nGenderF                 0.9813595 0.91763086 1.0493159\nRaceEthnicityAI         1.4858856 1.21818508 1.8011377\nRaceEthnicityAsian/PI   1.3669649 1.07436197 1.7262665\nRaceEthnicityBlack      0.8655710 0.71485835 1.0423485\nRaceEthnicityHispanic   1.3274930 1.09874782 1.5977598\neconomic.status1        0.7877415 0.73407596 0.8451555\nSpecialEdStatus1        1.2478810 1.14089453 1.3637063\nenglish.learner1        1.2516649 1.11085779 1.4098303\nnon.english.home1       2.2336881 1.87482103 2.6587403\nedrEDR 7E- East Central 0.8562522 0.77950092 0.9405462\nedrEDR 7W- Central      0.7849057 0.70472577 0.8743586\navg.wages.pct.state     1.4670841 0.65248313 3.3052822\navg.unemp.rate          1.0064212 0.98591575 1.0272868\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel2_no_record\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate, family = binomial, \n    data = master.disc)\n\nCoefficients:\n            (Intercept)                  GenderF          RaceEthnicityAI  \n              -1.906631                -0.018816                 0.396011  \n  RaceEthnicityAsian/PI       RaceEthnicityBlack    RaceEthnicityHispanic  \n               0.312593                -0.144366                 0.283292  \n       economic.status1         SpecialEdStatus1         english.learner1  \n              -0.238585                 0.221447                 0.224475  \n      non.english.home1  edrEDR 7E- East Central       edrEDR 7W- Central  \n               0.803654                -0.155190                -0.242192  \n    avg.wages.pct.state           avg.unemp.rate  \n               0.383277                 0.006401  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27655 Residual\nNull Deviance:\t    24060 \nResidual Deviance: 23710 \tAIC: 23740\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(model1_no_record, model2_no_record, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home\nModel 2: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1     27659      23736                          \n2     27655      23708  4   27.981 1.258e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model2_no_record$deviance / model2_no_record$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01460754\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model2_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        GVIF Df GVIF^(1/(2*Df))\nGender              1.016400  1        1.008166\nRaceEthnicity       1.884235  4        1.082410\neconomic.status     1.151586  1        1.073120\nSpecialEdStatus     1.432788  1        1.196991\nenglish.learner     1.791687  1        1.338539\nnon.english.home    2.013694  1        1.419047\nedr                 2.204322  2        1.218481\navg.wages.pct.state 2.105641  1        1.451083\navg.unemp.rate      1.375530  1        1.172830\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Model 3: Add High School Accomplishments\n\nSample: N = 27,669 (unchanged from Models 1–2) \\| AIC: 23,414.98 (down substantially from 23,736.46) \\| Pseudo R² (McFadden-style): 0.0286 (up from 0.0146)\n\nLikelihood ratio test vs. Model 2: Δdeviance = 337.48 on 8 df, p \\< 2.2e-16 — the largest single-block improvement in either sequence so far, more than five times the equivalent non-sustained block (62.96).\n\n**Coefficient Interpretation** (recall: OR \\> 1 = higher odds of persistent no-record status)\n\n*Gender, Economic Status, SpecialEdStatus, English Learner, and Non-English Home*\n\n- Gender remains not significant (OR = 0.96, p = 0.207).\n- Economic status remains significant and protective (OR = 0.78), essentially unchanged.\n- SpecialEdStatus remains significant and harmful but **attenuates somewhat** (OR = 1.16, down from 1.25 in Model 2) — some of its effect runs through accomplishments, consistent with its dual-mechanism role established in the earlier three-way bivariate comparison.\n- English learner remains significant and harmful (OR = 1.27), essentially unchanged.\n- **Non-English home remains the largest coefficient in the model** (OR = 2.12, CI 1.78–2.53), barely moved across three blocks now — this finding is proving completely robust to every control tested.\n\n*Race/Ethnicity*\n\n- American Indian remains significant (OR = 1.43), modestly attenuated from Model 2.\n- Asian/Pacific Islander and Hispanic both remain significant and harmful (OR = 1.38 and 1.29), continuing to confirm the mechanism split cleanly.\n- **Black remains not significant** (OR = 0.87, p = 0.144) — Model 1's protective finding has not returned; this coefficient appears to have been a Model-1-specific result that attenuates once HS context and accomplishments are both accounted for.\n\n*Regional and Local Labor Market Context*\n\n- **EDR 7E is no longer significant** (OR = 0.93, p = 0.152) — attenuated from Model 2's significant result; some of its protective association runs through accomplishments.\n- EDR 7W remains significant and protective (OR = 0.72).\n- `avg.wages.pct.state` remains not significant.\n- **`avg.unemp.rate` becomes significant here** (OR = 0.96, p \\< 0.001) — a genuine \"emerges once accomplishments are controlled\" pattern, protective in direction, distinct from its null result in Model 2.\n\n*High School Accomplishments — the mechanism split's clearest confirmation*\n\n- **`took.ACT` is dramatically stronger here than in the non-sustained model** (OR = 0.31, CI 0.24–0.40, vs. 0.61 non-sustained) — simply taking the ACT is associated with a nearly 70% reduction in odds of persistent no-record status, roughly twice the protective magnitude seen for non-sustained employment.\n- **`ACTCompositeScore.filled` shows a stronger harmful effect here too** (OR = 1.042 per point, vs. 1.021 non-sustained) — confirming the earlier three-way bivariate finding that ACT score's relationship with disconnection is concentrated overwhelmingly in the no-record mechanism.\n- **`sat.taken` flips from completely null in the non-sustained model to strongly significant and harmful here** (OR = 1.99, CI 1.44–2.71, vs. 1.13, p = 0.542 non-sustained). This is the single cleanest confirmation of the entire mechanism-split hypothesis in this whole two-part analysis: SAT-taking's dramatic bivariate disconnection disadvantage — the largest raw gap found anywhere in the earlier bivariate work — is confirmed here, in a fully controlled multivariate model, to be almost entirely a no-record phenomenon. Non-completers who took the SAT are essentially twice as likely to disappear from Minnesota's employment record, with no corresponding relationship to job instability.\n- `ap.exam` is **not significant here** (OR = 0.93, p = 0.310) — a modest reversal from its borderline-harmful trend in the non-sustained model, though neither reaches clear significance in either mechanism.\n- Both `cte.achievement` categories remain significant and protective, similar magnitude to the non-sustained model (OR = 0.81 and 0.83).\n- **`total.cte.courses.taken` is significant here** (OR = 0.96 per course, p \\< 0.001) — unlike its non-significant result in the non-sustained model (p = 0.136), confirming the earlier three-way bivariate finding that this variable's relationship with disconnection concentrates more in the no-record dimension.\n- `pseo.participant` remains **not significant** (OR = 0.97, p = 0.570) — notably, PSEO's real bivariate relationships with both isolated mechanisms (each significant at the bivariate stage) don't survive full multivariate control in either sequence, worth flagging as a case where the bivariate finding didn't replicate once fully adjusted.\n\n**Multicollinearity Check**\n\n`took.ACT` and `ACTCompositeScore.filled` are elevated as expected (3.79 and 4.03), slightly higher than the equivalent non-sustained model. Everything else remains comfortably under the \\~2.0–2.5 threshold, including `avg.wages.pct.state` (1.47) and `total.cte.courses.taken` (1.45).\n\n**Substantive Pattern**\n\nThis model is the strongest evidence in this entire two-part analysis for the original bivariate mechanism-split hypothesis. Every \"college-ambition\" accomplishment variable — ACT score, and especially SAT-taking — shows a considerably stronger, or in SAT's case entirely newly-emerged, relationship with no-record status compared to non-sustained employment, precisely mirroring the earlier bivariate three-way comparison. CTE variables continue to confirm their dual-channel protective role. The one finding that didn't hold up as cleanly is PSEO participation, whose real bivariate relationships with each mechanism separately don't survive once demographics, region, and other accomplishments are controlled simultaneously — a useful reminder that this confirmatory stage exists precisely to catch results like this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3_no_record <- glm(\n  persistent.no_record ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home +\n    edr +\n    avg.wages.pct.state +\n    avg.unemp.rate +\n    pseo.participant +\n    took.ACT +\n    ACTCompositeScore.filled +\n    ap.exam +\n    sat.taken +\n    cte.achievement +\n    total.cte.courses.taken,\n  family = binomial,\n  data = master.disc\n)\n\nnobs(model3_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model3_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23414.98\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model3_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken, family = binomial, \n    data = master.disc)\n\nCoefficients:\n                                              Estimate Std. Error z value\n(Intercept)                                  -1.053140   0.351785  -2.994\nGenderF                                      -0.043974   0.034870  -1.261\nRaceEthnicityAI                               0.356341   0.100777   3.536\nRaceEthnicityAsian/PI                         0.319282   0.121754   2.622\nRaceEthnicityBlack                           -0.141058   0.096534  -1.461\nRaceEthnicityHispanic                         0.253839   0.095803   2.650\neconomic.status1                             -0.249275   0.036586  -6.813\nSpecialEdStatus1                              0.144208   0.047479   3.037\nenglish.learner1                              0.235296   0.061223   3.843\nnon.english.home1                             0.753745   0.089330   8.438\nedrEDR 7E- East Central                      -0.069799   0.048685  -1.434\nedrEDR 7W- Central                           -0.321622   0.055638  -5.781\navg.wages.pct.state                           0.282303   0.417407   0.676\navg.unemp.rate                               -0.039458   0.011092  -3.557\npseo.participant1                            -0.026105   0.046003  -0.567\ntook.ACTYes                                  -1.179577   0.129510  -9.108\nACTCompositeScore.filled                      0.040803   0.006378   6.398\nap.exam1                                     -0.067331   0.066368  -1.015\nsat.taken1                                    0.686334   0.161823   4.241\ncte.achievementCTE Concentrator or Completor -0.205177   0.057296  -3.581\ncte.achievementCTE Participant               -0.182462   0.045036  -4.051\ntotal.cte.courses.taken                      -0.037659   0.006776  -5.558\n                                             Pr(>|z|)    \n(Intercept)                                  0.002756 ** \nGenderF                                      0.207272    \nRaceEthnicityAI                              0.000406 ***\nRaceEthnicityAsian/PI                        0.008733 ** \nRaceEthnicityBlack                           0.143955    \nRaceEthnicityHispanic                        0.008059 ** \neconomic.status1                             9.54e-12 ***\nSpecialEdStatus1                             0.002387 ** \nenglish.learner1                             0.000121 ***\nnon.english.home1                             < 2e-16 ***\nedrEDR 7E- East Central                      0.151665    \nedrEDR 7W- Central                           7.44e-09 ***\navg.wages.pct.state                          0.498833    \navg.unemp.rate                               0.000375 ***\npseo.participant1                            0.570400    \ntook.ACTYes                                   < 2e-16 ***\nACTCompositeScore.filled                     1.58e-10 ***\nap.exam1                                     0.310337    \nsat.taken1                                   2.22e-05 ***\ncte.achievementCTE Concentrator or Completor 0.000342 ***\ncte.achievementCTE Participant               5.09e-05 ***\ntotal.cte.courses.taken                      2.73e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 24060  on 27668  degrees of freedom\nResidual deviance: 23371  on 27647  degrees of freedom\nAIC: 23415\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel3_no_record\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken, family = binomial, \n    data = master.disc)\n\nCoefficients:\n                                 (Intercept)  \n                                    -1.05314  \n                                     GenderF  \n                                    -0.04397  \n                             RaceEthnicityAI  \n                                     0.35634  \n                       RaceEthnicityAsian/PI  \n                                     0.31928  \n                          RaceEthnicityBlack  \n                                    -0.14106  \n                       RaceEthnicityHispanic  \n                                     0.25384  \n                            economic.status1  \n                                    -0.24927  \n                            SpecialEdStatus1  \n                                     0.14421  \n                            english.learner1  \n                                     0.23530  \n                           non.english.home1  \n                                     0.75375  \n                     edrEDR 7E- East Central  \n                                    -0.06980  \n                          edrEDR 7W- Central  \n                                    -0.32162  \n                         avg.wages.pct.state  \n                                     0.28230  \n                              avg.unemp.rate  \n                                    -0.03946  \n                           pseo.participant1  \n                                    -0.02610  \n                                 took.ACTYes  \n                                    -1.17958  \n                    ACTCompositeScore.filled  \n                                     0.04080  \n                                    ap.exam1  \n                                    -0.06733  \n                                  sat.taken1  \n                                     0.68633  \ncte.achievementCTE Concentrator or Completor  \n                                    -0.20518  \n              cte.achievementCTE Participant  \n                                    -0.18246  \n                     total.cte.courses.taken  \n                                    -0.03766  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27647 Residual\nNull Deviance:\t    24060 \nResidual Deviance: 23370 \tAIC: 23410\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model3_no_record), confint(model3_no_record)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                    OR     2.5 %    97.5 %\n(Intercept)                                  0.3488408 0.1748937 0.6945439\nGenderF                                      0.9569788 0.8936712 1.0245755\nRaceEthnicityAI                              1.4280944 1.1683913 1.7349079\nRaceEthnicityAsian/PI                        1.3761398 1.0798164 1.7409401\nRaceEthnicityBlack                           0.8684392 0.7167661 1.0466115\nRaceEthnicityHispanic                        1.2889642 1.0662566 1.5524120\neconomic.status1                             0.7793657 0.7253620 0.8372281\nSpecialEdStatus1                             1.1551247 1.0520533 1.2672868\nenglish.learner1                             1.2652835 1.1220104 1.4263879\nnon.english.home1                            2.1249437 1.7828481 2.5306202\nedrEDR 7E- East Central                      0.9325813 0.8477000 1.0259680\nedrEDR 7W- Central                           0.7249720 0.6501219 0.8085724\navg.wages.pct.state                          1.3261811 0.5856936 3.0083224\navg.unemp.rate                               0.9613107 0.9405957 0.9823968\npseo.participant1                            0.9742329 0.8899420 1.0658222\ntook.ACTYes                                  0.3074087 0.2383506 0.3960220\nACTCompositeScore.filled                     1.0416467 1.0286965 1.0547403\nap.exam1                                     0.9348853 0.8200088 1.0637231\nsat.taken1                                   1.9864197 1.4375227 2.7138465\ncte.achievementCTE Concentrator or Completor 0.8145030 0.7278313 0.9111265\ncte.achievementCTE Participant               0.8332167 0.7627595 0.9100447\ntotal.cte.courses.taken                      0.9630410 0.9502768 0.9758563\n```\n\n\n:::\n\n```{.r .cell-code}\n# likelihood ratio test comparing Model 2 to Model 3\nanova(model1_no_record, model2_no_record, model3_no_record, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home\nModel 2: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate\nModel 3: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1     27659      23736                          \n2     27655      23708  4    27.98 1.258e-05 ***\n3     27647      23371  8   337.48 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model3_no_record$deviance / model3_no_record$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02863404\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model3_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              GVIF Df GVIF^(1/(2*Df))\nGender                    1.042638  1        1.021096\nRaceEthnicity             1.879120  4        1.082042\neconomic.status           1.178337  1        1.085512\nSpecialEdStatus           1.541055  1        1.241392\nenglish.learner           1.792584  1        1.338874\nnon.english.home          1.981234  1        1.407563\nedr                       2.353824  2        1.238635\navg.wages.pct.state       2.146279  1        1.465018\navg.unemp.rate            1.493509  1        1.222092\npseo.participant          1.334785  1        1.155329\ntook.ACT                 14.401981  1        3.794994\nACTCompositeScore.filled 16.223190  1        4.027802\nap.exam                   1.281029  1        1.131825\nsat.taken                 1.045017  1        1.022261\ncte.achievement           1.998268  2        1.188950\ntotal.cte.courses.taken   2.088355  1        1.445114\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Model 4: Add Postsecondary\n\nSample: N = 27,669 (unchanged from Models 1–3) \\| AIC: 23,278.38 (down from 23,414.98) \\| Pseudo R² (McFadden-style): 0.0344 (up from 0.0286)\n\nLikelihood ratio test vs. Model 3: Δdeviance = 138.60 on 1 df, p \\< 2.2e-16 — the largest single-block improvement anywhere in either sequence, larger even than `attended.ps`'s equivalent contribution to the non-sustained model (91.02).\n\n**Coefficient Interpretation** (recall: OR \\> 1 = higher odds of persistent no-record status)\n\n*Gender, Economic Status, SpecialEdStatus, English Learner, and Non-English Home*\n\n- Gender remains not significant.\n- Economic status remains significant and protective (OR = 0.77), essentially unchanged.\n- SpecialEdStatus remains significant but continues to weaken (OR = 1.12, p = 0.019, down from 1.16 in Model 3) — some of its effect continues to run through postsecondary attendance.\n- English learner remains significant and harmful (OR = 1.27), unchanged.\n- **Non-English home remains the largest coefficient in the model** (OR = 2.10, CI 1.76–2.50), stable across all four blocks — the single most robust finding in this entire two-part project.\n\n*Race/Ethnicity*\n\n- American Indian, Asian/Pacific Islander, and Hispanic all remain significant and harmful (OR = 1.38, 1.38, and 1.30), essentially unchanged from Model 3.\n- **Black remains not significant** (OR = 0.92, p = 0.359) — confirming Model 3's finding that the Model 1 protective effect does not survive full multivariate control.\n\n*Regional and Local Labor Market Context*\n\n- EDR 7E remains **borderline** (OR = 0.92, p = 0.089).\n- EDR 7W remains significant and protective (OR = 0.74).\n- `avg.wages.pct.state` remains not significant.\n- **`avg.unemp.rate` drops to non-significance here** (OR = 0.99, p = 0.377, down from a significant 0.96 in Model 3) — some of that effect runs through postsecondary attendance, exactly mirroring the identical pattern seen in the non-sustained sequence at this same step. This parallel between both sequences is a useful, reassuring consistency check: the same mechanism (unemployment's relationship partly running through `attended.ps`) shows up independently in both mechanism-specific models.\n\n*High School Accomplishments*\n\n- `took.ACT` (OR = 0.32), `ACTCompositeScore.filled` (OR = 1.045 per point), and `sat.taken` (OR = 2.00) all remain essentially unchanged from Model 3 — confirming these are genuine, stable, independent relationships that survive controlling for postsecondary attendance.\n- Both `cte.achievement` categories and `total.cte.courses.taken` remain significant and protective, essentially stable.\n- `pseo.participant` and `ap.exam` both remain not significant, consistent with Model 3.\n\n*Postsecondary Attendance*\n\n- **Having attended some postsecondary education is significant and strongly protective** (OR = 0.61, CI 0.56–0.67) — and notably, this is a **stronger effect than its counterpart in the non-sustained model** (OR = 0.67 there). This directly confirms and even sharpens the bivariate three-way finding that `attended.ps`'s benefit splits almost evenly between the two mechanisms with a slight edge toward no-record status (the bivariate gaps were 5.1 points for non-sustained vs. 5.6 points for no-record) — now shown here as a genuinely stronger, fully independent protective effect for no-record status specifically, even after every other variable in the model is controlled.\n\n**Multicollinearity Check**\n\n`took.ACT` and `ACTCompositeScore.filled` remain elevated as expected (3.77 and 4.01). `attended.ps` itself is low (1.07). Everything else remains comfortably under the \\~2.0–2.5 threshold.\n\n**Substantive Pattern**\n\nThis completes the planned 4-model sequence for persistent no-record status. `attended.ps` closes out both sequences as a genuinely dual-mechanism protective factor, exactly as the bivariate work predicted — real and significant in both models, with a modest edge toward the no-record mechanism specifically. The parallel attenuation of `avg.unemp.rate` once `attended.ps` enters, appearing independently in both sequences, adds confidence that this is a real, reproducible dynamic rather than a coincidence in either individual model. Combined with Model 3's SAT-taking reversal, this analysis has now delivered strong, direct multivariate confirmation of nearly every mechanism-specific prediction the bivariate stage produced.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4_no_record <- glm(\n  persistent.no_record ~\n    Gender +\n    RaceEthnicity +\n    economic.status +\n    SpecialEdStatus +\n    english.learner +\n    non.english.home +\n    edr +\n    avg.wages.pct.state +\n    avg.unemp.rate +\n    pseo.participant +\n    took.ACT +\n    ACTCompositeScore.filled +\n    ap.exam +\n    sat.taken +\n    cte.achievement +\n    total.cte.courses.taken +\n    attended.ps,\n  family = binomial,\n  data = master.disc\n)\n\nnobs(model4_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27669\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model4_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23278.38\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model4_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken + attended.ps, \n    family = binomial, data = master.disc)\n\nCoefficients:\n                                              Estimate Std. Error z value\n(Intercept)                                  -1.326204   0.353549  -3.751\nGenderF                                      -0.036418   0.034990  -1.041\nRaceEthnicityAI                               0.322728   0.101095   3.192\nRaceEthnicityAsian/PI                         0.323596   0.122086   2.651\nRaceEthnicityBlack                           -0.088684   0.096587  -0.918\nRaceEthnicityHispanic                         0.260974   0.095962   2.720\neconomic.status1                             -0.266699   0.036696  -7.268\nSpecialEdStatus1                              0.111939   0.047660   2.349\nenglish.learner1                              0.235566   0.061289   3.844\nnon.english.home1                             0.740279   0.089323   8.288\nedrEDR 7E- East Central                      -0.083069   0.048824  -1.701\nedrEDR 7W- Central                           -0.300542   0.055850  -5.381\navg.wages.pct.state                           0.496855   0.418885   1.186\navg.unemp.rate                               -0.010052   0.011369  -0.884\npseo.participant1                            -0.013390   0.046373  -0.289\ntook.ACTYes                                  -1.145861   0.129023  -8.881\nACTCompositeScore.filled                      0.044484   0.006373   6.980\nap.exam1                                     -0.054362   0.066990  -0.811\nsat.taken1                                    0.691865   0.163663   4.227\ncte.achievementCTE Concentrator or Completor -0.206619   0.057352  -3.603\ncte.achievementCTE Participant               -0.168533   0.045156  -3.732\ntotal.cte.courses.taken                      -0.037259   0.006775  -5.500\nattended.psYes                               -0.487532   0.042411 -11.496\n                                             Pr(>|z|)    \n(Intercept)                                  0.000176 ***\nGenderF                                      0.297958    \nRaceEthnicityAI                              0.001411 ** \nRaceEthnicityAsian/PI                        0.008036 ** \nRaceEthnicityBlack                           0.358528    \nRaceEthnicityHispanic                        0.006537 ** \neconomic.status1                             3.66e-13 ***\nSpecialEdStatus1                             0.018840 *  \nenglish.learner1                             0.000121 ***\nnon.english.home1                             < 2e-16 ***\nedrEDR 7E- East Central                      0.088865 .  \nedrEDR 7W- Central                           7.40e-08 ***\navg.wages.pct.state                          0.235568    \navg.unemp.rate                               0.376591    \npseo.participant1                            0.772770    \ntook.ACTYes                                   < 2e-16 ***\nACTCompositeScore.filled                     2.96e-12 ***\nap.exam1                                     0.417081    \nsat.taken1                                   2.36e-05 ***\ncte.achievementCTE Concentrator or Completor 0.000315 ***\ncte.achievementCTE Participant               0.000190 ***\ntotal.cte.courses.taken                      3.80e-08 ***\nattended.psYes                                < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 24060  on 27668  degrees of freedom\nResidual deviance: 23232  on 27646  degrees of freedom\nAIC: 23278\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel4_no_record\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = persistent.no_record ~ Gender + RaceEthnicity + \n    economic.status + SpecialEdStatus + english.learner + non.english.home + \n    edr + avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken + attended.ps, \n    family = binomial, data = master.disc)\n\nCoefficients:\n                                 (Intercept)  \n                                    -1.32620  \n                                     GenderF  \n                                    -0.03642  \n                             RaceEthnicityAI  \n                                     0.32273  \n                       RaceEthnicityAsian/PI  \n                                     0.32360  \n                          RaceEthnicityBlack  \n                                    -0.08868  \n                       RaceEthnicityHispanic  \n                                     0.26097  \n                            economic.status1  \n                                    -0.26670  \n                            SpecialEdStatus1  \n                                     0.11194  \n                            english.learner1  \n                                     0.23557  \n                           non.english.home1  \n                                     0.74028  \n                     edrEDR 7E- East Central  \n                                    -0.08307  \n                          edrEDR 7W- Central  \n                                    -0.30054  \n                         avg.wages.pct.state  \n                                     0.49686  \n                              avg.unemp.rate  \n                                    -0.01005  \n                           pseo.participant1  \n                                    -0.01339  \n                                 took.ACTYes  \n                                    -1.14586  \n                    ACTCompositeScore.filled  \n                                     0.04448  \n                                    ap.exam1  \n                                    -0.05436  \n                                  sat.taken1  \n                                     0.69187  \ncte.achievementCTE Concentrator or Completor  \n                                    -0.20662  \n              cte.achievementCTE Participant  \n                                    -0.16853  \n                     total.cte.courses.taken  \n                                    -0.03726  \n                              attended.psYes  \n                                    -0.48753  \n\nDegrees of Freedom: 27668 Total (i.e. Null);  27646 Residual\nNull Deviance:\t    24060 \nResidual Deviance: 23230 \tAIC: 23280\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(cbind(OR = coef(model4_no_record), confint(model4_no_record)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                    OR     2.5 %    97.5 %\n(Intercept)                                  0.2654831 0.1326373 0.5303981\nGenderF                                      0.9642371 0.9002369 1.0325916\nRaceEthnicityAI                              1.3808890 1.1290754 1.6786199\nRaceEthnicityAsian/PI                        1.3820891 1.0838130 1.7496704\nRaceEthnicityBlack                           0.9151348 0.7552435 1.1030335\nRaceEthnicityHispanic                        1.2981938 1.0735685 1.5640411\neconomic.status1                             0.7659033 0.7126775 0.8229438\nSpecialEdStatus1                             1.1184446 1.0182797 1.2274793\nenglish.learner1                             1.2656250 1.1221705 1.4269640\nnon.english.home1                            2.0965209 1.7590580 2.4967907\nedrEDR 7E- East Central                      0.9202875 0.8362967 1.0127175\nedrEDR 7W- Central                           0.7404169 0.6636968 0.8261454\navg.wages.pct.state                          1.6435447 0.7237473 3.7390983\navg.unemp.rate                               0.9899983 0.9681438 1.0122677\npseo.participant1                            0.9866990 0.9006746 1.0802449\ntook.ACTYes                                  0.3179500 0.2467560 0.4092091\nACTCompositeScore.filled                     1.0454879 1.0324999 1.0586227\nap.exam1                                     0.9470892 0.8296994 1.0789262\nsat.taken1                                   1.9974377 1.4403540 2.7388147\ncte.achievementCTE Concentrator or Completor 0.8133291 0.7267038 0.9099170\ncte.achievementCTE Participant               0.8449035 0.7732767 0.9230303\ntotal.cte.courses.taken                      0.9634266 0.9506588 0.9762454\nattended.psYes                               0.6141401 0.5649385 0.6671325\n```\n\n\n:::\n\n```{.r .cell-code}\n# likelihood ratio test comparing Model 2 to Model 3\nanova(model1_no_record, model2_no_record, model3_no_record, model4_no_record, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home\nModel 2: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate\nModel 3: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken\nModel 4: persistent.no_record ~ Gender + RaceEthnicity + economic.status + \n    SpecialEdStatus + english.learner + non.english.home + edr + \n    avg.wages.pct.state + avg.unemp.rate + pseo.participant + \n    took.ACT + ACTCompositeScore.filled + ap.exam + sat.taken + \n    cte.achievement + total.cte.courses.taken + attended.ps\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1     27659      23736                          \n2     27655      23708  4    27.98 1.258e-05 ***\n3     27647      23371  8   337.48 < 2.2e-16 ***\n4     27646      23232  1   138.60 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - (model4_no_record$deviance / model4_no_record$null.deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0343946\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model4_no_record)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              GVIF Df GVIF^(1/(2*Df))\nGender                    1.044031  1        1.021778\nRaceEthnicity             1.874499  4        1.081710\neconomic.status           1.179806  1        1.086189\nSpecialEdStatus           1.547589  1        1.244021\nenglish.learner           1.790489  1        1.338092\nnon.english.home          1.965551  1        1.401981\nedr                       2.369452  2        1.240686\navg.wages.pct.state       2.157765  1        1.468933\navg.unemp.rate            1.579343  1        1.256719\npseo.participant          1.346814  1        1.160523\ntook.ACT                 14.213029  1        3.770017\nACTCompositeScore.filled 16.106717  1        4.013317\nap.exam                   1.292045  1        1.136682\nsat.taken                 1.046767  1        1.023116\ncte.achievement           1.994882  2        1.188446\ntotal.cte.courses.taken   2.080069  1        1.442244\nattended.ps               1.142294  1        1.068782\n```\n\n\n:::\n:::\n\n\n<br>\n\n## Summary: Multivariate Confirmation — Persistent No Minnesota Employment Record\n\n### Overview\n\nFit improved substantially and consistently across all four models (AIC: 23,756 → 23,736 → 23,415 → 23,278; pseudo-R²: 0.013 → 0.015 → 0.029 → 0.034), with the accomplishments block and the postsecondary-attendance block both producing the two largest single-block improvements of either sequence in this entire two-part analysis. This confirmatory analysis validated nearly every mechanism-specific prediction from the bivariate stage, with one clear exception and one genuinely new finding worth flagging.\n\n### The predictions that held up, several dramatically\n\n- **Non-English home** was the largest, most stable coefficient in every single model (OR ranging from 2.10 to 2.23 across all four blocks) — barely moving despite every control added. This is now the single most robust individual finding across this entire two-part analysis, confirming the bivariate result that non-English-home students are dramatically more likely to disappear from Minnesota's employment record specifically, with essentially no relationship to job instability.\n- **English learner status** was significant and harmful in every model (OR ≈ 1.25–1.27) — a complete, consistent mirror image of its null role in the non-sustained sequence, confirming EL's disadvantage operates specifically through the no-record mechanism.\n- **Gender** was not significant in any of the four models — the complete opposite of its strong, stable role in the non-sustained sequence, confirming this variable's disadvantage is entirely about job instability and has nothing to do with disappearing from the record.\n- **Asian/Pacific Islander and Hispanic** were both significant and harmful in every model (OR ranging roughly 1.29–1.38) — a clean reversal from their null role in the non-sustained sequence, directly confirming the bivariate prediction that these two groups' disadvantage concentrates in the no-record mechanism.\n- **American Indian** remained significant and harmful throughout, though it attenuated somewhat as HS characteristics and accomplishments were added (OR moving from 1.59 down to 1.38), confirming this group's disadvantage — unlike Asian/Pacific Islander and Hispanic — operates through both mechanisms.\n- **Economic status** was significant and *protective* in every model (OR ≈ 0.77–0.81) — a genuinely new finding not clearly anticipated by the bivariate cross-tab, worth reporting as its own result: economically disadvantaged non-completers appear less likely to disappear from Minnesota's employment record, plausibly reflecting fewer resources to relocate or disengage from the formal system, though this interpretation can't be confirmed directly from the data.\n- **`took.ACT`, `ACTCompositeScore.filled`, and especially `sat.taken`** all showed dramatically stronger relationships here than in the non-sustained sequence — `sat.taken` in particular flipped from completely null (p = 0.542) to strongly significant (OR ≈ 1.99–2.00) once no-record status was the outcome. This is the single cleanest confirmation of the entire mechanism-split hypothesis in this whole two-part analysis: SAT-taking's dramatic bivariate disadvantage — the largest raw gap found anywhere in the earlier work — is now confirmed, in a fully controlled multivariate model, to be almost entirely about disappearing from the employment record.\n- **`attended.ps`** was strongly protective (OR ≈ 0.61), and notably *stronger* here than in the non-sustained sequence (OR ≈ 0.67 there) — confirming and sharpening the bivariate finding that this variable's benefit splits nearly evenly between both mechanisms with a slight edge toward no-record status.\n- **`total.cte.courses.taken`** was significant here (unlike its null result in the non-sustained sequence), confirming the earlier three-way bivariate finding that its relationship with disconnection concentrates more in the no-record dimension. `cte.achievement`'s two categories remained protective in both sequences, confirming CTE's dual-mechanism role.\n\n### The one clear exception: Black graduates\n\nBlack graduates showed a significant, *protective* association in Model 1 (OR = 0.82) — a genuine reversal from the raw bivariate cross-tab, which showed a modestly elevated no-record rate for this group. This protective effect weakened to non-significance once HS characteristics were added in Model 2 and remained null through Models 3 and 4. This should be reported honestly as an unstable, largely null finding for this group and mechanism specifically — distinct from the group's strong, non-attenuating disadvantage in the non-sustained sequence, and distinct from the consistent, non-attenuating Black-White gap seen throughout the rest of this project's outcomes.\n\n### A finding that didn't survive full control: PSEO\n\nPSEO participation showed real, independent bivariate relationships with both non-sustained employment and no-record status when tested separately in the earlier three-way comparison. In this fully controlled multivariate model, however, `pseo.participant` was not significant in any of the four no-record models (nor in the parallel non-sustained sequence). This is worth reporting as exactly the kind of result this confirmatory analysis was designed to catch: a real bivariate relationship that doesn't survive once demographics, HS context, and other accomplishments are all controlled simultaneously.\n\n### A reproducible cross-sequence pattern worth highlighting\n\n`avg.unemp.rate` emerged as significant and protective once accomplishments were added in Model 3, then dropped back to non-significance once `attended.ps` was added in Model 4 — and this exact same pattern (emerge in Model 3, disappear in Model 4) also occurred independently in the parallel non-sustained sequence. This consistency across both otherwise-separate models adds confidence that it reflects a real, reproducible dynamic (unemployment's apparent effect substantially running through postsecondary attendance) rather than noise specific to either individual model.\n\n### Bottom line\n\nThis sequence delivered the strongest, cleanest confirmatory results of this entire two-part analysis. Nearly every demographic and accomplishment variable behaved exactly as the bivariate mechanism-split hypothesis predicted, with SAT-taking's complete reversal (null for non-sustained, strongly significant for no-record) standing out as the single most decisive piece of evidence for treating these as genuinely distinct mechanisms. The two departures from expectation — Black graduates' unstable, ultimately-null coefficient, and PSEO's failure to survive full multivariate control in either sequence — are both worth reporting explicitly as honest, informative null results rather than smoothed over.\n\n<br>\n\n# Multivariate Confirmation: Side-by-Side Comparison of the Two Disconnection Mechanisms\n\n## Variable Screening Table\n\n| Variable | Bivariate Expectation | Confirmed for Non-Sustained? | Confirmed for No-Record? |\n|------------------|------------------|------------------|------------------|\n| Gender | Non-sustained mechanism (primarily) | **Yes** (OR = 1.57, harmful for women) | **No** — null in every model (OR = 0.96, p = 0.298) |\n| RaceEthnicity | Both, subgroup-specific (AI/Black → both; Asian-PI/Hispanic → no-record only) | **Yes** for Black (OR = 1.91); American Indian unstable across blocks, ends null | **Yes** for American Indian (1.38), Asian/PI (1.38), Hispanic (1.30); **Black did not confirm** (null, after an unstable Model 1 reversal) |\n| economic.status | Non-sustained mechanism (primarily) | **Yes** (OR = 1.21, harmful) | **Yes, opposite direction** (OR = 0.77, protective) — a stronger, more consequential no-record finding than the bivariate stage suggested |\n| SpecialEdStatus | Both mechanisms | **Yes** (OR = 1.52, stable across all four models) | **Yes, but weaker and attenuating** (OR = 1.12, weakened at every block) |\n| english.learner | No-record mechanism (primarily) | **No** — null in every model | **Yes** (OR = 1.27, harmful) |\n| non.english.home | Both, opposite directions | **Yes** (OR = 0.65, protective) | **Yes — strongest predictor in either sequence** (OR = 2.10, harmful) |\n| edr | Different regional signature per mechanism | **Yes** — EDR 7E harmful (OR = 1.28), EDR 7W null | **Partial** — EDR 7W protective (OR = 0.74), EDR 7E only borderline (p = 0.089) |\n| avg.wages.pct.state | Weak, no-record-leaning | **No** (p = 0.878) | **No** (p = 0.236) |\n| avg.unemp.rate | No-record mechanism (stronger bivariate) | **No** in final model — significant in Model 3 (p = 0.006), attenuated once `attended.ps` entered | **No** in final model — identical pattern: significant in Model 3 (p \\< 0.001), attenuated once `attended.ps` entered |\n| pseo.participant | Both (weak, masked by combined measure) | **No** (p = 0.168) | **No** (p = 0.773) |\n| took.ACT | Both, no-record somewhat stronger | **Yes** (OR = 0.62, protective) | **Yes, considerably stronger** (OR = 0.32, protective) |\n| ACTCompositeScore.filled | No-record mechanism (bivariate was null for non-sustained, p = 0.393) | **Yes — emerged in multivariate** (OR = 1.025, harmful) despite a null bivariate relationship | **Yes** (OR = 1.045, harmful) |\n| ap.exam | No-record mechanism (weak, bivariate) | **No** — borderline only (p = 0.051) | **No — did not survive** (p = 0.417), despite a significant bivariate relationship |\n| sat.taken | No-record mechanism | **No** (p = 0.565) | **Yes, dramatically** (OR = 2.00, harmful) |\n| cte.achievement | Both, no-record somewhat stronger (bivariate) | **Yes**, both categories (OR = 0.85 / 0.90, protective) | **Yes**, both categories (OR = 0.81 / 0.84, protective) |\n| total.cte.courses.taken | Both, no-record notably stronger (bivariate) | **No** (p = 0.162) | **Yes** (OR = 0.96, protective) |\n| attended.ps | Both, roughly balanced (bivariate) | **Yes** (OR = 0.67, protective) | **Yes, slightly stronger** (OR = 0.61, protective) |\n\n## Description of the Analysis and Findings\n\nThis analysis tested, via parallel four-block logistic regression sequences (demographics → high school characteristics → high school accomplishments → postsecondary attempt), whether the two disconnection mechanisms identified in the bivariate work — persistent non-sustained employment and persistent no-record status — remain genuinely distinct once all variables are considered simultaneously. Both models were fit on the same analytic population (N = 27,669 non-college graduates, 2011–2019 cohorts), using the same 17-variable candidate set.\n\nThe results confirm the mechanism split clearly, though with more nuance than a simple \"two separate systems\" story would suggest. Of the 17 variables tested, 13 came back significant for at least one outcome, and — as in the bivariate stage — the pattern of *which* variable matters for *which* outcome is largely non-overlapping.\n\n**Non-English home is the single strongest and most consequential finding in this entire analysis.** It shows the largest coefficient found in either sequence (OR = 2.10 for no-record status) and a smaller but genuinely opposite-signed effect for non-sustained employment (OR = 0.65, protective). This is not a case of one mechanism mattering and the other being noise — both effects are large, stable, and move in opposite directions for the same population.\n\n**Gender and English learner status are the cleanest single-mechanism confirmations.** Gender is significant and harmful for non-sustained employment in every model and completely null for no-record status in every model. English learner status shows the exact mirror pattern. Neither variable shows any hint of \"leaking\" into the other mechanism, which is about as clean a confirmation as a variable screening exercise like this can produce.\n\n**Two variables — economic status and SpecialEdStatus — matter for both mechanisms, but in genuinely different ways.** Economic status is harmful for non-sustained employment and protective for no-record status — opposite directions for the same variable. SpecialEdStatus is harmful for both, but far more so for non-sustained employment, and its no-record effect weakens noticeably as accomplishments are added, while its non-sustained effect does not move at all.\n\n**CTE engagement is a genuine dual-mechanism finding, not a single-mechanism one as the earlier bivariate work might have suggested.** Both `cte.achievement` categories are significantly protective for *both* outcomes at similar magnitude. `total.cte.courses.taken`, however, resolves cleanly to a no-record-only finding — protective and significant there, but not significant for non-sustained employment. This distinction between the categorical and continuous CTE measures is worth carrying into any final report, since treating \"CTE\" as a single undifferentiated protective factor would obscure this split.\n\n**ACT composite score is the analysis's clearest example of a relationship that emerged only once other variables were controlled.** The bivariate analysis found this variable had no significant relationship with non-sustained employment at all (p = 0.393). Once demographics, HS context, and other accomplishments are held constant, it becomes clearly significant and harmful for non-sustained employment (OR = 1.025) — a textbook illustration of why this project's confirmatory stage exists. Combined with `took.ACT`'s protective effect (participation helps, but a higher score among test-takers is a modest risk factor), this \"engagement helps, performance hurts\" tension now replicates across both mechanisms.\n\n**Two bivariate findings did not survive full multivariate control.** `pseo.participant` showed real, independent relationships with both mechanisms at the bivariate stage but is not significant for either outcome in any of the eight models here. `ap.exam` showed a significant bivariate relationship with no-record status specifically, but that relationship disappears once the full variable set is included. Both are worth reporting explicitly as null results rather than smoothed over, since a confirmatory analysis that only reports what replicates isn't doing its job.\n\n**`attended.ps` and `avg.unemp.rate` both show a genuine cross-mechanism parallel worth flagging on its own.** `attended.ps` is strongly protective for both outcomes, with a slightly larger effect for no-record status — directly confirming the bivariate finding that this was the one variable operating through both channels roughly equally. `avg.unemp.rate`, meanwhile, becomes significant for *both* outcomes once accomplishments are added in Model 3, then loses significance for *both* once `attended.ps` enters in Model 4 — the identical pattern occurring independently in two separately-run models, which is a strong indication this reflects a real, reproducible dynamic (unemployment's apparent effect substantially running through postsecondary attendance) rather than coincidence in either individual sequence.\n\n## The Story the Data Tells\n\nComing into this analysis, the working assumption — built from the bivariate stage — was that \"disconnection\" among non-college graduates might really be two problems wearing one label. This multivariate confirmation supports that assumption, but with an important refinement: it isn't a clean, symmetric split where each variable belongs entirely to one mechanism or the other. A meaningful subset of variables — non-English home, economic status, SpecialEdStatus, `attended.ps`, `took.ACT`, and `ACTCompositeScore` — matter for *both* mechanisms, sometimes in the same direction and sometimes in opposite ones. The real finding isn't \"two separate systems with no overlap.\" It's that combining these two outcomes into a single measure would not just dilute several of these relationships — for non-English home and economic status specifically, it would actively cancel them out, since the same variable pushes in opposite directions depending on which mechanism is being measured.\n\nIf you are a non-completer from a non-English-speaking home, the data says both risks apply to you, but very unevenly: you face a dramatically elevated risk of disappearing from Minnesota's employment record, even as you face a somewhat *lower* risk of unstable-but-visible employment once you're in the labor market at all. If you have a documented special education status, both risks apply too, but the instability risk is considerably larger and more durable than the record-disappearance risk, which fades noticeably once your high school accomplishments are accounted for. If your risk factor is gender or English-learner status specifically, only one mechanism applies to you at all — the other shows no relationship whatsoever, in either direction.\n\nThis has a direct, practical implication for anyone designing an intervention around this population. Programs built around CTE course *completion levels* would show real, roughly equal protective results against both instability and disappearance. Programs built around CTE course *volume* specifically would show results only against disappearance from the record, with no measurable effect on job stability. Programs built around postsecondary attendance — even incomplete attendance — would help with both, more so than almost anything else tested. And any intervention built around a single, undifferentiated theory of \"workforce disconnection\" risks helping one population while doing essentially nothing for the other, or helping both populations through entirely different, non-substitutable mechanisms that need to be built and evaluated separately from the start.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}