<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Local Employment CART Analysis – Pathways taken after high school - Central</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="site_libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="site_libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="site_libs/selectize-0.12.0/selectize.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Central</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./employment.html">
 <span class="dropdown-text">Employment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways.html">
 <span class="dropdown-text">Post-secondary pathways</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_CART.html">
 <span class="dropdown-text">Local Employment CART Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rank-of-predictors" id="toc-rank-of-predictors" class="nav-link active" data-scroll-target="#rank-of-predictors">Rank of predictors</a>
  <ul class="collapse">
  <li><a href="#strong-predictors-of-regional-employment-and-disconnection" id="toc-strong-predictors-of-regional-employment-and-disconnection" class="nav-link" data-scroll-target="#strong-predictors-of-regional-employment-and-disconnection"><strong>1. Strong Predictors of Regional Employment and Disconnection</strong></a></li>
  <li><a href="#moderate-predictors-some-association-less-consistency" id="toc-moderate-predictors-some-association-less-consistency" class="nav-link" data-scroll-target="#moderate-predictors-some-association-less-consistency"><strong>2. Moderate Predictors — Some Association, Less Consistency</strong></a></li>
  <li><a href="#weak-or-inconsistent-predictors-candidates-for-dropping" id="toc-weak-or-inconsistent-predictors-candidates-for-dropping" class="nav-link" data-scroll-target="#weak-or-inconsistent-predictors-candidates-for-dropping"><strong>3. Weak or Inconsistent Predictors — Candidates for Dropping</strong></a></li>
  </ul></li>
  <li><a href="#employment-states" id="toc-employment-states" class="nav-link" data-scroll-target="#employment-states">Employment states</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#analysis---meaningful-employment-region-vs.-meaningful-employment-mn" id="toc-analysis---meaningful-employment-region-vs.-meaningful-employment-mn" class="nav-link" data-scroll-target="#analysis---meaningful-employment-region-vs.-meaningful-employment-mn">Analysis - Meaningful employment region vs.&nbsp;Meaningful employment MN</a>
  <ul class="collapse">
  <li><a href="#one-year-after-graduation" id="toc-one-year-after-graduation" class="nav-link" data-scroll-target="#one-year-after-graduation">One year after graduation</a>
  <ul class="collapse">
  <li><a href="#cart" id="toc-cart" class="nav-link" data-scroll-target="#cart">CART</a></li>
  <li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest">Random Forest</a></li>
  <li><a href="#key-predictors" id="toc-key-predictors" class="nav-link" data-scroll-target="#key-predictors"><strong>Key Predictors</strong></a></li>
  <li><a href="#moderate-predictors" id="toc-moderate-predictors" class="nav-link" data-scroll-target="#moderate-predictors"><strong>Moderate Predictors</strong></a></li>
  <li><a href="#notable-finding" id="toc-notable-finding" class="nav-link" data-scroll-target="#notable-finding"><strong>Notable Finding</strong></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Local Employment CART Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>master.original <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/SLEDS/Masters/After analysis/Master-after-ct.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"1"</span>, <span class="st">"Public, 4-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"4"</span>, <span class="st">"Public, 2-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"11"</span>, <span class="st">"Other"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">==</span> <span class="st">"PS grad EDR"</span>, <span class="st">"PS grad region"</span>, ps.grad.location))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps.within.first.year.hsgrad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="even">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="even">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="even">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.10</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">edr</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: left;">attended.ps.within.first.year.hsgrad</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5356619</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">EDR 5 - North Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 4-year</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad outside MN</td>
<td style="text-align: left;">Outside RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">Outside MN</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7.400000</td>
<td style="text-align: right;">35348.33</td>
<td style="text-align: right;">0.7577566</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
<tr class="even">
<td style="text-align: right;">1506121</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7E- East Central</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">44645.67</td>
<td style="text-align: right;">0.6740970</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1456500</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">EDR 5 - North Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5.700000</td>
<td style="text-align: right;">28114.67</td>
<td style="text-align: right;">0.6820086</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">10870895</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.300000</td>
<td style="text-align: right;">41847.67</td>
<td style="text-align: right;">0.8475591</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1877865</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.966667</td>
<td style="text-align: right;">45101.67</td>
<td style="text-align: right;">0.8861302</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">1323083</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Associate degree</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Inside and outside same RUCA</td>
<td style="text-align: left;">Inside and outside same EDR</td>
<td style="text-align: left;">Inside and outside same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">36660.00</td>
<td style="text-align: right;">0.8779366</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="rank-of-predictors" class="level1">
<h1>Rank of predictors</h1>
<p>Our analysis of local employment using cross-tabs, Kramer v-test, and ANOVA tables, we identified the following rank of importance regarding independent variable relationships to employment outcomes after high school;</p>
<section id="strong-predictors-of-regional-employment-and-disconnection" class="level2">
<h2 class="anchored" data-anchor-id="strong-predictors-of-regional-employment-and-disconnection"><strong>1. Strong Predictors of Regional Employment and Disconnection</strong></h2>
<p>These variables <strong>consistently show strong or moderate Cramer’s V values</strong> and <strong>clear differences in meaningful employment in the region</strong>, making them strong candidates for inclusion in modeling.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Key Insights</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ps.grad.location</td>
<td>Postsecondary</td>
<td>Strongest predictor of regional employment. Local grads more likely to stay.</td>
</tr>
<tr class="even">
<td>ps.grad</td>
<td>Postsecondary</td>
<td>Graduation itself reduces disconnection and improves employment outcomes.</td>
</tr>
<tr class="odd">
<td>highest.cred.level</td>
<td>Postsecondary</td>
<td>Clear stepwise value: higher credential = better outcomes.</td>
</tr>
<tr class="even">
<td>ps.grad.InstitutionSector</td>
<td>Postsecondary</td>
<td>2-year grads more likely to stay regional; 4-year grads more mobile.</td>
</tr>
<tr class="odd">
<td>economic.status</td>
<td>Demographic</td>
<td>Low-income students consistently more disconnected, especially early.</td>
</tr>
<tr class="even">
<td>RaceEthnicity</td>
<td>Demographic</td>
<td>Persistent racial gaps. Black, AI, Hispanic students more likely disconnected.</td>
</tr>
<tr class="odd">
<td>Dem_Desc</td>
<td>High School Characteristic</td>
<td>Rural grads more regionally tied; metro students more mobile/disconnected.</td>
</tr>
<tr class="even">
<td>ACTCompositeScore</td>
<td>Accomplishment (cont.)</td>
<td>Higher scores = more statewide mobility, but not always regional.</td>
</tr>
<tr class="odd">
<td>pseo.participant</td>
<td>Accomplishment</td>
<td>Linked to early employment or enrollment; reduces disconnection.</td>
</tr>
</tbody>
</table>
</section>
<section id="moderate-predictors-some-association-less-consistency" class="level2">
<h2 class="anchored" data-anchor-id="moderate-predictors-some-association-less-consistency"><strong>2. Moderate Predictors — Some Association, Less Consistency</strong></h2>
<p>These variables show <strong>moderate associations</strong> with outcomes. Their predictive value may depend on how they interact with other variables and could be useful in modeling, especially when looking for cumulative effects.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Key Insights</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SpecialEdStatus</td>
<td>Demographic</td>
<td>Somewhat lower employment, higher disconnection.</td>
</tr>
<tr class="even">
<td>Grad.year.covid</td>
<td>Demographic</td>
<td>Post-COVID grads slightly more disconnected early on.</td>
</tr>
<tr class="odd">
<td>cte.achievement</td>
<td>Accomplishment</td>
<td>Boosts regional employment, especially early.</td>
</tr>
<tr class="even">
<td>total.cte.courses.taken</td>
<td>Accomplishment (cont.)</td>
<td>More courses = slight boost in employment, especially regionally.</td>
</tr>
<tr class="odd">
<td>avg.unemp.rate</td>
<td>HS Characteristic (cont.)</td>
<td>Higher unemployment → more disconnection. Small effect.</td>
</tr>
<tr class="even">
<td>avg.wage.pct.state</td>
<td>HS Characteristic (cont.)</td>
<td>Higher wage counties → less disconnection. Small but consistent.</td>
</tr>
<tr class="odd">
<td>MCA Math &amp; Reading</td>
<td>Accomplishment (cont.)</td>
<td>Slight association with higher employment, mostly MN-wide.</td>
</tr>
</tbody>
</table>
</section>
<section id="weak-or-inconsistent-predictors-candidates-for-dropping" class="level2">
<h2 class="anchored" data-anchor-id="weak-or-inconsistent-predictors-candidates-for-dropping"><strong>3. Weak or Inconsistent Predictors — Candidates for Dropping</strong></h2>
<p>These variables showed <strong>very weak associations</strong> (low Cramer’s V, minimal group differences) and could be considered for <strong>dropping from modeling</strong>, unless interaction effects suggest otherwise.</p>
<table class="caption-top table">
<caption>We now want to build a model to see which variables are most predictive and resulting in clear guidance in how regional workforce organizations can influence workforce retainment/growth among their high school graduates. We will only use the strong and moderate predictors for this analysis. Here are the predictors I will use by the type of variable;</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>english.learner</td>
<td>Demographic</td>
<td>Minimal differences, especially when controlling for other variables.</td>
</tr>
<tr class="even">
<td>non.english.home</td>
<td>Demographic</td>
<td>Weak signal, may overlap with other demographics.</td>
</tr>
<tr class="odd">
<td>sat.taken</td>
<td>Accomplishment</td>
<td>Tiny population, not informative.</td>
</tr>
<tr class="even">
<td>took.ACT</td>
<td>Accomplishment</td>
<td>Near-universal participation, little discriminatory value.</td>
</tr>
<tr class="odd">
<td>ap.exam</td>
<td>Accomplishment</td>
<td>Modest effect, likely overlapping with other academic indicators.</td>
</tr>
</tbody>
</table>
<ul>
<li>Demographic
<ul>
<li>economic.status</li>
<li>RaceEthnicity</li>
<li>SpecialEdStatus</li>
</ul></li>
<li>High school characteristics
<ul>
<li>Dem_Desc</li>
<li>avg.unemp.rate</li>
<li>avg.wage.pct.state</li>
</ul></li>
<li>High school accomplishments
<ul>
<li>ACTCompositeScore</li>
<li>pseo.participant</li>
<li>cte.achievement</li>
<li>total.cte.courses.taken</li>
<li>MCA Math</li>
<li>MCA Reading</li>
<li>MCA Science</li>
</ul></li>
<li>Post-secondary
<ul>
<li>ps.grad.location</li>
<li>ps.grad</li>
<li>highest.cred.level</li>
<li>ps.grad.InstitutionSector</li>
</ul></li>
</ul>
<p><br></p>
</section>
</section>
<section id="employment-states" class="level1">
<h1>Employment states</h1>
<p>Currently, we have the following employment states for 1-, 5- and 10-years after graduating high school.</p>
<ul>
<li>Meaningful emp region: Individual has meaningful employment in the region of their high school.</li>
<li>Meaningful emp MN: Individual has meaningful employment in Minnesota, but not in the region of their high school.</li>
<li>Attending ps: Individual is attending post-secondary and does not have meaningful employment.</li>
<li>Not meaningful, not attending ps: Individual is working in Minnesota, but it is not meaningful and is not attending post-secondary.</li>
<li>No MN record, not attending ps: Individual does not have a MN employment record and is not attending post-secondary.</li>
</ul>
<p><br></p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>This study investigates the factors that influence whether high school graduates achieve <em>meaningful employment in the same region</em> as their high school at 1, 5, and 10 years after graduation. To isolate and understand the predictors of this specific outcome, the analysis compares it separately against three alternative post-graduation statuses:</p>
<ol type="1">
<li><strong>Meaningful employment in Minnesota, but outside the region</strong></li>
<li><strong>Not meaningful employment in Minnesota and not attending post-secondary</strong></li>
<li><strong>No Minnesota employment record and not attending post-secondary</strong></li>
</ol>
<p>Graduates classified as <em>Attending post-secondary</em> at the time of measurement are excluded from the analysis, as their employment pathways are distinct and not directly comparable to full-time workforce participation.</p>
<p>For each of the three alternative statuses and each time point (1, 5, and 10 years after graduation), a separate binary classification model is created, resulting in nine total models. This binary framework ensures that “Meaningful employment in the region” is always the positive class, allowing a direct focus on distinguishing regional retention from each alternative pathway.</p>
<p>The modeling process follows these steps:</p>
<ol type="1">
<li><p><strong>Data Preparation</strong> All predictor variables include demographic characteristics, high school achievement indicators, and postsecondary attainment measures. Records with missing target outcome categories are excluded. For each binary comparison, the dataset is filtered to only include the two relevant classes, with “Meaningful employment in the region” coded as the positive class.</p></li>
<li><p><strong>Training and Test Split</strong> For each binary dataset, the data is randomly split into a training set (70–80%) and a testing set (20–30%) to ensure that model evaluation is conducted on previously unseen data.</p></li>
<li><p><strong>Preprocessing</strong> Preprocessing steps are applied to the training data using a <code>recipe</code> in the tidymodels framework:</p>
<ul>
<li>Remove near-zero variance predictors.</li>
<li>Impute missing values for categorical predictors with the mode and numeric predictors with the median.</li>
<li>Encode categorical predictors as dummy variables.</li>
<li>Upsample the minority class to balance class representation.</li>
</ul></li>
<li><p><strong>Modeling</strong></p>
<p>Two machine learning methods are applied to each binary comparison:</p>
<ul>
<li><strong>CART (Classification and Regression Tree)</strong> for interpretability and identification of clear decision rules.</li>
<li><strong>Random Forest</strong> for potentially higher predictive performance and more robust variable importance estimation.</li>
</ul></li>
<li><p><strong>Evaluation</strong> Models are evaluated on the testing set using accuracy, Cohen’s kappa, balanced accuracy, sensitivity, and specificity. Variable importance is examined to identify the most influential predictors for each comparison and time point.</p></li>
</ol>
<p>This approach emphasizes clarity in interpretation by focusing each model on a single binary distinction, making it easier to identify which factors most strongly differentiate graduates who achieve meaningful regional employment from those on alternative pathways.</p>
<p>Here is the final dataset I will be using.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> master.original <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(economic.status, RaceEthnicity, SpecialEdStatus, Dem_Desc, avg.unemp.rate, avg.wages.pct.state, ACTCompositeScore, pseo.participant, cte.achievement, total.cte.courses.taken, MCA.M, MCA.R, MCA.S, ps.grad.location, ps.grad, highest.cred.level, ps.grad.InstitutionSector, grad.year<span class="fl">.1</span>, grad.year<span class="fl">.5</span>, grad.year<span class="fl">.10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="analysis---meaningful-employment-region-vs.-meaningful-employment-mn" class="level1">
<h1>Analysis - Meaningful employment region vs.&nbsp;Meaningful employment MN</h1>
<section id="one-year-after-graduation" class="level2">
<h2 class="anchored" data-anchor-id="one-year-after-graduation">One year after graduation</h2>
<section id="cart" class="level3">
<h3 class="anchored" data-anchor-id="cart">CART</h3>
<p>First I’m going to filter out the data so only individuals that had meaningful employment in the region or Minnesota are in the dataset.</p>
<p>The table below shows that 64% of the individuals have meaningful employment in their high school region compared to 36% that have meaningful employment in Minnesota, but not their region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>meaningful.emp.mn.grad.year<span class="fl">.1</span> <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>grad.year<span class="fl">.5</span>, <span class="sc">-</span>grad.year<span class="fl">.10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(grad.year<span class="fl">.1</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Meaningful emp region"</span>, <span class="st">"Meaningful emp MN"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grad.year.1 =</span> <span class="fu">as.factor</span>(grad.year<span class="fl">.1</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(meaningful.emp.mn.grad.year<span class="fl">.1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "26,522"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> meaningful.emp.mn.grad.year<span class="fl">.1</span> <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(grad.year<span class="fl">.1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-b600bc8c4982aeb4bc5b" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-b600bc8c4982aeb4bc5b">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Meaningful emp MN&quot;,&quot;Meaningful emp region&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"9653\" data-max=\"16869\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.363961993816454\" data-max=\"0.636038006183546\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Meaningful emp MN","Meaningful emp region"],[9653,16869],[0.3639619938164543,0.6360380061835458]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>grad.year.1<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"grad.year.1","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model" class="level4">
<h4 class="anchored" data-anchor-id="base-model">Base Model</h4>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(meaningful.emp.mn.grad.year<span class="fl">.1</span>), <span class="fu">nrow</span>(meaningful.emp.mn.grad.year<span class="fl">.1</span>) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> meaningful.emp.mn.grad.year<span class="fl">.1</span>[sample_ind,]</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> meaningful.emp.mn.grad.year<span class="fl">.1</span>[<span class="sc">-</span>sample_ind,]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>meaningful.emp.mn.grad.year.<span class="fl">1.</span>model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(grad.year<span class="fl">.1</span> <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.1 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore         avg.unemp.rate           
 [3] avg.wages.pct.state       cte.achievement          
 [5] Dem_Desc                  economic.status          
 [7] highest.cred.level        MCA.M                    
 [9] MCA.R                     MCA.S                    
[11] ps.grad.InstitutionSector ps.grad.location         
[13] pseo.participant          RaceEthnicity            
[15] SpecialEdStatus           total.cte.courses.taken  

Root node error: 6744/18565 = 0.36326

n= 18565 

           CP nsplit rel error  xerror      xstd
1  1.4087e-02      0   1.00000 1.00000 0.0097167
2  4.7944e-03      2   0.97183 0.97183 0.0096556
3  4.1518e-03      5   0.95744 0.97375 0.0096599
4  2.9656e-03      6   0.95329 0.96204 0.0096332
5  2.4466e-03      8   0.94736 0.96085 0.0096304
6  1.7794e-03     10   0.94247 0.96041 0.0096294
7  1.4828e-03     11   0.94069 0.95922 0.0096266
8  1.3345e-03     14   0.93550 0.96278 0.0096349
9  9.3911e-04     16   0.93283 0.96174 0.0096325
10 8.8968e-04     19   0.93001 0.96812 0.0096472
11 8.4025e-04     20   0.92912 0.96975 0.0096509
12 8.1554e-04     24   0.92556 0.97109 0.0096539
13 7.9083e-04     34   0.91578 0.97583 0.0096646
14 7.7847e-04     37   0.91340 0.97435 0.0096612
15 7.4140e-04     51   0.89961 0.97420 0.0096609
16 7.0433e-04     55   0.89665 0.97464 0.0096619
17 6.6726e-04     64   0.88953 0.97257 0.0096572
18 5.9312e-04     72   0.88419 0.97494 0.0096626
19 5.4369e-04    104   0.86343 0.97583 0.0096646
20 5.3381e-04    129   0.84653 0.97672 0.0096665
21 5.1898e-04    135   0.84297 0.97805 0.0096695
22 4.9427e-04    137   0.84193 0.97865 0.0096708
23 4.4484e-04    147   0.83674 0.98324 0.0096809
24 4.0777e-04    196   0.81435 0.98873 0.0096928
25 3.9541e-04    207   0.80961 0.99303 0.0097021
26 3.8129e-04    215   0.80620 0.99333 0.0097027
27 3.7070e-04    223   0.80308 0.99007 0.0096957
28 3.4599e-04    265   0.78648 0.99125 0.0096983
29 2.9656e-04    275   0.78277 1.00341 0.0097238
30 2.5949e-04    395   0.74407 1.01023 0.0097378
31 2.4713e-04    401   0.74244 1.01394 0.0097452
32 2.2242e-04    435   0.73339 1.02135 0.0097599
33 2.1418e-04    472   0.72420 1.02595 0.0097689
34 1.9771e-04    490   0.71856 1.02728 0.0097715
35 1.8535e-04    507   0.71471 1.03262 0.0097816
36 1.7299e-04    511   0.71397 1.03396 0.0097842
37 1.4828e-04    517   0.71293 1.03811 0.0097919
38 1.2710e-04    636   0.69469 1.04167 0.0097985
39 1.1862e-04    643   0.69380 1.04671 0.0098077
40 1.1121e-04    665   0.68846 1.04953 0.0098128
41 1.0591e-04    709   0.68238 1.05056 0.0098147
42 9.8853e-05    716   0.68164 1.05116 0.0098157
43 8.8968e-05    741   0.67838 1.05086 0.0098152
44 7.4140e-05    749   0.67719 1.05694 0.0098260
45 6.1783e-05    799   0.67349 1.05842 0.0098285
46 5.9312e-05    811   0.67275 1.06421 0.0098385
47 4.9427e-05    826   0.67186 1.07192 0.0098515
48 4.2366e-05    850   0.67067 1.07236 0.0098523
49 3.7070e-05    857   0.67037 1.07503 0.0098567
50 2.9656e-05    865   0.67008 1.07503 0.0098567
51 2.4713e-05    870   0.66993 1.07829 0.0098620
52 1.8535e-05    876   0.66978 1.07903 0.0098632
53 0.0000e+00    884   0.66963 1.07903 0.0098632</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The resulting model produced a VERY complex tree with too many nodes that it isn’t interpretable. The xerror bottoms out at 11 splits, so there is definitely room to simplify.</p>
<p>Next, the accuracy of the model is computed and stored in a variable base_accuracy so we can compare it to our pruned trees later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>base_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(base_accuracy, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "61.4%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a confusion matrix</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cm <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">factor</span>(test<span class="sc">$</span>pred),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">reference =</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">"Meaningful emp region"</span>  <span class="co"># whichever class you want as "positive"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>cm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

                       Reference
Prediction              Meaningful emp MN Meaningful emp region
  Meaningful emp MN                  1142                  1304
  Meaningful emp region              1767                  3744
                                               
               Accuracy : 0.6141               
                 95% CI : (0.6033, 0.6248)     
    No Information Rate : 0.6344               
    P-Value [Acc &gt; NIR] : 0.9999               
                                               
                  Kappa : 0.1389               
                                               
 Mcnemar's Test P-Value : &lt;2e-16               
                                               
            Sensitivity : 0.7417               
            Specificity : 0.3926               
         Pos Pred Value : 0.6794               
         Neg Pred Value : 0.4669               
             Prevalence : 0.6344               
         Detection Rate : 0.4705               
   Detection Prevalence : 0.6926               
      Balanced Accuracy : 0.5671               
                                               
       'Positive' Class : Meaningful emp region
                                               </code></pre>
</div>
</div>
<p>The resulting test for accuracy gives me a 61.4%.</p>
<p><strong>Overall Performance</strong></p>
<ul>
<li><strong>Accuracy (61.4%)</strong> – The model is correct in a little over six out of ten predictions, which is worse than simply guessing the majority class (“Meaningful emp region”, 63.4%). This is why the <strong>p-value for Acc &gt; NIR is ~1</strong>, meaning there’s no statistically significant improvement over the naive baseline.</li>
<li><strong>Kappa (0.139)</strong> – Very low agreement beyond chance; the model isn’t capturing much true discriminatory power between the two groups.</li>
</ul>
<p><strong>Class-Level Performance</strong> (with “Meaningful emp region” as the <em>positive</em> class):</p>
<ul>
<li><strong>Sensitivity (74.2%)</strong> – The model is fairly good at identifying actual “Meaningful emp region” cases.</li>
<li><strong>Specificity (39.3%)</strong> – The model is poor at correctly identifying “Meaningful emp MN” cases; it confuses many of them for “Meaningful emp region.”</li>
<li><strong>Positive Predictive Value (68.0%)</strong> – When the model predicts “Meaningful emp region,” it’s correct about two-thirds of the time.</li>
<li><strong>Negative Predictive Value (46.7%)</strong> – When the model predicts “Meaningful emp MN,” it’s correct less than half the time.</li>
</ul>
<p><strong>Balanced Accuracy (56.7%)</strong></p>
<ul>
<li>This average of sensitivity and specificity shows the model is performing only slightly better than random guessing for this binary classification.</li>
</ul>
<p><strong>Interpretation</strong> Your CART model in this configuration is <strong>over-predicting “Meaningful emp region”</strong> and struggling to correctly identify “Meaningful emp MN” cases. This is reflected in the large difference between sensitivity (~74%) and specificity (~39%).<br>
</p>
<p>In practical terms, this means your model catches most of the “Meaningful emp region” group, but at the cost of misclassifying a lot of “Meaningful emp MN” students.</p>
<p><br></p>
</section>
<section id="pre-pruning" class="level4">
<h4 class="anchored" data-anchor-id="pre-pruning">Pre-pruning</h4>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 6</li>
<li>minsplit: 5% of nrow(train) which is 928.25.</li>
<li>minbucket: round(minsplit / 3) which is 309</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">6</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> .<span class="dv">05</span><span class="sc">*</span><span class="fu">nrow</span>(train)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>meaningful.emp.mn.grad.year.<span class="fl">1.</span>model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(grad.year<span class="fl">.1</span> <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "64.5%"</code></pre>
</div>
</div>
<p>Pre-pruning shows an slight increase in accuracy compared to the base model. But not much. Here is the full confusion Matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cm <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">factor</span>(test<span class="sc">$</span>pred, <span class="at">levels =</span> <span class="fu">levels</span>(test<span class="sc">$</span>grad.year<span class="fl">.1</span>)),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">reference =</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">"Meaningful emp region"</span>  <span class="co"># whichever class you want as "positive"</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>cm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

                       Reference
Prediction              Meaningful emp MN Meaningful emp region
  Meaningful emp MN                   762                   679
  Meaningful emp region              2147                  4369
                                               
               Accuracy : 0.6448               
                 95% CI : (0.6342, 0.6554)     
    No Information Rate : 0.6344               
    P-Value [Acc &gt; NIR] : 0.02722              
                                               
                  Kappa : 0.1427               
                                               
 Mcnemar's Test P-Value : &lt; 2e-16              
                                               
            Sensitivity : 0.8655               
            Specificity : 0.2619               
         Pos Pred Value : 0.6705               
         Neg Pred Value : 0.5288               
             Prevalence : 0.6344               
         Detection Rate : 0.5491               
   Detection Prevalence : 0.8189               
      Balanced Accuracy : 0.5637               
                                               
       'Positive' Class : Meaningful emp region
                                               </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ul>
<li>Pre-pruning <strong>simplified the tree</strong>, which increased its ability to generalize — you got a noticeable accuracy bump.</li>
<li>The model is <strong>biased toward predicting “Meaningful emp region”</strong>, which is why sensitivity is high but specificity is low.</li>
<li>If your main interest is <em>catching</em> “Meaningful emp region” cases and you don’t mind some false alarms, this is okay.</li>
<li>If you need better balance between the two classes, you might need to tweak the pruning parameters or use a more balanced model (Random Forest, or adjusting class weights).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_local_employment_CART_files/figure-html/pre pruning plot meaningful emp MN grad year 1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = grad.year.1 ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] avg.wages.pct.state Dem_Desc            highest.cred.level 
[4] ps.grad.location   

Root node error: 6744/18565 = 0.36326

n= 18565 

         CP nsplit rel error  xerror      xstd
1 0.0140866      0   1.00000 1.00000 0.0097167
2 0.0099348      1   0.98591 1.00148 0.0097198
3 0.0068209      2   0.97598 0.98280 0.0096800
4 0.0063019      3   0.96916 0.98013 0.0096741
5 0.0023725      5   0.95655 0.96782 0.0096465
6 0.0000000      6   0.95418 0.96738 0.0096455</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="post-pruning" class="level4">
<h4 class="anchored" data-anchor-id="post-pruning">Post-pruning</h4>
<p>Next, let’s try postpruning. The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> meaningful.emp.mn.grad.year.<span class="fl">1.</span>model<span class="sc">$</span>cptable</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> meaningful.emp.mn.grad.year.<span class="fl">1.</span>model<span class="sc">$</span>cptable[<span class="fu">which.min</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>meaningful.emp.mn.grad.year.<span class="fl">1.</span>model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model, <span class="at">cp =</span> optimal_cp)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(meaningful.emp.mn.grad.year.<span class="fl">1.</span>model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "64.5%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cm <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> <span class="fu">factor</span>(test<span class="sc">$</span>pred, <span class="at">levels =</span> <span class="fu">levels</span>(test<span class="sc">$</span>grad.year<span class="fl">.1</span>)),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">reference =</span> test<span class="sc">$</span>grad.year<span class="fl">.1</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">"Meaningful emp region"</span>  <span class="co"># whichever class you want as "positive"</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>cm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

                       Reference
Prediction              Meaningful emp MN Meaningful emp region
  Meaningful emp MN                   660                   579
  Meaningful emp region              2249                  4469
                                               
               Accuracy : 0.6446               
                 95% CI : (0.634, 0.6551)      
    No Information Rate : 0.6344               
    P-Value [Acc &gt; NIR] : 0.03029              
                                               
                  Kappa : 0.1277               
                                               
 Mcnemar's Test P-Value : &lt; 2e-16              
                                               
            Sensitivity : 0.8853               
            Specificity : 0.2269               
         Pos Pred Value : 0.6652               
         Neg Pred Value : 0.5327               
             Prevalence : 0.6344               
         Detection Rate : 0.5616               
   Detection Prevalence : 0.8443               
      Balanced Accuracy : 0.5561               
                                               
       'Positive' Class : Meaningful emp region
                                               </code></pre>
</div>
</div>
<p>Interpretation</p>
<ul>
<li><strong>Accuracy 64.5%</strong> (vs NIR 63.4%): only a <em>small</em> gain over always predicting the majority (“Meaningful emp region”).</li>
<li><strong>Kappa 0.13</strong>: very low agreement beyond chance → limited discriminatory power.</li>
<li><strong>Sensitivity 88.5%</strong> (for <em>Meaningful emp region</em>): you catch most region cases.</li>
<li><strong>Specificity 22.7%</strong>: you miss a lot of <em>Meaningful emp MN</em> (many false positives for region).</li>
<li><strong>Balanced accuracy 55.6%</strong>: only slightly better than coin‑flip once we account for both classes equally.</li>
</ul>
<p>The pruned tree is <strong>biased toward predicting “Meaningful emp region.”</strong> It’s good at <em>finding</em> region cases, but it calls too many “Other MN” cases as region. Pruning didn’t fix that trade‑off; it just made the tree smaller.</p>
<p>Because my <strong>base</strong>, <strong>pre-pruned</strong>, and <strong>post-pruned</strong> CART models all suffer from:</p>
<ul>
<li><strong>Low specificity</strong> for “Meaningful emp MN” (lots of false positives for “Region”)</li>
<li><strong>Low Kappa</strong> (poor agreement beyond chance)</li>
<li><strong>Balanced accuracy barely above 50%</strong></li>
</ul>
<p>…any variable importance rankings they produce will be unreliable for <strong>identifying strong predictors</strong> of <em>meaningful employment in the region</em>.</p>
<p>In other words:</p>
<ul>
<li>The tree is <strong>biased toward predicting “Region”</strong>, so the splits are mostly optimized for catching Region cases rather than separating Region from MN employment accurately.</li>
<li>That bias skews which variables get selected and how their importance is scored.</li>
<li>You could end up over- or under-estimating the influence of certain predictors simply because the model struggles with the minority class.</li>
</ul>
<p>To get <em>trustworthy</em> importance for this question, I’ll want a method that:</p>
<ol type="1">
<li>Handles class imbalance better (e.g., class weights, upsampling, balanced RF).</li>
<li>Achieves <strong>balanced accuracy ≥ ~0.65–0.70</strong> so it’s actually distinguishing the classes in a meaningful way.</li>
</ol>
<p>Once that’s in place, our variable importance will reflect <em>both</em> sides of the classification instead of just the majority class.</p>
<p><br></p>
</section>
</section>
<section id="random-forest" class="level3">
<h3 class="anchored" data-anchor-id="random-forest">Random Forest</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 1. Filter to only the two classes ---</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>levels_to_use <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Meaningful emp region"</span>, <span class="st">"Meaningful emp MN"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>train_rf <span class="ot">&lt;-</span> <span class="fu">subset</span>(train, grad.year<span class="fl">.1</span> <span class="sc">%in%</span> levels_to_use)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>test_rf  <span class="ot">&lt;-</span> <span class="fu">subset</span>(test, grad.year<span class="fl">.1</span> <span class="sc">%in%</span> levels_to_use)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop unused factor levels</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>train_rf<span class="sc">$</span>grad.year<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(train_rf<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>test_rf<span class="sc">$</span>grad.year<span class="fl">.1</span>  <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(test_rf<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 2. Compute class weights (inverse of frequency) ---</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>class_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(train_rf<span class="sc">$</span>grad.year<span class="fl">.1</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>class_weights <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">sum</span>(class_counts) <span class="sc">/</span> (<span class="fu">length</span>(class_counts) <span class="sc">*</span> class_counts))</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(class_weights) <span class="ot">&lt;-</span> <span class="fu">names</span>(class_counts)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 3. Train Random Forest with balanced weights ---</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> <span class="fu">ranger</span>(</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  grad.year<span class="fl">.1</span> <span class="sc">~</span> .,</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_rf,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">num.trees =</span> <span class="dv">500</span>,</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">mtry =</span> <span class="fu">floor</span>(<span class="fu">sqrt</span>(<span class="fu">ncol</span>(train_rf) <span class="sc">-</span> <span class="dv">1</span>)),</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">importance =</span> <span class="st">"impurity"</span>,       <span class="co"># or "permutation" for more reliable scores</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability =</span> <span class="cn">FALSE</span>,</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">class.weights =</span> class_weights,</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">123</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 4. Predict on the test set ---</span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>rf_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_model, <span class="at">data =</span> test_rf)<span class="sc">$</span>predictions</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 5. Confusion matrix &amp; metrics ---</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>cm <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(rf_pred, <span class="at">levels =</span> <span class="fu">levels</span>(test_rf<span class="sc">$</span>grad.year<span class="fl">.1</span>)),</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>  test_rf<span class="sc">$</span>grad.year<span class="fl">.1</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

                       Reference
Prediction              Meaningful emp MN Meaningful emp region
  Meaningful emp MN                  1243                  1243
  Meaningful emp region              1666                  3805
                                           
               Accuracy : 0.6344           
                 95% CI : (0.6237, 0.645)  
    No Information Rate : 0.6344           
    P-Value [Acc &gt; NIR] : 0.5051           
                                           
                  Kappa : 0.1868           
                                           
 Mcnemar's Test P-Value : 5.108e-15        
                                           
            Sensitivity : 0.4273           
            Specificity : 0.7538           
         Pos Pred Value : 0.5000           
         Neg Pred Value : 0.6955           
             Prevalence : 0.3656           
         Detection Rate : 0.1562           
   Detection Prevalence : 0.3124           
      Balanced Accuracy : 0.5905           
                                           
       'Positive' Class : Meaningful emp MN
                                           </code></pre>
</div>
</div>
<ul>
<li><strong>Overall accuracy:</strong> 63.5% — almost identical to your baseline proportion (NIR = 63.4%), meaning the model is not giving a major boost in overall correct classification.</li>
<li><strong>Kappa:</strong> 0.189 — very low, suggesting weak agreement beyond chance.</li>
<li><strong>Sensitivity (Meaningful emp MN):</strong> 42.9% — the model catches fewer than half of the people who actually have meaningful employment in MN.</li>
<li><strong>Specificity (Meaningful emp MN):</strong> 75.4% — better at correctly identifying those <em>not</em> in MN (i.e., in Region).</li>
<li><strong>Balanced Accuracy:</strong> 59.2% — better than random guessing (50%), but not particularly strong.</li>
</ul>
<p><strong>Interpretation:</strong> Your Random Forest is biased toward predicting “Meaningful emp region” — that’s why Sensitivity for MN is low, but Specificity is higher. Even with balanced class weights, the model still struggles to find a good set of predictors for MN outcomes.</p>
<p>The <strong>Variable Importance</strong> plot from this RF will still be useful for identifying the strongest predictors, but we have to keep in mind that the predictive performance is modest, so the ranking is informative but not definitive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 6. Variable importance ---</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>var_imp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">names</span>(rf_model<span class="sc">$</span>variable.importance),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Importance =</span> rf_model<span class="sc">$</span>variable.importance</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>var_imp <span class="ot">&lt;-</span> var_imp[<span class="fu">order</span>(<span class="sc">-</span>var_imp<span class="sc">$</span>Importance), ]</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(var_imp, <span class="dv">20</span>)  <span class="co"># Top 20 important variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           Variable Importance
avg.wages.pct.state             avg.wages.pct.state 1223.35228
total.cte.courses.taken     total.cte.courses.taken 1172.92601
avg.unemp.rate                       avg.unemp.rate  993.75969
MCA.M                                         MCA.M  488.64534
MCA.R                                         MCA.R  444.87403
cte.achievement                     cte.achievement  331.74141
Dem_Desc                                   Dem_Desc  235.81489
MCA.S                                         MCA.S  230.25457
RaceEthnicity                         RaceEthnicity  229.84913
economic.status                     economic.status  223.53056
highest.cred.level               highest.cred.level  206.76485
ps.grad.InstitutionSector ps.grad.InstitutionSector  205.92367
ps.grad.location                   ps.grad.location  198.85456
SpecialEdStatus                     SpecialEdStatus  157.51401
pseo.participant                   pseo.participant   61.27701
ps.grad                                     ps.grad   53.17420
ACTCompositeScore                 ACTCompositeScore -110.92504</code></pre>
</div>
</div>
</section>
<section id="key-predictors" class="level3">
<h3 class="anchored" data-anchor-id="key-predictors"><strong>Key Predictors</strong></h3>
<ol type="1">
<li><strong>avg.wages.pct.state</strong> (Highest importance)
<ul>
<li>Indicates that local wage competitiveness compared to the state average is the strongest differentiator between working in MN vs in the region.</li>
<li>Higher relative wages may be drawing individuals into regional employment or retaining them locally.</li>
</ul></li>
<li><strong>total.cte.courses.taken</strong>
<ul>
<li>Suggests that the number of career and technical education (CTE) courses taken in high school plays a major role in predicting where graduates end up employed.</li>
<li>This might reflect how CTE programs link to local/regional job pipelines.</li>
</ul></li>
<li><strong>avg.unemp.rate</strong>
<ul>
<li>Regional unemployment levels are highly predictive, likely capturing labor market pull/push effects.</li>
</ul></li>
<li><strong>MCA Math &amp; Reading scores (MCA.M, MCA.R)</strong>
<ul>
<li>Higher academic performance may influence mobility and employability, indirectly affecting job location.</li>
</ul></li>
<li><strong>cte.achievement</strong>
<ul>
<li>Not just the number of CTE courses, but completing recognized CTE achievements is important.</li>
</ul></li>
</ol>
</section>
<section id="moderate-predictors" class="level3">
<h3 class="anchored" data-anchor-id="moderate-predictors"><strong>Moderate Predictors</strong></h3>
<ul>
<li><strong>Demographic and background factors</strong>: <code>Dem_Desc</code>, <code>RaceEthnicity</code>, <code>economic.status</code>
<ul>
<li>These appear in the middle of the ranking, suggesting socioeconomic and demographic patterns in mobility or job placement.</li>
</ul></li>
<li><strong>Postsecondary factors</strong>: <code>highest.cred.level</code>, <code>ps.grad.InstitutionSector</code>, <code>ps.grad.location</code>
<ul>
<li>These indicate that where someone graduates from and at what credential level can matter, but less than the core labor market and high school preparation variables.</li>
</ul></li>
</ul>
</section>
<section id="notable-finding" class="level3">
<h3 class="anchored" data-anchor-id="notable-finding"><strong>Notable Finding</strong></h3>
<ul>
<li><p><strong>ACTCompositeScore</strong> has a <strong>negative importance</strong> in your model output.</p>
<ul>
<li><p>This can happen if the variable adds noise when controlling for others, or if it is inversely correlated with the target after accounting for stronger predictors.</p></li>
<li><p>In practice, this means ACT score is not helpful in distinguishing between MN vs regional meaningful employment here.</p></li>
</ul></li>
</ul>
<p><strong>Bottom line:</strong><br>
</p>
<p>Your model suggests that <strong>local labor market conditions</strong> (wages, unemployment), <strong>high school CTE engagement</strong>, and <strong>academic performance in MCA tests</strong> are the strongest drivers of whether someone has meaningful employment in the region vs Minnesota overall. Demographic and postsecondary factors still matter, but to a lesser extent.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>