<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Post-secondary Paths CART – Pathways taken after high school - Central</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="site_libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="site_libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="site_libs/selectize-0.12.0/selectize.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Central</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./employment.html">
 <span class="dropdown-text">Employment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways.html">
 <span class="dropdown-text">Post-secondary pathways</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_CART.html">
 <span class="dropdown-text">Local Employment CART Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_paths_CART.html">
 <span class="dropdown-text">Post-secondary Paths CART Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#post-secondary-paths" id="toc-post-secondary-paths" class="nav-link active" data-scroll-target="#post-secondary-paths">Post-secondary Paths</a>
  <ul class="collapse">
  <li><a href="#postsecondary-graduation-location-ps.grad.location" id="toc-postsecondary-graduation-location-ps.grad.location" class="nav-link" data-scroll-target="#postsecondary-graduation-location-ps.grad.location"><strong>Postsecondary Graduation Location (<code>ps.grad.location</code>)</strong></a></li>
  <li><a href="#highest-credential-level-highest.cred.level" id="toc-highest-credential-level-highest.cred.level" class="nav-link" data-scroll-target="#highest-credential-level-highest.cred.level"><strong>Highest Credential Level (<code>highest.cred.level</code>)</strong></a></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#analysis---post-secondary-location" id="toc-analysis---post-secondary-location" class="nav-link" data-scroll-target="#analysis---post-secondary-location">Analysis - Post secondary location</a>
  <ul class="collapse">
  <li><a href="#base-model" id="toc-base-model" class="nav-link" data-scroll-target="#base-model">Base Model</a></li>
  <li><a href="#pre-pruning" id="toc-pre-pruning" class="nav-link" data-scroll-target="#pre-pruning">Pre-pruning</a></li>
  <li><a href="#post-pruning" id="toc-post-pruning" class="nav-link" data-scroll-target="#post-pruning">Post-pruning</a></li>
  <li><a href="#main-takeaway" id="toc-main-takeaway" class="nav-link" data-scroll-target="#main-takeaway"><strong>Main takeaway</strong></a></li>
  </ul></li>
  <li><a href="#analysis---highest-credential-earned" id="toc-analysis---highest-credential-earned" class="nav-link" data-scroll-target="#analysis---highest-credential-earned">Analysis - Highest Credential Earned</a>
  <ul class="collapse">
  <li><a href="#base-model-1" id="toc-base-model-1" class="nav-link" data-scroll-target="#base-model-1">Base Model</a></li>
  <li><a href="#pre-pruning-1" id="toc-pre-pruning-1" class="nav-link" data-scroll-target="#pre-pruning-1">Pre-pruning</a></li>
  <li><a href="#post-pruning-1" id="toc-post-pruning-1" class="nav-link" data-scroll-target="#post-pruning-1">Post-pruning</a></li>
  <li><a href="#main-takeaway-1" id="toc-main-takeaway-1" class="nav-link" data-scroll-target="#main-takeaway-1"><strong>Main takeaway</strong></a></li>
  </ul></li>
  <li><a href="#comparison" id="toc-comparison" class="nav-link" data-scroll-target="#comparison">Comparison</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Post-secondary Paths CART</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>master.original <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/SLEDS/Masters/After analysis/Master-after-ct.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"1"</span>, <span class="st">"Public, 4-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"4"</span>, <span class="st">"Public, 2-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"11"</span>, <span class="st">"Other"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">==</span> <span class="st">"PS grad EDR"</span>, <span class="st">"PS grad region"</span>, ps.grad.location),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level =</span> <span class="fu">as.factor</span>(highest.cred.level),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">as.factor</span>(ps.grad.location))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps.within.first.year.hsgrad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="even">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="even">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="even">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.10</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">edr</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: left;">attended.ps.within.first.year.hsgrad</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5356619</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">EDR 5 - North Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 4-year</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad outside MN</td>
<td style="text-align: left;">Outside RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">Outside MN</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7.400000</td>
<td style="text-align: right;">35348.33</td>
<td style="text-align: right;">0.7577566</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
<tr class="even">
<td style="text-align: right;">1506121</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7E- East Central</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">44645.67</td>
<td style="text-align: right;">0.6740970</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1456500</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">EDR 5 - North Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5.700000</td>
<td style="text-align: right;">28114.67</td>
<td style="text-align: right;">0.6820086</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">10870895</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.300000</td>
<td style="text-align: right;">41847.67</td>
<td style="text-align: right;">0.8475591</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1877865</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.966667</td>
<td style="text-align: right;">45101.67</td>
<td style="text-align: right;">0.8861302</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">1323083</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Associate degree</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Inside and outside same RUCA</td>
<td style="text-align: left;">Inside and outside same EDR</td>
<td style="text-align: left;">Inside and outside same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">36660.00</td>
<td style="text-align: right;">0.8779366</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="post-secondary-paths" class="level1">
<h1>Post-secondary Paths</h1>
<p>In the previous analyses, post-secondary variables rose to the top again and again as a primary factor in whether an individual had meaningful employment in the region or not. In particular, these two variables were the highest and broke in the following ways;</p>
<section id="postsecondary-graduation-location-ps.grad.location" class="level2">
<h2 class="anchored" data-anchor-id="postsecondary-graduation-location-ps.grad.location"><strong>Postsecondary Graduation Location (<code>ps.grad.location</code>)</strong></h2>
<p>Across all three modeling scenarios we’ve explored — comparing meaningful employment in the region to employment in Minnesota, to not meaningful employment, and to no Minnesota employment record — <code>ps.grad.location</code> consistently emerged as one of the most important predictors.</p>
<p>Graduating from a postsecondary institution <strong>within the region</strong> was strongly associated with a higher likelihood of being meaningfully employed in the region, suggesting that geographic alignment between educational attainment and local labor markets fosters stronger employment ties.</p>
<p>Graduating outside the region, particularly outside Minnesota, was linked with an increased likelihood of either securing meaningful employment elsewhere or having no Minnesota employment record at all.</p>
<p>These patterns point to the potential “stickiness” of local graduates in the regional workforce, and the challenges of retaining graduates who leave to complete their education.</p>
</section>
<section id="highest-credential-level-highest.cred.level" class="level2">
<h2 class="anchored" data-anchor-id="highest-credential-level-highest.cred.level"><strong>Highest Credential Level (<code>highest.cred.level</code>)</strong></h2>
<p><code>highest.cred.level</code> was a dominant predictor in multiple models, particularly when distinguishing between individuals who were meaningfully employed in the region and those who were not.</p>
<p>Earning an <strong>associate degree or higher</strong> — and especially a <strong>bachelor’s degree or higher</strong> — was linked with greater odds of being meaningfully employed in the region.</p>
<p>Lower levels of attainment, including “some college” without a credential, “less than associate degree,” or “no college,” were associated with higher rates of disconnectedness (no Minnesota employment record, not attending postsecondary) or employment outside the region.</p>
<p>This reinforces the central role of credential attainment in improving employment stability and alignment with regional labor needs.</p>
<hr>
<p>For both of these variables, we will combine classifications in order to have a smaller set to model against;</p>
<ul>
<li>ps.grad.location
<ol type="1">
<li>PS grad region</li>
<li>PS grad outside region: includes all individuals that graduated from college outside of the region.</li>
<li>Did not graduate ps</li>
</ol></li>
<li>highest.cred.level
<ol type="1">
<li>Associate degree or lower</li>
<li>Bachelors or higher</li>
<li>Did not graduate: includes individuals with some college and no college experience.</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>master <span class="ot">&lt;-</span> master.original <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.location.new =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"PS grad MN"</span>, <span class="st">"PS grad outside MN"</span>), <span class="st">"PS grad outside region"</span>, <span class="fu">as.character</span>(ps.grad.location)),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level.new =</span> <span class="fu">ifelse</span>(highest.cred.level <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Associate degree"</span>, <span class="st">"Less than Associate Degree"</span>), <span class="st">"Associate degree or lower"</span>, <span class="fu">as.character</span>(highest.cred.level)),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level.new =</span> <span class="fu">ifelse</span>(highest.cred.level.new <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"No college"</span>, <span class="st">"Some college"</span>), <span class="st">"Did not graduate ps"</span>, <span class="fu">as.character</span>(highest.cred.level.new)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="even">
<td style="text-align: left;">attended.ps.within.first.year.hsgrad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="even">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="even">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="even">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location.new</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level.new</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">edr</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: left;">attended.ps.within.first.year.hsgrad</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
<th style="text-align: left;">ps.grad.location.new</th>
<th style="text-align: left;">highest.cred.level.new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5356619</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">EDR 5 - North Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Public, 4-year</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad outside MN</td>
<td style="text-align: left;">Outside RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">Outside MN</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7.400000</td>
<td style="text-align: right;">35348.33</td>
<td style="text-align: right;">0.7577566</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="even">
<td style="text-align: right;">1506121</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7E- East Central</td>
<td style="text-align: left;">Post-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">44645.67</td>
<td style="text-align: right;">0.6740970</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1456500</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: left;">EDR 5 - North Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5.700000</td>
<td style="text-align: right;">28114.67</td>
<td style="text-align: right;">0.6820086</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">10870895</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not attend ps</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Never attended ps</td>
<td style="text-align: left;">No college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.300000</td>
<td style="text-align: right;">41847.67</td>
<td style="text-align: right;">0.8475591</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">No MN emp record, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1877865</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.966667</td>
<td style="text-align: right;">45101.67</td>
<td style="text-align: right;">0.8861302</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">1323083</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 7W- Central</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Associate degree</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Inside and outside same RUCA</td>
<td style="text-align: left;">Inside and outside same EDR</td>
<td style="text-align: left;">Inside and outside same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">36660.00</td>
<td style="text-align: right;">0.8779366</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Associate degree or lower</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>This study investigates the factors that influence what secondary education pathway a high school graduate follows. To isolate and understand the predictors of this specific outcome, the analysis compares it separately against three alternative post-secondary variables:</p>
<ol type="1">
<li>Post-secondary graduation location</li>
<li>Highest Credential Earned in Post-secondary</li>
</ol>
<p>Graduates classified as <em>Attending post-secondary</em> for either of these are excluded from the analysis.</p>
<p>The modeling process follows these steps:</p>
<ol type="1">
<li><p><strong>Data Preparation</strong> All predictor variables include demographic characteristics, high school characteristics, and high school achievement indicators. Records with missing target outcome categories are excluded.</p></li>
<li><p><strong>Training and Test Split</strong> For each post-secondary variable, the data is randomly split into a training set (70–80%) and a testing set (20–30%) to ensure that model evaluation is conducted on previously unseen data.</p></li>
<li><p><strong>Modeling</strong></p>
<p>We are going to use the following method to each comparison:</p>
<ul>
<li><strong>CART (Classification and Regression Tree)</strong> for interpretability and identification of clear decision rules. We will start by developing the base model, and then do pre- and post-pruning to determine which model provides the best accuracy.</li>
</ul></li>
<li><p><strong>Evaluation</strong> Models are evaluated on the testing set using accuracy, Cohen’s kappa, balanced accuracy, sensitivity, and specificity. Variable importance is examined to identify the most influential predictors for each comparison and time point.</p></li>
</ol>
<p>This approach emphasizes clarity in interpretation by focusing each mode three post-secondary distinctions, making it easier to identify which factors most strongly differentiate graduates who follow pathways that lead to secondary pathways that benefit regional workforce employment.</p>
<p><br></p>
</section>
<section id="analysis---post-secondary-location" class="level1">
<h1>Analysis - Post secondary location</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> master <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(economic.status, RaceEthnicity, SpecialEdStatus, Dem_Desc, avg.unemp.rate, avg.wages.pct.state, ACTCompositeScore, pseo.participant, cte.achievement, total.cte.courses.taken, MCA.M, MCA.R, MCA.S, ps.grad.location.new, highest.cred.level.new)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="even">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="even">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.location.new</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest.cred.level.new</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">economic.status</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: left;">ps.grad.location.new</th>
<th style="text-align: left;">highest.cred.level.new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: right;">7.400000</td>
<td style="text-align: right;">0.7577566</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">0.6740970</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Concentrator or Completor</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Town/rural mix</td>
<td style="text-align: right;">5.700000</td>
<td style="text-align: right;">0.6820086</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Hispanic</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">4.300000</td>
<td style="text-align: right;">0.8475591</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">3.966667</td>
<td style="text-align: right;">0.8861302</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">6.700000</td>
<td style="text-align: right;">0.8779366</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Associate degree or lower</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table below shows that 58% of the individuals did not graduate college, 30% graduated outside their high school region, and only 12% graduated from a college within their region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ps.grad.location <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>highest.cred.level.new) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ps.grad.location.new <span class="sc">!=</span> <span class="st">"Attending ps"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.location.new =</span> <span class="fu">as.factor</span>(ps.grad.location.new))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(ps.grad.location))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "119,385"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> ps.grad.location <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(ps.grad.location.new) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-505bac32b5bedddbad08" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-505bac32b5bedddbad08">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Did not graduate ps&quot;,&quot;PS grad outside region&quot;,&quot;PS grad region&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"14641\" data-max=\"69440\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.122636847175105\" data-max=\"0.581647610671358\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Did not graduate ps","PS grad outside region","PS grad region"],[69440,35304,14641],[0.5816476106713574,0.2957155421535369,0.1226368471751058]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>ps.grad.location.new<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"ps.grad.location.new","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model" class="level2">
<h2 class="anchored" data-anchor-id="base-model">Base Model</h2>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(ps.grad.location), <span class="fu">nrow</span>(ps.grad.location) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> ps.grad.location[sample_ind,]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> ps.grad.location[<span class="sc">-</span>sample_ind,]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ps.grad.location.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>accuracy_base <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_base, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "63.6%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore       avg.unemp.rate          avg.wages.pct.state    
 [4] cte.achievement         Dem_Desc                economic.status        
 [7] MCA.M                   MCA.R                   MCA.S                  
[10] pseo.participant        RaceEthnicity           SpecialEdStatus        
[13] total.cte.courses.taken

Root node error: 35015/83569 = 0.419

n= 83569 

            CP nsplit rel error  xerror      xstd
1   7.6596e-02      0   1.00000 1.00000 0.0040735
2   6.0288e-02      1   0.92340 0.92340 0.0040210
3   1.9792e-02      2   0.86312 0.86352 0.0039672
4   3.3414e-03      3   0.84332 0.84335 0.0039465
5   2.8788e-03      4   0.83998 0.84241 0.0039455
6   2.6560e-03     10   0.81876 0.82522 0.0039267
7   2.3419e-03     11   0.81611 0.81605 0.0039162
8   1.9849e-03     12   0.81377 0.81054 0.0039098
9   1.9135e-03     14   0.80980 0.81045 0.0039097
10  9.7101e-04     16   0.80597 0.81040 0.0039097
11  8.2822e-04     19   0.80306 0.80785 0.0039067
12  7.7110e-04     21   0.80140 0.80691 0.0039056
13  5.7118e-04     22   0.80063 0.80203 0.0038997
14  5.4262e-04     25   0.79891 0.80097 0.0038985
15  5.1407e-04     29   0.79674 0.80134 0.0038989
16  4.9979e-04     32   0.79520 0.80049 0.0038979
17  3.9983e-04     41   0.78943 0.79971 0.0038970
18  3.8555e-04     43   0.78863 0.79894 0.0038960
19  3.7127e-04     47   0.78709 0.79863 0.0038956
20  3.2843e-04     48   0.78672 0.79740 0.0038942
21  3.1415e-04     50   0.78606 0.79709 0.0038938
22  2.8559e-04     53   0.78512 0.79754 0.0038943
23  2.5703e-04     54   0.78484 0.79766 0.0038945
24  2.4275e-04     58   0.78381 0.79723 0.0038939
25  2.3561e-04     64   0.78235 0.79743 0.0038942
26  2.2847e-04     68   0.78141 0.79732 0.0038941
27  2.1419e-04     71   0.78072 0.79692 0.0038936
28  2.0943e-04     78   0.77918 0.79632 0.0038928
29  1.9991e-04     82   0.77830 0.79589 0.0038923
30  1.9420e-04    101   0.77421 0.79594 0.0038924
31  1.9039e-04    110   0.77227 0.79583 0.0038922
32  1.8563e-04    113   0.77170 0.79657 0.0038931
33  1.8087e-04    119   0.77058 0.79640 0.0038929
34  1.7136e-04    125   0.76950 0.79612 0.0038926
35  1.5708e-04    138   0.76724 0.79580 0.0038922
36  1.5232e-04    148   0.76567 0.79526 0.0038915
37  1.4280e-04    156   0.76433 0.79569 0.0038921
38  1.3328e-04    169   0.76242 0.79657 0.0038931
39  1.3137e-04    176   0.76147 0.79623 0.0038927
40  1.2852e-04    182   0.76065 0.79623 0.0038927
41  1.2376e-04    196   0.75879 0.79552 0.0038919
42  1.2058e-04    205   0.75768 0.79554 0.0038919
43  1.1424e-04    214   0.75659 0.79534 0.0038916
44  1.0472e-04    243   0.75308 0.79437 0.0038905
45  9.9957e-05    253   0.75202 0.79483 0.0038910
46  9.7101e-05    270   0.75031 0.79443 0.0038905
47  9.5197e-05    277   0.74954 0.79443 0.0038905
48  9.2817e-05    291   0.74791 0.79514 0.0038914
49  8.5678e-05    295   0.74754 0.79580 0.0038922
50  7.9966e-05    369   0.74108 0.79674 0.0038934
51  7.8538e-05    421   0.73614 0.79794 0.0038948
52  7.7518e-05    425   0.73583 0.79794 0.0038948
53  7.6158e-05    443   0.73429 0.79826 0.0038952
54  7.1398e-05    499   0.72860 0.79917 0.0038963
55  6.8542e-05    562   0.72358 0.79949 0.0038967
56  6.6638e-05    572   0.72289 0.79966 0.0038969
57  6.5278e-05    599   0.72092 0.79974 0.0038970
58  6.4258e-05    606   0.72046 0.79986 0.0038971
59  6.2830e-05    632   0.71872 0.79986 0.0038971
60  6.1878e-05    637   0.71841 0.80517 0.0039035
61  6.1198e-05    643   0.71804 0.80517 0.0039035
62  6.0688e-05    671   0.71555 0.80505 0.0039034
63  5.7118e-05    697   0.71384 0.80523 0.0039036
64  5.3038e-05    872   0.70336 0.80703 0.0039057
65  5.2359e-05    888   0.70250 0.80834 0.0039073
66  5.1407e-05    902   0.70164 0.80848 0.0039074
67  4.9979e-05    962   0.69773 0.80931 0.0039084
68  4.8959e-05    979   0.69684 0.80985 0.0039090
69  4.8551e-05    987   0.69642 0.80988 0.0039091
70  4.7599e-05    999   0.69579 0.80988 0.0039091
71  4.5695e-05   1031   0.69425 0.81242 0.0039120
72  4.4879e-05   1036   0.69402 0.81317 0.0039129
73  4.2839e-05   1051   0.69333 0.81408 0.0039140
74  4.1541e-05   1193   0.68673 0.81608 0.0039163
75  4.0799e-05   1207   0.68605 0.81645 0.0039167
76  3.9983e-05   1215   0.68571 0.81702 0.0039174
77  3.8079e-05   1223   0.68533 0.81953 0.0039202
78  3.6719e-05   1320   0.68114 0.82071 0.0039216
79  3.6175e-05   1329   0.68074 0.82085 0.0039217
80  3.5699e-05   1348   0.67999 0.82148 0.0039225
81  3.4271e-05   1416   0.67688 0.82210 0.0039232
82  3.3319e-05   1446   0.67577 0.82225 0.0039233
83  3.2639e-05   1465   0.67505 0.82225 0.0039233
84  3.1732e-05   1482   0.67431 0.82225 0.0039233
85  2.8559e-05   1495   0.67385 0.83567 0.0039382
86  2.5703e-05   1912   0.66132 0.83710 0.0039398
87  2.5386e-05   1927   0.66092 0.83778 0.0039405
88  2.4989e-05   1948   0.66029 0.83918 0.0039420
89  2.3799e-05   1966   0.65983 0.83924 0.0039421
90  2.2847e-05   1996   0.65906 0.84235 0.0039454
91  2.2213e-05   2006   0.65883 0.84312 0.0039462
92  2.1419e-05   2017   0.65857 0.84341 0.0039465
93  1.9039e-05   2099   0.65666 0.84689 0.0039502
94  1.8174e-05   2217   0.65418 0.84829 0.0039517
95  1.7849e-05   2229   0.65395 0.84929 0.0039527
96  1.7136e-05   2246   0.65363 0.84984 0.0039533
97  1.5866e-05   2279   0.65306 0.84989 0.0039533
98  1.4280e-05   2289   0.65289 0.85843 0.0039621
99  1.2240e-05   2505   0.64949 0.85992 0.0039636
100 1.1424e-05   2529   0.64918 0.86186 0.0039655
101 1.0984e-05   2584   0.64855 0.86197 0.0039657
102 1.0710e-05   2597   0.64841 0.86197 0.0039657
103 9.5197e-06   2618   0.64815 0.86649 0.0039701
104 8.1598e-06   2725   0.64712 0.86714 0.0039708
105 7.1398e-06   2739   0.64701 0.86886 0.0039725
106 5.7118e-06   2831   0.64635 0.86903 0.0039726
107 5.1926e-06   2876   0.64609 0.87037 0.0039739
108 4.7599e-06   2887   0.64604 0.87068 0.0039742
109 4.0799e-06   2923   0.64581 0.87086 0.0039744
110 3.5699e-06   2944   0.64572 0.87131 0.0039749
111 2.8559e-06   2960   0.64567 0.87143 0.0039750
112 0.0000e+00   2970   0.64564 0.87151 0.0039750</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 63.6%</li>
<li><strong>Variables used:</strong> 13 total, spanning demographics, high school characteristics, and high school accomplishments (e.g., ACTCompositeScore, avg.unemp.rate, avg.wages.pct.state, CTE achievement, economic status, MCA scores, pseo.participant, RaceEthnicity, SpecialEdStatus, total CTE courses taken).</li>
<li><strong>Lowest cross-validation error:</strong> 0.79443 at cp ≈ 0.000097101 (nsplit = 277).</li>
</ul>
<p><br></p>
</section>
<section id="pre-pruning" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning">Pre-pruning</h2>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 6</li>
<li>minsplit: round(2% of nrow(train)) which is 1617.</li>
<li>minbucket: round(minsplit / 3) which is 557</li>
<li>cp = 0</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">6</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> <span class="fu">round</span>(.<span class="dv">02</span><span class="sc">*</span><span class="fu">nrow</span>(train))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ps.grad.location.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "65.9%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore   avg.wages.pct.state cte.achievement    
[4] economic.status     pseo.participant    RaceEthnicity      
[7] SpecialEdStatus    

Root node error: 35015/83569 = 0.419

n= 83569 

           CP nsplit rel error  xerror      xstd
1  0.07659574      0   1.00000 1.00000 0.0040735
2  0.06028845      1   0.92340 0.92340 0.0040210
3  0.01979152      2   0.86312 0.86312 0.0039668
4  0.00334143      3   0.84332 0.84332 0.0039464
5  0.00302727      4   0.83998 0.83824 0.0039410
6  0.00287877      5   0.83696 0.83544 0.0039380
7  0.00198486     10   0.82256 0.82011 0.0039209
8  0.00045695     12   0.81859 0.81799 0.0039185
9  0.00017136     13   0.81814 0.81913 0.0039198
10 0.00000000     15   0.81779 0.81833 0.0039189</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy:</strong> 65.9% — notable improvement over the base model’s 63.6%.</li>
<li><strong>Variables used (8 total):</strong> A mix of high school accomplishments (ACTCompositeScore, pseo.participant, cte.achievement), Demographics (economic.status, RaceEthnicity, SpecialEdStatus) and high school characteristics (avg.wages.pct.state)</li>
<li><strong>Tree complexity:</strong> Pre-pruning capped growth to <strong>maxdepth</strong>, resulting in 15 splits vs.&nbsp;1000+ in the base model.</li>
<li><strong>Lowest cross-validation error (xerror):</strong> ≈ 0.81799 at <strong>cp ≈</strong> 0.00045695 (nsplit = 12).</li>
</ul>
<p><br></p>
</section>
<section id="post-pruning" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning">Post-pruning</h2>
<p>The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> ps.grad.location.model.preprune<span class="sc">$</span>cptable</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> ps.grad.location.model.preprune<span class="sc">$</span>cptable[<span class="fu">which.min</span>(ps.grad.location.model.preprune<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(ps.grad.location.model.preprune, <span class="at">cp =</span> cp_1se)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "65.8%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore   avg.wages.pct.state economic.status    
[4] pseo.participant    RaceEthnicity       SpecialEdStatus    

Root node error: 35015/83569 = 0.419

n= 83569 

         CP nsplit rel error  xerror      xstd
1 0.0765957      0   1.00000 1.00000 0.0040735
2 0.0602884      1   0.92340 0.92340 0.0040210
3 0.0197915      2   0.86312 0.86312 0.0039668
4 0.0033414      3   0.84332 0.84332 0.0039464
5 0.0030273      4   0.83998 0.83824 0.0039410
6 0.0028788      5   0.83696 0.83544 0.0039380
7 0.0019849     10   0.82256 0.82011 0.0039209</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy:</strong> 65.8% — same as pre-pruned.</li>
<li><strong>Variables used (6 total):</strong> HIgh school achievements (ACTCompositeScore, pseo.participant), High school characteristics (avg.wages.pct.state), Demographics (economic.status, RaceEthnicity, SpecialEdStatus)</li>
<li><strong>Tree complexity:</strong> We simplified the tree to just 10 splits, compared to 15 for the pre-pruned tree.</li>
<li><strong>Lowest cross-validation error (xerror):</strong> ≈ 0.82011 at <strong>cp ≈</strong> 0.0019849 (nsplit = 10).</li>
</ul>
<p>So, the accuracy of these are clear;</p>
<ul>
<li>Base model: 63.6%</li>
<li>Pre-pruned model: 65.9%</li>
<li>Post-pruned model: 65.8%</li>
</ul>
<p>The post-pruned model provides a much simpler model - 10 splits instead of pre-pruned’s 15 splits - while also giving the same accuracy. I will dive into that one below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(ps.grad.location.model.postprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="main-takeaway" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaway"><strong>Main takeaway</strong></h2>
<p><strong>Main Splits</strong><br>
</p>
<p>The first and most influential split is <strong>PSEO participation</strong>. Individuals who did not participate in PSEO are much more likely to fall into the “Did not graduate PS” category. Among non-PSEO participants, the next split is <strong>Race/Ethnicity</strong> (AI/Black/Hispanic/Unknown vs.&nbsp;other groups), followed by <strong>Special Education status</strong> and <strong>Economic status</strong>. For PSEO participants, the main split is also <strong>Race/Ethnicity</strong> (AI/Unknown vs.&nbsp;other groups), followed by <strong>Economic status</strong>, and then <strong>ACT Composite Score</strong> thresholds (&lt; 21, &lt; 22, &lt; 26) along with <strong>average wages as a percent of state average</strong>. These combinations differentiate between “Did not graduate PS,” “PS grad outside region,” and “PS grad region.”</p>
<p><strong>Variable Importance</strong></p>
<ol type="1">
<li><strong>PSEO participation</strong> – Primary driver of the first split, strongest influence overall.</li>
<li><strong>Race/Ethnicity</strong> – Consistent second-level split on both sides of the tree.</li>
<li><strong>Economic status</strong> – Influential in both PSEO and non-PSEO branches.</li>
<li><strong>ACT Composite Score</strong> – Multiple threshold splits influence postsecondary graduation location.</li>
<li><strong>Special Education status</strong> – Key split for non-PSEO students from certain racial/ethnic groups.</li>
<li><strong>Average wages (relative to state)</strong> – Smaller role, only relevant in a limited branch.</li>
</ol>
<p><strong>Interpretation</strong> Participation in PSEO strongly predicts likelihood of postsecondary graduation and whether it occurs within the high school region. Students without PSEO experience tend to have lower postsecondary graduation rates, especially those from underrepresented racial/ethnic groups, with special education needs, or from lower economic backgrounds. For students with PSEO experience, ACT score thresholds and economic status further refine the likelihood of regional versus non-regional graduation. Higher ACT scores are associated with greater odds of graduating outside the region, while economic disadvantages tilt toward non-completion. Wage levels relative to the state average only appear as a predictor in a narrow subgroup, suggesting it’s not a major factor overall.</p>
<p><strong>Brief Conclusion</strong> The model shows that PSEO participation is the most significant factor in predicting postsecondary graduation location, with race/ethnicity, economic status, and ACT performance providing additional differentiation. Non-PSEO participants—especially from underrepresented racial/ethnic groups and lower economic backgrounds—are much more likely not to graduate. Among PSEO participants, academic performance and economic status determine whether graduation is more likely to occur within or outside the high school region.</p>
<p><br></p>
</section>
</section>
<section id="analysis---highest-credential-earned" class="level1">
<h1>Analysis - Highest Credential Earned</h1>
<p>The table below shows that 58% of the individuals did not graduate college, 28% graduated with a Bachelor degree or higher, and 14% graduated with an Associate degree or lower.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>highest.cred.level <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ps.grad.location.new) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(highest.cred.level.new <span class="sc">!=</span> <span class="st">"Attending ps"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">highest.cred.level.new =</span> <span class="fu">as.factor</span>(highest.cred.level.new))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(highest.cred.level))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "119,387"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> highest.cred.level <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(highest.cred.level.new) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-84b5eb657cbacb559f81" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-84b5eb657cbacb559f81">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Associate degree or lower&quot;,&quot;Bachelor degree or higher&quot;,&quot;Did not graduate ps&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"17091\" data-max=\"69440\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.14315629004833\" data-max=\"0.581637866769414\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Associate degree or lower","Bachelor degree or higher","Did not graduate ps"],[17091,32856,69440],[0.1431562900483302,0.275205843182256,0.5816378667694138]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>highest.cred.level.new<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"highest.cred.level.new","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model-1" class="level2">
<h2 class="anchored" data-anchor-id="base-model-1">Base Model</h2>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(highest.cred.level), <span class="fu">nrow</span>(highest.cred.level) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> highest.cred.level[sample_ind,]</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> highest.cred.level[<span class="sc">-</span>sample_ind,]</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(highest.cred.level.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>accuracy_base <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_base, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "65.2%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore       avg.unemp.rate          avg.wages.pct.state    
 [4] cte.achievement         Dem_Desc                economic.status        
 [7] MCA.M                   MCA.R                   MCA.S                  
[10] pseo.participant        RaceEthnicity           SpecialEdStatus        
[13] total.cte.courses.taken

Root node error: 34977/83570 = 0.41854

n= 83570 

            CP nsplit rel error  xerror      xstd
1   8.9945e-02      0   1.00000 1.00000 0.0040773
2   6.6644e-02      1   0.91006 0.90988 0.0040134
3   2.5445e-02      2   0.84341 0.84447 0.0039510
4   4.5287e-03      3   0.81797 0.81920 0.0039231
5   2.3444e-03      9   0.78635 0.78760 0.0038852
6   2.1157e-03     11   0.78166 0.77868 0.0038739
7   1.8155e-03     14   0.77362 0.77305 0.0038666
8   1.4295e-03     18   0.76487 0.76788 0.0038598
9   1.2008e-03     19   0.76344 0.76670 0.0038583
10  7.1476e-04     20   0.76224 0.76450 0.0038553
11  7.0046e-04     21   0.76153 0.76384 0.0038545
12  6.0039e-04     23   0.76013 0.76316 0.0038535
13  5.2892e-04     29   0.75630 0.76230 0.0038524
14  4.7174e-04     34   0.75364 0.76167 0.0038515
15  4.5744e-04     38   0.75175 0.76167 0.0038515
16  4.0026e-04     39   0.75129 0.76093 0.0038505
17  3.6595e-04     41   0.75049 0.76073 0.0038503
18  2.8590e-04     49   0.74721 0.75850 0.0038473
19  2.5731e-04     55   0.74549 0.75747 0.0038459
20  2.2872e-04     56   0.74523 0.75687 0.0038450
21  2.1919e-04     57   0.74500 0.75650 0.0038445
22  2.1443e-04     61   0.74412 0.75613 0.0038440
23  2.0966e-04     65   0.74326 0.75627 0.0038442
24  2.0013e-04     72   0.74154 0.75587 0.0038437
25  1.8870e-04     78   0.74029 0.75538 0.0038430
26  1.8584e-04     86   0.73857 0.75504 0.0038425
27  1.7726e-04     88   0.73820 0.75475 0.0038421
28  1.7154e-04     93   0.73731 0.75504 0.0038425
29  1.5725e-04     99   0.73628 0.75530 0.0038429
30  1.5248e-04    103   0.73565 0.75490 0.0038423
31  1.4772e-04    110   0.73457 0.75455 0.0038419
32  1.4295e-04    119   0.73314 0.75424 0.0038414
33  1.3342e-04    143   0.72902 0.75424 0.0038414
34  1.2866e-04    148   0.72802 0.75361 0.0038406
35  1.2707e-04    167   0.72548 0.75370 0.0038407
36  1.2389e-04    177   0.72419 0.75553 0.0038432
37  1.1436e-04    185   0.72316 0.75507 0.0038426
38  1.0864e-04    204   0.72085 0.75558 0.0038433
39  1.0292e-04    209   0.72030 0.75438 0.0038416
40  1.0211e-04    237   0.71639 0.75430 0.0038415
41  1.0007e-04    246   0.71544 0.75432 0.0038416
42  9.5301e-05    270   0.71298 0.75404 0.0038412
43  9.1489e-05    293   0.71058 0.75490 0.0038423
44  8.5771e-05    304   0.70947 0.75527 0.0038429
45  8.1686e-05    376   0.70315 0.75504 0.0038425
46  8.0053e-05    383   0.70258 0.75481 0.0038422
47  7.8623e-05    389   0.70203 0.75678 0.0038449
48  7.6241e-05    393   0.70172 0.75673 0.0038448
49  7.1476e-05    409   0.70049 0.75741 0.0038458
50  6.8617e-05    480   0.69497 0.75821 0.0038469
51  6.6711e-05    495   0.69386 0.75873 0.0038476
52  6.5349e-05    531   0.69108 0.75873 0.0038476
53  6.4328e-05    540   0.69045 0.75873 0.0038476
54  6.2898e-05    553   0.68960 0.75873 0.0038476
55  6.1945e-05    599   0.68514 0.76233 0.0038524
56  5.7180e-05    611   0.68436 0.76267 0.0038529
57  5.1462e-05    815   0.67210 0.76470 0.0038556
58  5.0033e-05    849   0.67004 0.76810 0.0038601
59  4.7650e-05    858   0.66955 0.76853 0.0038607
60  4.5744e-05    926   0.66538 0.77359 0.0038673
61  4.4927e-05    956   0.66389 0.77377 0.0038675
62  4.2885e-05    970   0.66326 0.77442 0.0038684
63  4.0843e-05   1103   0.65715 0.77737 0.0038722
64  4.0026e-05   1120   0.65632 0.77791 0.0038729
65  3.9312e-05   1135   0.65557 0.77931 0.0038747
66  3.8681e-05   1155   0.65466 0.77931 0.0038747
67  3.8120e-05   1178   0.65369 0.78008 0.0038757
68  3.6759e-05   1265   0.64954 0.78114 0.0038771
69  3.5738e-05   1297   0.64811 0.78237 0.0038786
70  3.4308e-05   1309   0.64768 0.78277 0.0038791
71  3.3355e-05   1358   0.64568 0.78320 0.0038797
72  3.2675e-05   1384   0.64468 0.78320 0.0038797
73  3.2164e-05   1398   0.64422 0.78320 0.0038797
74  3.1767e-05   1424   0.64337 0.78320 0.0038797
75  2.8590e-05   1434   0.64302 0.79638 0.0038961
76  2.5991e-05   1769   0.63299 0.79795 0.0038980
77  2.5414e-05   1780   0.63270 0.79970 0.0039001
78  2.4506e-05   1795   0.63224 0.80190 0.0039028
79  2.3825e-05   1811   0.63184 0.80213 0.0039031
80  2.2872e-05   1843   0.63104 0.80484 0.0039063
81  2.1443e-05   1909   0.62924 0.80544 0.0039070
82  2.0422e-05   1957   0.62810 0.80882 0.0039110
83  1.9060e-05   1964   0.62796 0.80950 0.0039119
84  1.7403e-05   2065   0.62601 0.81128 0.0039139
85  1.7154e-05   2104   0.62524 0.81233 0.0039152
86  1.4295e-05   2146   0.62427 0.82123 0.0039254
87  1.2253e-05   2408   0.61969 0.82288 0.0039273
88  1.1436e-05   2415   0.61961 0.82451 0.0039292
89  1.0211e-05   2451   0.61918 0.82451 0.0039292
90  9.5301e-06   2475   0.61892 0.82966 0.0039349
91  8.1686e-06   2579   0.61792 0.83020 0.0039355
92  7.1476e-06   2607   0.61769 0.83258 0.0039381
93  5.7180e-06   2669   0.61723 0.83272 0.0039383
94  5.1982e-06   2718   0.61695 0.83443 0.0039402
95  4.7650e-06   2736   0.61683 0.83549 0.0039413
96  4.0843e-06   2758   0.61672 0.83606 0.0039419
97  3.5738e-06   2783   0.61661 0.83635 0.0039423
98  3.1767e-06   2791   0.61658 0.83641 0.0039423
99  2.8590e-06   2809   0.61652 0.83666 0.0039426
100 0.0000e+00   2819   0.61649 0.83661 0.0039425</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 65.2%</li>
<li><strong>Variables used:</strong> 13 total, spanning demographics, high school characteristics, and high school accomplishments (e.g., ACTCompositeScore, avg.unemp.rate, avg.wages.pct.state, CTE achievement, economic status, MCA scores, pseo.participant, RaceEthnicity, SpecialEdStatus, total CTE courses taken).</li>
<li><strong>Lowest cross-validation error:</strong> 0.75361 at cp ≈ 0.00012866 (nsplit = 148).</li>
</ul>
<p><br></p>
</section>
<section id="pre-pruning-1" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning-1">Pre-pruning</h2>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 6</li>
<li>minsplit: round(2% of nrow(train)) which is 1617.</li>
<li>minbucket: round(minsplit / 3) which is 557</li>
<li>cp = 0</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">6</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> <span class="fu">round</span>(.<span class="dv">02</span><span class="sc">*</span><span class="fu">nrow</span>(train))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(highest.cred.level.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "67.4%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore cte.achievement   economic.status   pseo.participant 
[5] RaceEthnicity     SpecialEdStatus  

Root node error: 34977/83570 = 0.41854

n= 83570 

          CP nsplit rel error  xerror      xstd
1 0.08994482      0   1.00000 1.00000 0.0040773
2 0.06664379      1   0.91006 0.90997 0.0040135
3 0.02544529      2   0.84341 0.84401 0.0039505
4 0.00452869      3   0.81797 0.81925 0.0039232
5 0.00323069      8   0.79532 0.79947 0.0038999
6 0.00211568     10   0.78886 0.79172 0.0038904
7 0.00040026     13   0.78083 0.78317 0.0038796
8 0.00000000     14   0.78043 0.78274 0.0038791</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy:</strong> 67.4% — notable improvement over the base model’s 65.2%.</li>
<li><strong>Variables used (6 total):</strong>
<ul>
<li>High school accomplishments: ACTCompositeScore, cte.achievement, pseo.participant</li>
<li>Demographics: economic.status, RaceEthnicity, SpecialEdStatus</li>
</ul></li>
<li><strong>Tree complexity:</strong> Pre-pruning capped growth to <strong>maxdepth</strong>, resulting in 14 splits vs.&nbsp;1000+ in the base model.</li>
<li><strong>Lowest cross-validation error (xerror):</strong> ≈ 0.79172 at <strong>cp ≈</strong> 0.00211568 (nsplit = 10).</li>
</ul>
<p><br></p>
</section>
<section id="post-pruning-1" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning-1">Post-pruning</h2>
<p>The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> highest.cred.level.model.preprune<span class="sc">$</span>cptable</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> highest.cred.level.model.preprune<span class="sc">$</span>cptable[<span class="fu">which.min</span>(highest.cred.level.model.preprune<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(highest.cred.level.model.preprune, <span class="at">cp =</span> cp_1se)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "67.4%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore cte.achievement   economic.status   pseo.participant 
[5] RaceEthnicity     SpecialEdStatus  

Root node error: 34977/83570 = 0.41854

n= 83570 

          CP nsplit rel error  xerror      xstd
1 0.08994482      0   1.00000 1.00000 0.0040773
2 0.06664379      1   0.91006 0.90997 0.0040135
3 0.02544529      2   0.84341 0.84401 0.0039505
4 0.00452869      3   0.81797 0.81925 0.0039232
5 0.00323069      8   0.79532 0.79947 0.0038999
6 0.00211568     10   0.78886 0.79172 0.0038904
7 0.00040026     13   0.78083 0.78317 0.0038796</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key Takeaways</strong></p>
<ul>
<li><strong>Accuracy:</strong> 67.4% — same as pre-pruned.</li>
<li><strong>Variables used (6 total):</strong>
<ul>
<li>High school accomplishments: ACTCompositeScore, cte.achievement, pseo.participant</li>
<li>Demographics: economic.status, RaceEthnicity, SpecialEdStatus</li>
</ul></li>
<li><strong>Tree complexity:</strong> We simplified the tree to just 13 splits, compared to 14 for the pre-pruned tree.</li>
<li><strong>Lowest cross-validation error (xerror):</strong> ≈ 0.78317 at <strong>cp ≈</strong> 0.00040026 (nsplit = 13).</li>
</ul>
<p>So, the accuracy of these are clear;</p>
<ul>
<li>Base model: 65.2%</li>
<li>Pre-pruned model: 67.4%</li>
<li>Post-pruned model: 67.4%</li>
</ul>
<p>The post-pruned model provides a bit of a simpler model - 13 splits instead of pre-pruned’s 14 splits - while also giving the same accuracy. I will dive into that one below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(highest.cred.level.model.postprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="main-takeaway-1" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaway-1"><strong>Main takeaway</strong></h2>
<p><strong>Main Splits</strong> The most influential split is <strong>PSEO participation</strong>. Students without PSEO experience are more likely not to graduate from postsecondary education, while those with PSEO experience show higher rates of earning a bachelor’s degree or higher. For non-PSEO participants, the next split is <strong>Race/Ethnicity</strong> (Asian/PI/Black/Hispanic/White vs.&nbsp;others), followed by <strong>ACT Composite Score</strong> thresholds (≥ 21 and ≥ 26), with <strong>economic status</strong> and <strong>CTE achievement</strong> further refining outcomes. For PSEO participants, <strong>ACT Composite Score</strong> (≥ 20) is the initial determinant, followed by <strong>Race/Ethnicity</strong>, <strong>economic status</strong>, and <strong>Special Education status</strong>. In some branches, lower ACT scores (&lt; 24) and special education status predict much higher rates of non-completion.</p>
<p><strong>Variable Importance</strong></p>
<ol type="1">
<li><p><strong>PSEO participation</strong> – Strongest driver of overall classification, key root split.</p></li>
<li><p><strong>ACT Composite Score</strong> – Appears multiple times with different thresholds (18, 20, 21, 24, 26), strongly differentiating educational outcomes.</p></li>
<li><p><strong>Race/Ethnicity</strong> – Consistent second-level split, shaping degree level expectations.</p></li>
<li><p><strong>Economic status</strong> – Important in both PSEO and non-PSEO paths, associated with lower completion at higher credential levels.</p></li>
<li><p><strong>CTE achievement</strong> – Plays a smaller but notable role for high-scoring non-PSEO students.</p></li>
<li><p><strong>Special Education status</strong> – Particularly important for lower ACT PSEO students.</p></li>
</ol>
<p><strong>Interpretation</strong> PSEO participation sharply divides the likelihood of postsecondary credential attainment. Non-PSEO students—particularly from certain racial/ethnic groups and with lower ACT scores—are far more likely to not graduate, while higher ACT scores and favorable economic conditions increase the odds of earning bachelor’s degrees. For PSEO students, ACT performance remains a strong determinant, with high scorers more likely to reach bachelor’s or higher credentials, and low scorers—especially those from disadvantaged economic backgrounds or with special education status—more likely not to complete. CTE achievement provides a modest boost in certain high-performing, non-PSEO cases.</p>
<p><strong>Brief Conclusion</strong> The model underscores PSEO participation and ACT performance as the two most critical predictors of highest credential earned, with race/ethnicity, economic status, and—more selectively—CTE achievement and special education status providing additional nuance. High ACT scores combined with PSEO participation strongly favor bachelor’s-level attainment, while low scores, economic disadvantage, and lack of PSEO participation correspond with non-completion.</p>
<p><br></p>
</section>
</section>
<section id="comparison" class="level1">
<h1>Comparison</h1>
<p>Both models identify <strong>PSEO participation</strong> as the strongest predictor, but the way subsequent variables shape outcomes differs.</p>
<p>For <strong><code>ps.grad.location.new</code></strong>, the primary narrative is about <em>where</em> postsecondary graduation occurs—or if it happens at all. After PSEO participation, <strong>Race/Ethnicity</strong> is the next most influential factor in both branches, followed by <strong>Economic status</strong> and multiple <strong>ACT Composite Score</strong> thresholds. Special Education status plays a role mainly for non-PSEO students, while <strong>average wages (relative to state)</strong> only appears in a small branch. The outcome paths focus on the geographic context of graduation (within region, outside region, or no graduation).</p>
<p>For <strong><code>highest.cred.level</code></strong>, the emphasis is on <em>how far</em> a student progresses academically. After PSEO participation, <strong>ACT Composite Score</strong> takes a larger role in differentiating degree levels, with several score thresholds driving major branches. <strong>Race/Ethnicity</strong> still appears early but is sometimes secondary to ACT performance. <strong>Economic status</strong> consistently lowers the likelihood of earning bachelor’s degrees, while <strong>CTE achievement</strong> and <strong>Special Education status</strong> appear in smaller but notable branches. The outcome paths here are more strongly tied to academic performance and degree completion level.</p>
<p><strong>Key Differences</strong></p>
<ul>
<li><p><strong>Second Split</strong>: Location model → Race/Ethnicity; Credential model → ACT Composite Score.</p></li>
<li><p><strong>Geography vs.&nbsp;Attainment</strong>: Location model’s later splits focus on regional vs.&nbsp;non-regional graduation; Credential model’s later splits focus on associate vs.&nbsp;bachelor’s degree attainment.</p></li>
<li><p><strong>Unique Predictors</strong>: Location model includes average wages; Credential model includes CTE achievement.</p></li>
<li><p><strong>Special Education Influence</strong>: Appears earlier and more prominently in Credential model’s PSEO branch, but mostly in the non-PSEO branch for Location model.</p></li>
</ul>
<p><strong>Brief Conclusion</strong> While both models agree that PSEO participation is the critical starting point, the determinants that follow diverge according to the outcome of interest. Geographic graduation patterns are more closely tied to demographic and economic factors, whereas credential level is more directly tied to academic performance and CTE involvement.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>