<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The pathways – Pathways taken after high school - Central</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Central</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./employment.html">
 <span class="dropdown-text">Employment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways_ct.html">
 <span class="dropdown-text">Post-secondary pathways cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_multivariate_confirmation_analysis.html">
 <span class="dropdown-text">Multivariate Confirmation Analysis - Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_post_secondary_graduates.html">
 <span class="dropdown-text">Non-college graduates</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_college_deeper.html">
 <span class="dropdown-text">Further analysis on non-college grads</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_multivariate_confirmation_non_college_grads.html">
 <span class="dropdown-text">Multivariate Confirmation Analysis on non-college grads - Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_multivariate_confirmation_disconnection_persistence.html">
 <span class="dropdown-text">Multivariate Confirmation Analysis on Persistent Disconnection</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="./summary_pathways.html" aria-current="page"> 
<span class="menu-text">Summary of the three pathways</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-findings-paths-taken-by-high-school-graduates" id="toc-the-findings-paths-taken-by-high-school-graduates" class="nav-link active" data-scroll-target="#the-findings-paths-taken-by-high-school-graduates">The Findings: Paths Taken by High School Graduates</a>
  <ul class="collapse">
  <li><a href="#proportion-of-graduates-in-each-workforce-participation-category-by-year-after-high-school" id="toc-proportion-of-graduates-in-each-workforce-participation-category-by-year-after-high-school" class="nav-link" data-scroll-target="#proportion-of-graduates-in-each-workforce-participation-category-by-year-after-high-school">Proportion of Graduates in Each Workforce Participation Category, by Year After High School</a></li>
  </ul></li>
  <li><a href="#getting-to-know-the-pathways" id="toc-getting-to-know-the-pathways" class="nav-link" data-scroll-target="#getting-to-know-the-pathways">Getting to Know the Pathways</a>
  <ul class="collapse">
  <li><a href="#pathway-1-the-college-completers-pathway" id="toc-pathway-1-the-college-completers-pathway" class="nav-link" data-scroll-target="#pathway-1-the-college-completers-pathway">Pathway 1: The College Completers’ Pathway</a>
  <ul class="collapse">
  <li><a href="#completing-college-is-highly-associated-with-sustained-labor-force-participation" id="toc-completing-college-is-highly-associated-with-sustained-labor-force-participation" class="nav-link" data-scroll-target="#completing-college-is-highly-associated-with-sustained-labor-force-participation">Completing college is highly associated with sustained labor force participation</a></li>
  <li><a href="#who-was-more-likely-to-complete-a-postsecondary-program" id="toc-who-was-more-likely-to-complete-a-postsecondary-program" class="nav-link" data-scroll-target="#who-was-more-likely-to-complete-a-postsecondary-program">Who was more likely to complete a postsecondary program?</a></li>
  <li><a href="#where-do-college-completers-participate-in-the-labor-force" id="toc-where-do-college-completers-participate-in-the-labor-force" class="nav-link" data-scroll-target="#where-do-college-completers-participate-in-the-labor-force">Where Do College Completers Participate in the Labor Force?</a></li>
  <li><a href="#what-high-school-experiences-were-associated-with-college-location" id="toc-what-high-school-experiences-were-associated-with-college-location" class="nav-link" data-scroll-target="#what-high-school-experiences-were-associated-with-college-location">What High School Experiences Were Associated with College Location?</a></li>
  </ul></li>
  <li><a href="#pathway-2-the-workforce-first-pathway" id="toc-pathway-2-the-workforce-first-pathway" class="nav-link" data-scroll-target="#pathway-2-the-workforce-first-pathway">Pathway 2: The Workforce-First Pathway</a>
  <ul class="collapse">
  <li><a href="#understanding-this-group" id="toc-understanding-this-group" class="nav-link" data-scroll-target="#understanding-this-group">Understanding this group</a></li>
  <li><a href="#who-was-more-likely-to-stay-connected-to-the-regional-workforce" id="toc-who-was-more-likely-to-stay-connected-to-the-regional-workforce" class="nav-link" data-scroll-target="#who-was-more-likely-to-stay-connected-to-the-regional-workforce">Who was more likely to stay connected to the regional workforce?</a></li>
  </ul></li>
  <li><a href="#pathway-3-the-disconnected-pathway" id="toc-pathway-3-the-disconnected-pathway" class="nav-link" data-scroll-target="#pathway-3-the-disconnected-pathway">Pathway 3: The Disconnected Pathway</a>
  <ul class="collapse">
  <li><a href="#size-of-this-group" id="toc-size-of-this-group" class="nav-link" data-scroll-target="#size-of-this-group">Size of this group</a></li>
  <li><a href="#persistently-disconnected" id="toc-persistently-disconnected" class="nav-link" data-scroll-target="#persistently-disconnected">Persistently Disconnected</a></li>
  <li><a href="#two-kinds-of-disconnection" id="toc-two-kinds-of-disconnection" class="nav-link" data-scroll-target="#two-kinds-of-disconnection">Two Kinds of Disconnection</a></li>
  <li><a href="#a-local-opportunity" id="toc-a-local-opportunity" class="nav-link" data-scroll-target="#a-local-opportunity">A Local Opportunity</a></li>
  <li><a href="#who-is-most-at-risk-of-disconnection" id="toc-who-is-most-at-risk-of-disconnection" class="nav-link" data-scroll-target="#who-is-most-at-risk-of-disconnection">Who is Most at Risk of Disconnection?</a></li>
  <li><a href="#disparities-compound-across-the-pipeline" id="toc-disparities-compound-across-the-pipeline" class="nav-link" data-scroll-target="#disparities-compound-across-the-pipeline">Disparities Compound Across the Pipeline</a></li>
  </ul></li>
  <li><a href="#what-offers-protection-against-disconnection" id="toc-what-offers-protection-against-disconnection" class="nav-link" data-scroll-target="#what-offers-protection-against-disconnection">What Offers Protection Against Disconnection?</a>
  <ul class="collapse">
  <li><a href="#protections-against-persistent-instability-non-sustained-employment" id="toc-protections-against-persistent-instability-non-sustained-employment" class="nav-link" data-scroll-target="#protections-against-persistent-instability-non-sustained-employment">Protections Against Persistent Instability (Non-Sustained Employment)</a></li>
  <li><a href="#protections-against-persistent-no-minnesota-employment-record-status" id="toc-protections-against-persistent-no-minnesota-employment-record-status" class="nav-link" data-scroll-target="#protections-against-persistent-no-minnesota-employment-record-status">Protections Against Persistent No-Minnesota-Employment-Record Status</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The pathways</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-findings-paths-taken-by-high-school-graduates" class="level1">
<h1>The Findings: Paths Taken by High School Graduates</h1>
<section id="proportion-of-graduates-in-each-workforce-participation-category-by-year-after-high-school" class="level2">
<h2 class="anchored" data-anchor-id="proportion-of-graduates-in-each-workforce-participation-category-by-year-after-high-school">Proportion of Graduates in Each Workforce Participation Category, by Year After High School</h2>
<p>The chart below tracks the share of high school graduates in each of seven “states” — meaningful employment in the county, in the same EDR, in the broader region, or in Minnesota; attending postsecondary; not meaningfully employed and not attending postsecondary; and no Minnesota employment record and not attending postsecondary — for each year following high school.</p>
<p>A few patterns stand out:</p>
<ul>
<li>Meaningful employment in Central Minnesota peaks about six years after graduation, when nearly a quarter of graduates are working 1,000+ hours that year for a single employer.</li>
<li>By six years after graduation, over half of all graduates have meaningful employment somewhere in Minnesota.</li>
<li>The share of graduates falling short of the meaningful-employment threshold in Minnesota holds fairly steady, hovering around 15% after the first year out of high school.</li>
<li>Nearly 30% of graduates have effectively disappeared from the dataset by about ten years after graduation — meaning they are neither enrolled in postsecondary education in the United States nor showing up in Minnesota’s employment records.</li>
</ul>
<hr>
</section>
</section>
<section id="getting-to-know-the-pathways" class="level1">
<h1>Getting to Know the Pathways</h1>
<section id="pathway-1-the-college-completers-pathway" class="level2">
<h2 class="anchored" data-anchor-id="pathway-1-the-college-completers-pathway">Pathway 1: The College Completers’ Pathway</h2>
<section id="completing-college-is-highly-associated-with-sustained-labor-force-participation" class="level3">
<h3 class="anchored" data-anchor-id="completing-college-is-highly-associated-with-sustained-labor-force-participation">Completing college is highly associated with sustained labor force participation</h3>
<p><strong>How many graduates complete college?</strong> Among the 119,386 graduates with a resolved postsecondary outcome (i.e., excluding those still enrolled), 42% went on to complete a postsecondary credential, while 58% did not.</p>
<p><strong>Do completers show more sustained workforce participation?</strong> Comparing meaningful employment rates between completers and non-completers — and setting aside those still attending postsecondary — shows a consistent advantage for completers, though the gap narrows over time:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Years after graduation</th>
<th>Non-completers: sustained employment</th>
<th>Completers: sustained employment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 year</td>
<td>35.2%</td>
<td>64.0%</td>
</tr>
<tr class="even">
<td>5 years</td>
<td>48.4%</td>
<td>64.5%</td>
</tr>
<tr class="odd">
<td>10 years</td>
<td>48.2%</td>
<td>58.9%</td>
</tr>
</tbody>
</table>
<p><em>(“Sustained employment” combines meaningful employment in the region and meaningful employment elsewhere in Minnesota, among those with a resolved employment status — i.e., excluding anyone still attending postsecondary.)</em></p>
<p>Completers hold a nearly 29-point advantage in sustained workforce participation one year after graduation, and while non-completers gradually close some of that gap over the following decade, completers remain more likely to be sustained workers at every point measured.</p>
</section>
<section id="who-was-more-likely-to-complete-a-postsecondary-program" class="level3">
<h3 class="anchored" data-anchor-id="who-was-more-likely-to-complete-a-postsecondary-program">Who was more likely to complete a postsecondary program?</h3>
<p>A multivariate model confirms that completion is the most demographically and behaviorally predictable outcome examined anywhere in this project — demographics alone explain more of the variation in completion than the full model sequences did for sustained regional employment.</p>
<p><strong>High school academic engagement is the strongest driver of completion.</strong> PSEO participation shows the single strongest association found anywhere across the project (PSEO participants are more than twice as likely to complete a credential). Taking the ACT is associated with lower completion odds unless the score is high enough to offset it — a “threshold” pattern where simply taking the test isn’t enough on its own, but higher scores strongly predict completion. AP exam participation is also a positive predictor.</p>
<p><strong>Demographic gaps in completion mostly reflect an access story, not a suppression story.</strong> Economically disadvantaged students, students with special education status, and English learners all show clear disadvantage from the outset, but that disadvantage shrinks substantially once high school accomplishments (PSEO, ACT, AP) are added to the model — special education status shows the largest shrinkage of any coefficient in the sequence. This suggests a real share of the demographic completion gap runs through unequal access to those accomplishment-building opportunities, rather than those opportunities simply masking an underlying disadvantage.</p>
<p><strong>Gender runs in the opposite direction here than for employment outcomes.</strong> Female graduates consistently show higher odds of completing a credential — the reverse of what’s seen for sustained regional employment, where female graduates show lower odds. These are two distinct, non-contradictory findings: women complete credentials at higher rates but, once employed, are somewhat less likely to remain regionally attached.</p>
<p><strong>Race/ethnicity gaps narrow once accomplishments are controlled</strong>, with American Indian, Black, and Hispanic graduates all moving substantially closer to parity with White graduates. Asian/Pacific Islander is the one exception, becoming a significant negative predictor only once accomplishments enter the model.</p>
<p><strong>Local labor market conditions matter little for whether students complete</strong>, though the relationship is the opposite direction from what predicts regional employment: higher local wages and higher local unemployment are both associated with somewhat higher odds of completion, plausibly because weaker local job prospects push more students toward postsecondary pathways.</p>
<p><strong>A notable exception: CTE course-taking and achievement show no association with completion at all</strong> — despite mattering consistently for regional employment attachment. This reinforces that CTE functions specifically as a pathway to regional employment rather than a general completion-boosting pathway.</p>
</section>
<section id="where-do-college-completers-participate-in-the-labor-force" class="level3">
<h3 class="anchored" data-anchor-id="where-do-college-completers-participate-in-the-labor-force">Where Do College Completers Participate in the Labor Force?</h3>
<p><strong>Postsecondary graduation location is the single strongest predictor of sustained regional workforce attachment among completers.</strong> Completing a credential outside the region is associated with dramatically lower odds of sustained regional attachment — the largest-magnitude effect found anywhere in this project. Its addition to the model explains more of the outcome than any other single factor tested, including credential level, demographics, or high school accomplishments.</p>
<p><strong>Only about 3 in 10 completers finish their credential within the region.</strong> Overall, 29.3% of college completers earned their credential from an institution within the region, 51.6% completed elsewhere in Minnesota, and 19.1% completed out of state.</p>
<p><strong>Highest credential earned also independently predicts sustained regional attachment.</strong> Holding a bachelor’s degree (versus an associate degree or less) is associated with roughly a 35% reduction in the odds of sustained regional attachment, compared to a roughly 70% reduction associated with completing outside the region. Both effects are independently significant — location and credential level are not simply capturing the same underlying pattern, but location is the substantially stronger of the two.</p>
<p><strong>One disparity does not close, no matter what is controlled for.</strong> The gap in sustained regional attachment between Black and White completers never narrows across the model sequence — if anything, it widens at several points and ends as the widest gap found anywhere in either the full-cohort or completers-only analysis. No accomplishment variable, credential level, or completion location explains this disparity, making it the single most important unresolved finding in the project.</p>
</section>
<section id="what-high-school-experiences-were-associated-with-college-location" class="level3">
<h3 class="anchored" data-anchor-id="what-high-school-experiences-were-associated-with-college-location">What High School Experiences Were Associated with College Location?</h3>
<p>The same model that identifies where graduates end up working (in-region vs.&nbsp;out) also identifies which high school characteristics predict completing college within the region versus elsewhere:</p>
<p><strong>Characteristics associated with completing college located in the region:</strong> - Economic disadvantage, special education status, English learner status, and non-English home language — students facing each of these are considerably more likely to complete their credential close to home rather than leaving the state. This mirrors the “access-constrained mobility” pattern seen throughout the project, though the accomplishments block explains a meaningful share of each of these relationships. - Attending high school in EDR 7W is associated with substantially higher odds of completing college within the region — the single strongest, most stable predictor identified for this outcome. - Black students consistently show higher odds of completing within the region than White students. - Taking the ACT (regardless of score) and higher CTE course-taking volume are both associated with staying regional.</p>
<p><strong>Characteristics associated with completing college located outside the region:</strong> - Attending high school in EDR 7E is associated with substantially lower odds of completing within the region. - Hispanic students consistently show lower odds of completing within the region than White students — a genuine split from Black students, who move in the opposite direction. This is the only outcome in the entire project where race/ethnicity categories split into two opposing directions rather than moving together. - Higher local wages near the high school predict leaving the region for postsecondary completion. - AP exam participation and SAT-taking both predict leaving the region. - Among ACT-takers, each additional point on the composite score further predicts leaving the region — so while simply taking the ACT predicts staying, scoring well on it predicts going elsewhere.</p>
<hr>
</section>
</section>
<section id="pathway-2-the-workforce-first-pathway" class="level2">
<h2 class="anchored" data-anchor-id="pathway-2-the-workforce-first-pathway">Pathway 2: The Workforce-First Pathway</h2>
<p><strong>58% of high school graduates did not complete a postsecondary credential.</strong></p>
<section id="understanding-this-group" class="level3">
<h3 class="anchored" data-anchor-id="understanding-this-group">Understanding this group</h3>
<p>Tracking non-completers’ employment status in the years following high school shows growing — but incomplete — connection to the workforce:</p>
<ul>
<li><strong>1 year after high school:</strong> 18.1% were in meaningful regional employment, and a combined 28.4% had meaningful employment somewhere in Minnesota. Most others were either underemployed (34.6%) or had no Minnesota employment record (17.6%); nearly one-fifth were still attending postsecondary.</li>
<li><strong>5 years after high school:</strong> The share in meaningful regional employment grew to 24.8%, and a combined 46.3% had meaningful employment somewhere in Minnesota — nearly half of this group. The remainder was split between underemployment (25.5%) and no Minnesota employment record (23.9%).</li>
<li><strong>10 years after high school:</strong> Meaningful regional employment held essentially steady at 23.7%, while meaningful employment elsewhere in Minnesota reached 24.5% (a combined 48.2%). However, the largest single group had no Minnesota employment record at all (31.5%) — signaling growing long-term detachment for a substantial share of this population.</li>
</ul>
<p>Meaningful employment in the region stabilizes at roughly one in four non-completers over time, and about half secure stable employment somewhere in Minnesota by year ten. But an equally large share remain underemployed or have disappeared from the state’s workforce records — underscoring both the resilience of many workforce-first graduates and the persistent risk of disconnection for others.</p>
</section>
<section id="who-was-more-likely-to-stay-connected-to-the-regional-workforce" class="level3">
<h3 class="anchored" data-anchor-id="who-was-more-likely-to-stay-connected-to-the-regional-workforce">Who was more likely to stay connected to the regional workforce?</h3>
<p>A parallel multivariate analysis focused specifically on sustained employment <em>within the region</em> (rather than sustained employment anywhere in Minnesota) reveals several dynamics that a combined measure obscures:</p>
<ul>
<li><strong>Local labor market context matters far more than a pooled analysis would suggest.</strong> High school EDR and local wage levels show a dramatic, highly significant relationship with regional (as opposed to statewide) sustained employment at every time point — among the strongest effects found anywhere in the project. A prior pooled analysis had concluded these factors faded in importance after year one; separating “sustained regionally” from “sustained elsewhere in Minnesota” shows that conclusion was an artifact of combining the two outcomes.</li>
<li><strong>The Black-White employment gap is disproportionately concentrated outside the region in the early years, but that pattern fades by year ten.</strong> Black non-completers who do achieve sustained employment are considerably more likely than White non-completers to have that employment be outside the Central region in years one and five — though this regional-mobility gap largely disappears by year ten, even as the underlying employment disparity itself never narrows.</li>
<li><strong>PSEO participation functions as a genuine regional-anchoring pathway.</strong> At years one and ten, PSEO showed no relationship with sustained employment generally, but became a clear, significant predictor once the outcome was narrowed to regional employment specifically — its benefit is invisible unless you’re specifically looking at who stays local.</li>
<li><strong>Simply attending postsecondary (without completing) is a fading general employment booster with no specific regional pull.</strong> Its effect on sustained employment collapses steadily from year one through year ten, and by year ten offers no meaningful advantage for regional attachment specifically.</li>
<li><strong>Taking the ACT becomes an increasingly region-specific advantage over time</strong>, growing stronger in the region-only measure by years five and ten even as its general-employment relationship weakens.</li>
<li><strong>Special education status’s disadvantage is almost entirely about achieving sustained employment at all — not about where that employment happens.</strong> By year ten, non-completers with special education status who do reach sustained employment appear no less likely, and possibly slightly more likely, to have that employment be regional.</li>
</ul>
<hr>
</section>
</section>
<section id="pathway-3-the-disconnected-pathway" class="level2">
<h2 class="anchored" data-anchor-id="pathway-3-the-disconnected-pathway">Pathway 3: The Disconnected Pathway</h2>
<section id="size-of-this-group" class="level3">
<h3 class="anchored" data-anchor-id="size-of-this-group">Size of this group</h3>
<p>Among non-completers, roughly half do not reach sustained workforce participation within five years of high school: at year five, 25.5% show non-sustained (underemployed/unstable) participation and 23.9% have no Minnesota employment record at all — together, about 49% of non-completers.</p>
</section>
<section id="persistently-disconnected" class="level3">
<h3 class="anchored" data-anchor-id="persistently-disconnected">Persistently Disconnected</h3>
<p>Looking across the full first five years after leaving formal education (rather than a single point-in-time snapshot), non-completers fall into four persistence categories:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category</th>
<th>Share of non-completers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Consistently attached (sustained employment all 5 years)</td>
<td>15.6%</td>
</tr>
<tr class="even">
<td>Intermittently disconnected (disconnected 1–2 years)</td>
<td>27.6%</td>
</tr>
<tr class="odd">
<td>Broadly disconnected (disconnected 3 years)</td>
<td>13.0%</td>
</tr>
<tr class="even">
<td>Persistently disconnected (disconnected 4–5 years)</td>
<td>43.8%</td>
</tr>
</tbody>
</table>
<p>Workforce disconnection is the modal experience for non-completers, not the exception: a majority (56.8%) experience disconnection in three or more of their first five years, and persistent disconnection alone (43.8%) is nearly three times the size of the group with full, sustained attachment (15.6%).</p>
</section>
<section id="two-kinds-of-disconnection" class="level3">
<h3 class="anchored" data-anchor-id="two-kinds-of-disconnection">Two Kinds of Disconnection</h3>
<p>Separating “disconnection” into its two distinct components — non-sustained employment (unstable/underemployment) versus no Minnesota employment record at all — reveals two very different risk profiles, tracked here across the first five years after formal education:</p>
<ul>
<li><strong>Combined sustained employment</strong> (region + broader Minnesota) rises steadily from 35.1% in year one to 48.1% by year five.</li>
<li><strong>No Minnesota employment record</strong> climbs every single year with no deceleration or reversal — from 21.8% in year one to 27.1% by year five, becoming the single largest of the seven tracked categories by that point.</li>
<li><strong>Non-sustained/fragmented employment</strong> (in-region only, out-of-region only, unclassified, and mixed combined) shrinks consistently, falling from 43.2% in year one to 24.8% by year five. The “mixed” sub-category (simultaneous in- and out-of-region non-sustained work) shrinks fastest, roughly halving from 14.7% to 6.9%.</li>
</ul>
<p>The two components behave very differently when tracked over time and given how often each type persists:</p>
<ul>
<li><strong>Non-sustained employment is common but usually temporary.</strong> Nearly 70% of non-completers experience it at some point, but of those, only about 1 in 5 (20.4%) ends up persistently non-sustained — most resolve to a short-term or intermittent pattern instead.</li>
<li><strong>No-record status is rarer, but far stickier.</strong> About 41% ever experience it, but of those, roughly 2 in 5 (41.3%) become persistently no-record — more than double the “stickiness” rate of non-sustained employment.</li>
</ul>
<p>A further quarter of non-completers (25.8%) experience <em>both</em> problems at different points across the five years rather than being persistently stuck in just one — which is why the combined “persistently disconnected” figure (43.8%) exceeds either individual persistence measure. Within the most disconnected group specifically, no single explanation dominates: it splits into three comparably sized subgroups — no-record driven (38.5%), non-sustained driven (32.5%), and a “mixed” group cycling between both problems (29.1%).</p>
</section>
<section id="a-local-opportunity" class="level3">
<h3 class="anchored" data-anchor-id="a-local-opportunity">A Local Opportunity</h3>
<p>Even among non-completers who do reach sustained employment, a growing share of that success is occurring outside the region rather than within it. The share of all sustained workers specifically attached to the Central region (as opposed to elsewhere in Minnesota) declines steadily — from 59.4% in year one down to 52.6% by year five. In other words, the longer a non-completer has been out of school, the more of their eventual employment “success” is happening somewhere other than Central Minnesota — a meaningful regional-retention concern layered on top of the disconnection patterns above.</p>
</section>
<section id="who-is-most-at-risk-of-disconnection" class="level3">
<h3 class="anchored" data-anchor-id="who-is-most-at-risk-of-disconnection">Who is Most at Risk of Disconnection?</h3>
<p>A confirmatory multivariate model tested the same characteristics against each disconnection mechanism separately, since a variable that predicts one type of disconnection may look very different — or even reverse — for the other.</p>
<p><strong>Characteristics associated with persistent non-sustained (unstable) employment:</strong> - Gender and economic disadvantage both show real, stable disadvantage specific to this mechanism. - Black non-completers show a large, non-attenuating disadvantage that slightly widens once postsecondary attendance is added to the model — the same Black-White gap that recurs across every outcome examined in this project. - Attending high school in EDR 7E is associated with higher odds of persistent non-sustained employment. - A higher ACT composite score (among those who took it) is associated with worse outcomes on this measure specifically — even though simply having taken the ACT is protective.</p>
<p><strong>Characteristics associated with persistent no-Minnesota-employment-record status:</strong> - Non-English home language shows the single most robust finding across this entire analysis — a large, highly stable disadvantage that barely moves regardless of which other factors are controlled for. - English learner status is significantly associated with higher odds of this outcome specifically (in contrast to its null relationship with non-sustained employment). - Asian/Pacific Islander and Hispanic graduates both show a significant disadvantage here — a clean reversal from their null role in the non-sustained-employment model, confirming their disconnection risk concentrates in disappearing from the record rather than job instability. - American Indian graduates show disadvantage in both mechanisms, though it’s somewhat weaker here than in the non-sustained model. - Having taken the SAT is strongly associated with this outcome specifically — the clearest single piece of evidence that the two disconnection mechanisms are genuinely distinct, since SAT-taking shows no relationship at all with non-sustained employment.</p>
</section>
<section id="disparities-compound-across-the-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="disparities-compound-across-the-pipeline">Disparities Compound Across the Pipeline</h3>
<p>The same demographic gaps that predict lower odds of completing college in the first place (see “Who was more likely to complete a postsecondary program?” above) — particularly for economically disadvantaged students, students with special education status, English learners, and American Indian and Hispanic students — tend to be the same gaps that reappear, sometimes in different forms, at each subsequent stage: in whether sustained employment is achieved at all, in whether that employment is regional, and in which specific disconnection mechanism (job instability vs.&nbsp;disappearing from the record) a graduate is more exposed to. The one gap that shows up consistently, and without meaningfully narrowing, at nearly every stage examined across the full project is the Black-White gap in workforce outcomes.</p>
<hr>
</section>
</section>
<section id="what-offers-protection-against-disconnection" class="level2">
<h2 class="anchored" data-anchor-id="what-offers-protection-against-disconnection">What Offers Protection Against Disconnection?</h2>
<section id="protections-against-persistent-instability-non-sustained-employment" class="level3">
<h3 class="anchored" data-anchor-id="protections-against-persistent-instability-non-sustained-employment">Protections Against Persistent Instability (Non-Sustained Employment)</h3>
<ul>
<li><strong>Attending postsecondary education, even without completing</strong>, is strongly protective once other factors are controlled for.</li>
<li><strong>Having taken the ACT</strong> is associated with meaningfully lower odds of persistent non-sustained employment.</li>
<li><strong>Reaching a CTE achievement threshold</strong> (whether as a concentrator/completer or a participant) is consistently protective.</li>
<li><strong>Coming from a non-English-speaking home</strong> is, notably, protective against this specific mechanism — despite being one of the strongest risk factors for the opposite disconnection mechanism (no employment record).</li>
</ul>
</section>
<section id="protections-against-persistent-no-minnesota-employment-record-status" class="level3">
<h3 class="anchored" data-anchor-id="protections-against-persistent-no-minnesota-employment-record-status">Protections Against Persistent No-Minnesota-Employment-Record Status</h3>
<ul>
<li><strong>Attending postsecondary education, even without completing</strong>, is strongly protective — more strongly protective here than for non-sustained employment specifically.</li>
<li><strong>Economic disadvantage</strong> is, somewhat unexpectedly, protective against this outcome — economically disadvantaged non-completers appear less likely to disappear from Minnesota’s employment record, plausibly reflecting fewer resources to relocate or disengage from the formal system, though this can’t be confirmed directly from the data.</li>
<li><strong>Reaching a CTE achievement threshold and taking more CTE courses overall</strong> are both protective.</li>
<li><strong>Higher local unemployment near the high school</strong> shows a protective association once high school accomplishments are accounted for, though this effect appears to run largely through postsecondary attendance rather than operating independently.</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>